### PR TITLE
Eventually list namespaces for test

### LINKED ISSUE #5836: create/delete/list/set namespace/project test failing regularly on Prow
/kind bug

These tests are failing frequently on Prow:

```
[Fail] odo create/delete/list/set namespace/project tests list namespace [It] should successfully list all the namespaces 

[Fail] odo create/delete/list/set namespace/project tests list project [It] should successfully list all the projects  - Rishika
- https://github.com/redhat-developer/odo/pull/5809 this PR will fix the flaky behavior observed on the CI
```

### PR DESCRIPTION
**Pull request by feloy**
**What type of PR is this:**

/kind tests

**Which issue(s) this PR fixes:**

Fixes #5836 

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

### CODE REVIEW

**Comment by rm3l** [comment]
@feloy If I understood correctly, tests are not passing on Prow because of https://github.com/redhat-developer/service-binding-operator/issues/1172, right?

**Comment by feloy** [comment]
> @feloy If I understood correctly, tests are not passing on Prow because of [redhat-developer/service-binding-operator#1172](https://github.com/redhat-developer/service-binding-operator/issues/1172), right?

Yes, I think so

**Comment by valaparthvi** [comment]
> > @feloy If I understood correctly, tests are not passing on Prow because of [redhat-developer/service-binding-operator#1172](https://github.com/redhat-developer/service-binding-operator/issues/1172), right?
> 
> Yes, I think so

**Comment by feloy** [comment]
I think there has been a misunderstanding. IMO, the still failing tests (8 tests constantly failing) are due to https://github.com/redhat-developer/service-binding-operator/issues/1172, but there are 2 flaky tests that should be fixed with this PR. 

I'll wait for the fix on SBO, and reopen this PR if there are still flaky tests.

**Comment by valaparthvi** [comment]
I closed this PR by mistake, hadn't realized I did that. Feel free to open it @feloy.

**Comment by valaparthvi** [comment]
@feloy should we put this on hold until the SBO issue is resolved?

**Comment by feloy** [comment]
/test v4.10-integration-e2e

This fix is independent from the SBO problem. It tries to fix the problem when the listing of namespaces is not up to date.

I restart the tests as I can see some network errors

**Comment by valaparthvi** [comment]
> This fix is independent from the SBO problem. It tries to fix the problem when the listing of namespaces is not up to date.
> 
> I restart the tests as I can see some network errors

The test fixed by this PR seems to be passing. I'm inclined to merge this PR.

**Comment by feloy** [comment]
I can see the same failure on IBM Windows tests (from another PR):

```
https://cloud.ibm.com/devops/pipelines/929da3ed-6cad-4026-a847-7a8485f20fa4/582614a3-b910-4659-ac27-6288668c5fe6/a1d74ffa-3d39-4dbb-8583-b0a34f87f3bd/1b647bf2-5a73-485b-87de-29789ad66f1f/f4f3f320-fa08-4612-b4a9-3a86e3eefb28?env_id=ibm:yp:eu-de
```

**Comment by feloy** [comment]
SBO has just been updated to v1.1.1, running the tests again:

/test v4.10-integration-e2e

**Comment by feloy** [comment]
> Can we merge this PR?

For me yes it can be merged

**Comment by rm3l** [comment]
> > Can we merge this PR?
> 
> For me yes it can be merged

/approve

**Comment by feloy** [comment]
/override ci/prow/v4.10-integration-e2e

Tests pass on IBM Cloud

**Pull request merged**
