### PR TITLE
Make 3.0.0 the default on the site

### PR DESCRIPTION
**Pull request by cdrage**
**What type of PR is this:**

/kind documentation

**What does this PR do / why we need it:**

* Moves the 3.0.0 documentation to current
* Changes the "intro" page to "introduction" due to limitations of
  docusaurus index paging.

**Which issue(s) this PR fixes:**

Fixes https://github.com/redhat-developer/odo/issues/5842

**PR acceptance criteria:**

- [X] Documentation

**How to test changes / Special notes to the reviewer:**

Signed-off-by: Charlie Drage <charlie@charliedrage.com>

### CODE REVIEW

**Comment by valaparthvi** [comment]
/approve
/lgtm

All the updated links are in place.

**Comment by rm3l** [comment]
image

The text in the top banner seems a bit repetitive to me when we are browsing the 3.0.0 docs, especially the last sentence: `For up-to-date documentation, see the latest version (3.0.0 (Alpha 2) 🚧).`
Would it be possible to hide the last sentence when we are already reading the default version?

**Comment by valaparthvi** [comment]
> image
> 
> The text in the top banner seems a bit repetitive to me when we are browsing the 3.0.0 docs, especially the last sentence: `For up-to-date documentation, see the latest version (3.0.0 (Alpha 2) 🚧).` Would it be possible to hide the last sentence when we are already reading the docs for the latest version?

I think the last sentence is supposed to talk about the stable 2.5.0 version, I remember seeing it somewhere.

**Comment by cdrage** [comment]
> /hold cancel
> 
> `Read the docs` on the main page still points to 2.5.0 docs.

Clear your cookies :) probably why it was doing that.

**Comment by cdrage** [comment]
> > image
> > The text in the top banner seems a bit repetitive to me when we are browsing the 3.0.0 docs, especially the last sentence: `For up-to-date documentation, see the latest version (3.0.0 (Alpha 2) 🚧).` Would it be possible to hide the last sentence when we are already reading the docs for the latest version?
> 
> I think the last sentence is supposed to talk about the stable 2.5.0 version, I remember seeing it somewhere.

I've removed these! :) it shouldn't appear anymore and instead use the 🚧 emoji and that it's "alpha" to indicate it's unreleased.

**Review by rm3l — APPROVED** [review]

**Comment by cdrage** [comment]
Fixed and ready for another review 👍

**Review by rm3l — APPROVED** [review]

**Comment by cdrage** [comment]
Let's merge this in! Got one approval for docs (that's only what's needed). We can see what issues arise this week with broken links, but I've covered all use cases for the README.md as well as wiki + main page (no docusaurus errors)

**Pull request merged**
