### PR TITLE
Adds tabs for windows / linux / mac in deployment documentation

### PR DESCRIPTION
**Pull request by cdrage**
Adds tabs for mac / windows / linux environments in docs

**What type of PR is this:**

/kind documentation

**What does this PR do / why we need it:**
* Updates the documentation with regards to different operating systems
  when deploying an image

**Which issue(s) this PR fixes:**

Fixes https://github.com/redhat-developer/odo/issues/6085

Signed-off-by: Charlie Drage <charlie@charliedrage.com>

### CODE REVIEW

**Comment by cdrage** [comment]
NOTE:

This builds upon the work on: https://github.com/redhat-developer/odo/pull/6071

**Comment by valaparthvi** [comment]
Thoughts on merging this in 6071?

**Comment by valaparthvi** [comment]
@cdrage Can you rebase this branch?

**Comment by cdrage** [comment]
Too many conflicts and reopening another PR so I can clean up all these messages.

**Pull request closed without merging**
