### PR TITLE
Update devfiles information and used images for ppc64le

### PR DESCRIPTION
**Pull request by Mahima-Gaikwad**
**What type of PR is this:

What does this PR do / why we need it:**

For Power, we have verified latest languages and runtimes refer to https://github.com/devfile/registry/tree/main/stacks. So this PR is to update document https://odo.dev/docs/tutorials/deploying-a-devfile-using-odo-on-IBM-Z-and-Power for Power.
All the added type of languages have been verified on Power.

**Which issue(s) this PR fixes:**

Fixes #

**PR acceptance criteria:**

- [x] Documentation 

**How to test changes / Special notes to the reviewer:**

/area system-PZ

### CODE REVIEW

**Comment by valaparthvi** [comment]
@Mahima-Gaikwad This PR is good to go, right?
If yes, then feel free to unhold this PR.

**Comment by feloy** [comment]
/override Kubernetes Integration Tests/Kubernetes Integration Tests

**Comment by feloy** [comment]
/override OpenShift Integration tests/OpenShift Integration tests
/override Unit Tests/Unit Tests
/override validator/Validate

Doc only 
Tests failing because of quote in PR title

**Comment by Mahima-Gaikwad** [comment]
> @Mahima-Gaikwad This PR is good to go, right? If yes, then feel free to unhold this PR.

Yes, PR good to go.

**Pull request merged**
