### PR TITLE
Use latest alizer library version, including .net detection

### LINKED ISSUE #5803: Use latest vesion odo alizer library
/kind feature

## Which functionality do you think we should add?

The alizer library has had new features added recently. odo should use the latest version of this library.

## Why is this needed?

To better detect devfile from odo

### PR DESCRIPTION
**Pull request by feloy**
**What type of PR is this:**

/kind feature

**What does this PR do / why we need it:**

**Which issue(s) this PR fixes:**

Fixes #5803 

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

### CODE REVIEW

**Review by rm3l — APPROVED** [review]
LGTM.

As discussed in https://github.com/redhat-developer/odo/pull/5774/files#r885866357, maybe we could now also update the Quickstart Guide for .NET to include a more realistic sample output? Could be done here or in a subsequent PR.
cc @cdrage

**Comment by feloy** [comment]
> As discussed in https://github.com/redhat-developer/odo/pull/5774/files#r885866357, maybe we could now also update the Quickstart Guide for .NET to include a more realistic sample output? Could be done here or in a subsequent PR.

I updated the doc, but Alizer does not detect the version of dotnet in this case.

**Comment by valaparthvi** [comment]
I am inclined to approve this because the updated library detects the language correctly if not the version, unlike the current library version that we have in main.

I have a dotnet 3.1 project here.
```sh
➜  ls             
app.csproj  appsettings.Development.json  appsettings.json  Controllers  Models  Program.cs  Properties  Startup.cs  Views  wwwroot

➜  cat app.csproj 
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>



</Project>
```
**Result from main:**
```sh
➜  odo init
  __
 /  \__     Initializing new component
 \__/  \    Files: Source code detected, a Devfile will be determined based upon source code autodetection
 /  \__/    odo version: v3.0.0-alpha3
 \__/

Interactive mode enabled, please answer the following questions:
Based on the files in the current directory odo detected
Language: javascript
Project type: nodejs
The devfile "nodejs" from the registry "MyRegistry" will be downloaded.
? Is this correct? No
^C
```
**Result from updated library:**
```sh
➜  odo init
  __
 /  \__     Initializing new component
 \__/  \    Files: Source code detected, a Devfile will be determined based upon source code autodetection
 /  \__/    odo version: v3.0.0-alpha2
 \__/

Interactive mode enabled, please answer the following questions:
Based on the files in the current directory odo detected
Language: dotnet
Project type: dotnet
The devfile "dotnet50" from the registry "MyRegistry" will be downloaded.
? Is this correct? (Y/n) 
 ✗  interrupt
the command failed, the devfile has been removed from current directory
```

/approve

**Review by rm3l — APPROVED** [review]

**Comment by feloy** [comment]
/override ci/prow/v4.10-integration-e2e
IBM Tests pass

**Comment by rm3l** [comment]
> > As discussed in https://github.com/redhat-developer/odo/pull/5774/files#r885866357, maybe we could now also update the Quickstart Guide for .NET to include a more realistic sample output? Could be done here or in a subsequent PR.
> 
> I updated the doc, but Alizer does not detect the version of dotnet in this case.

Great - thanks for the changes. Maybe we can open an issue in the Alizer repo then?

**Pull request merged**
