### PR TITLE
Add blog post for v3.0.0-beta3 and update installation docs

### LINKED ISSUE #5906: 🎉 Release for Sprint 222 🎉
Issue to track work for publishing a new release of `odo` at the end of the Sprint.

- Version: **v3.0.0-beta3**
- Target release process start date: **Aug 18, 2022**

Note: Write an announcement blog post once the release is done.

### PR DESCRIPTION
**Pull request by valaparthvi**
**What type of PR is this:**
/kind documentation
/area documentation

**What does this PR do / why we need it:**
This adds blog post for odo v3.0.0-beta3

**Which issue(s) this PR fixes:**

Fixes #5906 

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [x] Documentation 

**How to test changes / Special notes to the reviewer:**

### CODE REVIEW

**Comment by valaparthvi** [comment]
/hold
Until the release on 18th August.

**Review by rm3l — CHANGES_REQUESTED** [review]
Can you also include the video about the `odo logs` performance improvement? https://www.youtube.com/watch?v=tfIOhU7H4zI&list=PLGMB2PY4SNOoDKAk8qQ8nhva3ff1fgZgr&index=3

**Review by rm3l — CHANGES_REQUESTED** [review]
One last comment: can you also update `docs/website/docusaurus.config.js` to change the current version label from Beta 2 to Beta 3?

**Review by rm3l — APPROVED** [review]
/approve

**Comment by cdrage** [comment]
Merging since the failed test is a false negative 👍

**Pull request merged**
