### PR TITLE
remove report collection

### PR DESCRIPTION
**Pull request by anandrkskd**
Signed-off-by: anandrkskd <anandrkskd@gmail.com>

**What type of PR is this:**
/area testing

**What does this PR do / why we need it:**
This will remove the report collection from tests

**Which issue(s) this PR fixes:**
Fixes [#5875](https://github.com/redhat-developer/odo/issues/5875)

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

### CODE REVIEW

**Review by rm3l — CHANGES_REQUESTED** [review]
@anandrkskd I don't see any meaningful changes in this PR, except removing empty lines. Is that expected?

**Comment by anandrkskd** [comment]
> @anandrkskd I don't see any meaningful changes in this PR, except removing empty lines. Is that expected?

Yes, as we are not  creating artifacts/reports in our tests, these steps are leading the PRs and periodic jobs to fail on prow.

**Comment by dharmit** [comment]
> > @anandrkskd I don't see any meaningful changes in this PR, except removing empty lines. Is that expected?
> 
> Yes, as we are not creating artifacts/reports in our tests, these steps are leading the PRs and periodic jobs to fail on prow.

I'm still confused. The lines I see getting removed in this PR are simply empty lines. How are they going to help solve the periodic tests' failure issue? I'm lost. 😕

**Comment by anandrkskd** [comment]
> I'm still confused. The lines I see getting removed in this PR are simply empty lines. How are they going to help solve the periodic tests' failure issue? I'm lost. confused

My bad, I made those changes in another PR and those are merged.

**Comment by dharmit** [comment]
> My bad, I made those changes in another PR as part of clean up and that PR is now merged.

So do we need this PR around any more?

**Comment by anandrkskd** [comment]
I think we can close this one. /close

**Pull request closed without merging**
