### PR TITLE
Bump version to 0.0.11

### PR DESCRIPTION
**Pull request by anmolbabu**
Signed-off-by: anmolbabu <anmolbudugutta@gmail.com>

### CODE REVIEW

**Comment by surajnarwade** [comment]
@anmolbabu , version on homebrew is different, that's why it is failing

**Comment by anmolbabu** [comment]
> @anmolbabu , version on homebrew is different, that's why it is failing

But I changed it as in https://github.com/kadel/homebrew-odo/blob/master/Formula/odo.rb#L4-L5
May be as @cdrage mentioned the order was important...
Release after the homebrew pr was merged ahould have been followed...

**Comment by cdrage** [comment]
@surajnarwade Isn't it a holiday over there? :D haha. Are you able to update the version on Homebrew? We're trying to do a release.

**Comment by surajnarwade** [comment]
@cdrage yeah it was holiday, but failed master build of ODO triggered my OCD :laughing:

**Comment by kadel** [comment]
https://github.com/kadel/homebrew-odo/blob/master/Formula/odo.rb#L4-L5
should be updated only after the 0.0.11 version is released

**Comment by surajnarwade** [comment]
All green, merging :tada:

**Pull request merged**
