### PR TITLE
Replace odo delete component integration with unit tests

### LINKED ISSUE #6889: Rewrite `delete component` integration tests as unit tests
Move odo delete component tests from integration to unit tests

### PR DESCRIPTION
**Pull request by feloy**
**What type of PR is this:**

/kind code-refactoring
/area testing

**What does this PR do / why we need it:**

**Which issue(s) this PR fixes:**

Fixes partially #6889 

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

### CODE REVIEW

**Review by rm3l — APPROVED** [review]
Thanks for this!

**Comment by feloy** [comment]
/override OpenShift-Integration-tests/OpenShift-Integration-tests

```
[FAILED] [423.619 seconds]
odo dev command tests when a component is bootstrapped when odo dev is executed and Ephemeral is set to false [BeforeEach] when killing odo dev and running odo delete component --wait should have deleted all resources before returning
  [BeforeEach] /go/odo_1/tests/integration/cmd_dev_test.go:527
  [It] /go/odo_1/tests/integration/cmd_dev_test.go:544
```

```
[FAILED] [422.289 seconds]
odo dev command tests when running odo dev with devfile containing volume-component - without metadata.name [BeforeEach] should successfully use the volume components in container components
  [BeforeEach] /go/odo_1/tests/integration/cmd_dev_test.go:2185
  [It] /go/odo_1/tests/integration/cmd_dev_test.go:2210

```

**Comment by feloy** [comment]
/ovreride windows-integration-test/Windows-test

```
 [FAILED] [102.501 seconds]
odo describe/list binding command tests when creating a component with a binding as environment variables (service in namespace "") when Starting a Pg service when running dev session when changing the current namespace [It] should list the binding with --namespace flag - command: [list binding]
C:/Users/Administrator.ANSIBLE-TEST-VS/4194/tests/integration/cmd_describe_list_binding_test.go:810
```

```
[FAILED] [213.386 seconds]
odo dev command tests 1. devfile contains composite apply command when odo dev is running with image build extra args [It] should execute the composite apply commands successfully
C:/Users/Administrator.ANSIBLE-TEST-VS/4194/tests/integration/cmd_dev_test.go:2320
```

```
odo dev command tests when a component is bootstrapped when Automount volumes are present in the namespace when odo dev is executed [BeforeEach] should mount the volumes
  [BeforeEach] C:/Users/Administrator.ANSIBLE-TEST-VS/4194/tests/integration/cmd_dev_test.go:759
```

```
[FAILED] [247.804 seconds]
odo list with devfile devfile has missing metadata when projectType is missing when the component is pushed in dev mode [BeforeEach] should show the language for 'Type' in odo list
  [BeforeEach] C:/Users/Administrator.ANSIBLE-TEST-VS/4194/tests/integration/cmd_devfile_list_test.go:324
  [It] C:/Users/Administrator.ANSIBLE-TEST-VS/4194/tests/integration/cmd_devfile_list_test.go:334
````

**Comment by feloy** [comment]
/override windows-integration-test/Windows-test

```
 [FAILED] [102.501 seconds]
odo describe/list binding command tests when creating a component with a binding as environment variables (service in namespace "") when Starting a Pg service when running dev session when changing the current namespace [It] should list the binding with --namespace flag - command: [list binding]
C:/Users/Administrator.ANSIBLE-TEST-VS/4194/tests/integration/cmd_describe_list_binding_test.go:810
```

```
[FAILED] [213.386 seconds]
odo dev command tests 1. devfile contains composite apply command when odo dev is running with image build extra args [It] should execute the composite apply commands successfully
C:/Users/Administrator.ANSIBLE-TEST-VS/4194/tests/integration/cmd_dev_test.go:2320
```

```
odo dev command tests when a component is bootstrapped when Automount volumes are present in the namespace when odo dev is executed [BeforeEach] should mount the volumes
  [BeforeEach] C:/Users/Administrator.ANSIBLE-TEST-VS/4194/tests/integration/cmd_dev_test.go:759
```

```
[FAILED] [247.804 seconds]
odo list with devfile devfile has missing metadata when projectType is missing when the component is pushed in dev mode [BeforeEach] should show the language for 'Type' in odo list
  [BeforeEach] C:/Users/Administrator.ANSIBLE-TEST-VS/4194/tests/integration/cmd_devfile_list_test.go:324
  [It] C:/Users/Administrator.ANSIBLE-TEST-VS/4194/tests/integration/cmd_devfile_list_test.go:334
````

**Pull request merged**
