### PR TITLE
Remove v2delete reference from Makefile

### LINKED ISSUE #5559: remove `odo v2delete`
more info in #5521 

## Acceptance criteria 
- [x] test cases for the removed command should be removed, tests cases that use removed commands should be updated
- [x] commands that are going to be removed need to be removed together with their implementation and test cases
- [ ] all help messages and error messages need to be reviewed and updated to make sure that it doesn't contain a reference to commands that no longer exist
- [x] remove `Delete` function in https://github.com/redhat-developer/odo/blob/a8218725e4e556b76e11ca2194a500bc0f4dee32/pkg/component/component.go#L547

### PR DESCRIPTION
**Pull request by valaparthvi**
**What type of PR is this:**
/kind code-refactoring

**What does this PR do / why we need it:**
This PR removes reference of the old delete test file from Makefile and replaces it with the new one.
**Which issue(s) this PR fixes:**

Fixes #5559 

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**
Run `make test-cmd-delete` and check if it runs the desired set of tests, ie tests/integration/devfile/cmd_delete_test.go

### CODE REVIEW

**Comment by valaparthvi** [comment]
@rm3l @feloy Can one of you verify this for me? I am not very sure if it is collecting the right set of tests.

**Comment by dharmit** [comment]
IIUC, this is just doing cosmetic change (removal of the word `devfile`) because the old and new code both consider the same `tests/integration/devfile/` path. I don't see why this could be a reason we reopened the parent issue.

Correct me if I am wrong.

**Comment by feloy** [comment]
> IIUC, this is just doing cosmetic change (removal of the word `devfile`) because the old and new code both consider the same `tests/integration/devfile/` path. I don't see why this could be a reason we reopened the parent issue.
> 
> Correct me if I am wrong.

The `focus` also changed, by removing the `devfile` word, so it will now focus on the tests in the `tests/integration/devfile/cmd_delete_test.go` file. The change looks good to me

/lgtm

**Comment by anandrkskd** [comment]
> I am not very sure if it is collecting the right set of tests.

I have verified it, it's executing the right set of tests. @valaparthvi 

/approve

**Comment by valaparthvi** [comment]
Great! Thanks for the quick reviews everyone! :)

**Review by rm3l — APPROVED** [review]

**Comment by valaparthvi** [comment]
/test v4.10-integration-e2e
 — Pod got deleted unexpectedly

**Comment by valaparthvi** [comment]
/test v4.10-integration-e2e
— Pod got deleted unexpectedly

**Pull request merged**
