### PR TITLE
Disable loading a single branch when getting git starter project

### LINKED ISSUE #6232: `odo init` - cloning wrong branch of starterProject
/kind bug
```
▶ odo init  --name vertx  --devfile java-vertx --starter vertx-http-example-redhat
  __
 /  \__     Initializing a new component
 \__/  \
 /  \__/    odo version: v3.0.0-rc2
 \__/

 ✓  Downloading devfile "java-vertx" [1s]
 ✗  Downloading starter project "vertx-http-example-redhat" [2s]
 ✗  unable to download starter project "vertx-http-example-redhat": couldn't find remote ref "refs/heads/master"
the command failed, the devfile has been removed from current directory
```

default branch in https://github.com/openshift-vertx-examples/vertx-http-example-redhat is `main` but odo is trying to clone `master`.

inside devfile.yaml starter project is defined as this
```
  - name: vertx-health-checks-example-redhat
    git:
      remotes:
        origin: https://github.com/openshift-vertx-examples/vertx-health-checks-example-redhat
```
which is correct. If there is no `revision` defined it should use the default branch as defined in repository. It looks like odo is always assuming `master`.

### PR DESCRIPTION
**Pull request by feloy**
**What type of PR is this:**

/kind bug

**What does this PR do / why we need it:**

**Which issue(s) this PR fixes:**

Fixes #6232

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

### CODE REVIEW

**Comment by rm3l** [comment]
Would it make sense to add a test case (E2E maybe) for this, to catch potential future regressions?

**Review by rm3l — APPROVED** [review]
/lgtm

I noticed that `odo` currently does not support checking out from a specific commit ID (branches and tags work great). But this is not related to the changes in this PR. I'll create a separate issue.

**Comment by feloy** [comment]
/override v4.11-integration-e2e
Tests pass on IBM Cloud

**Pull request merged**
