### PR TITLE
Remove cluster setup

### PR DESCRIPTION
**Pull request by cdrage**
Remove cluster setup

**What type of PR is this:**

/kind documentation

**What does this PR do / why we need it:**

Removes the clsuter setup section as it's no longer needed / we assume
that odo developers do not need to touch the cluster.

**Which issue(s) this PR fixes:**

Fixes https://github.com/redhat-developer/odo/issues/6080

Signed-off-by: Charlie Drage <charlie@charliedrage.com>

### CODE REVIEW

**Comment by valaparthvi** [comment]
@cdrage Can you remove references of cluster-setup from add-binding.md and quickstart.md?

**Comment by cdrage** [comment]
> @cdrage Can you remove references of cluster-setup from add-binding.md and quickstart.md? But perhaps add the information about using SBO in add-binding section?

Confused with regards to quickstart? The only cluster setup we have on there is namespace / project creation which is intentional from our cabal talks.

I've gone ahead and moved the references of SBO and removed the links that were no longer working in add-binding.

**Review by valaparthvi — APPROVED** [review]

**Comment by valaparthvi** [comment]
/override Unit-Tests/Unit-Tests

This PR represents docs change.

**Pull request merged**
