### PR TITLE
Move parent devfiles in specific directories

### LINKED ISSUE #6817: Move parent devfiles into specific directories
/kind bug

Parent Devfiles are placed in `pkg/libdevfile/testdata`, but the specification says that all files into the directory of the parent Devfile wil be part of the Devfile stack.

We need to create sub-directories into `pkg/libdevfile/testdata`, one for each parent devfile.

Related to https://github.com/devfile/api/issues/1118

### PR DESCRIPTION
**Pull request by feloy**
**What type of PR is this:**

/kind bug
/area testing

**What does this PR do / why we need it:**

**Which issue(s) this PR fixes:**

Fixes #6817 

The parent devfile is still copied into the current devfile. We need to wait for an option to not copy parent files.

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

### CODE REVIEW

**Review by rm3l — APPROVED** [review]

**Comment by feloy** [comment]
/override odo-podman-test

```
[FAILED] [20.419 seconds]
2023-05-15T14:32:46.4050044Z odo dev command tests port-forwarding for the component when devfile has multiple endpoints when running odo dev [BeforeEach] should expose all endpoints on localhost regardless of exposure(podman=true, manual=true, customPortForwarding=true, customAddress=false) [podman]

[...]

unable to access podman. Do you have podman client installed and configured correctly? cause: timeout (10s) while waiting for Podman version: context deadline exceeded: signal: killed: (read |0: file already closed). Please check the output of the following command: [podman version --format json]
```

```

**Comment by feloy** [comment]
/override Kubernetes-Integration-Tests/Kubernetes-Integration-Tests
/override OpenShift-Integration-tests/OpenShift-Integration-tests

```
[FAILED] [170.059 seconds]
odo remove binding command tests when the component with binding is bootstrapped (bindingName=my-nodejs-app-cluster-sample-ocp) when odo dev is running when binding is removed [It] should have led odo dev to delete ServiceBinding from the cluster
/go/odo_1/tests/integration/cmd_remove_binding_test.go:71
```

**Pull request merged**
