### PR TITLE
[v2 cherrypicking] Undeploy error

### PR DESCRIPTION
**Pull request by valaparthvi**
**What type of PR is this:**

/kind bug

**What does this PR do / why we need it:**

**Which issue(s) this PR fixes:**

Fixes #

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

### CODE REVIEW

**Comment by valaparthvi** [comment]
Merging this PR since it is a Cherrypick to v2.

**Comment by dharmit** [comment]
Please use the `/cherrypick` plugin to create PR. Mainly because manual merging is a bad idea, IMO.

All you need to do on the original PR is make this comment - `/cherrypick v2`. Don't put in code blocks.

**Comment by dharmit** [comment]
See https://github.com/redhat-developer/odo/pull/5315#issuecomment-1016087780 for reference.

**Comment by kadel** [comment]
@valaparthvi please also link the related PR that went into master so we have a record that it was merged into both branches.

**Comment by valaparthvi** [comment]
> Please use the `/cherrypick` plugin to create PR. Mainly because manual merging is a bad idea, IMO.
> 
> All you need to do on the original PR is make this comment - `/cherrypick v2`. Don't put in code blocks.

Idk why, but I remember someone mentioned that cherry-picking with /cherrypick was not working, which is why I manually created this PR and merged it.

**Comment by dharmit** [comment]
> Idk why, but I remember someone mentioned that cherry-picking with /cherrypick was not working, which is why I manually created this PR and merged it.

https://kubernetes.slack.com/archives/C01D6L2NUAG/p1642491094015100?

I opened https://github.com/openshift/release/pull/25382 afterwards to sort it out.

**Pull request merged**
