### PR TITLE
Trigger the IBM Cloud Image Workflow on PRs as well

### PR DESCRIPTION
**Pull request by rm3l**
**What type of PR is this:**
/area testing

**What does this PR do / why we need it:**

For some context, while working on #6586, I wanted to make sure that updating the Go version in the Dockerfile will not break the image (this happened already in the past - see https://github.com/redhat-developer/odo/pull/6166#discussion_r1016623089).
I checked manually but thought it would be nice to have our Workflow check that instead.
So this PR allows us to test that the image can be built successfully on PRs as well.

Pushing the image to the registry is run only upon a push on the `main` branch.

**Which issue(s) this PR fixes:**
&mdash;

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**
An example of workflow run on this PR: https://github.com/redhat-developer/odo/actions/runs/4135154988/jobs/7147225272

### CODE REVIEW

**Comment by rm3l** [comment]
/override Kubernetes-Integration-Tests/Kubernetes-Docs-Integration-Tests

Not applicable

**Comment by valaparthvi** [comment]
Can you help me understand what is this image used for? I read the Dockerfile and and odo-robot code but it did not make much sense to me.

**Comment by anandrkskd** [comment]
> Can you help me understand what this image is used for? I read the Dockerfile and and odo-robot code but it did not make much sense to me.

We use this image for our test on IBM Cloud, if you check stage configuration you will see we are using a custom docker image.

**Comment by rm3l** [comment]
> > Can you help me understand what this image is used for? I read the Dockerfile and and odo-robot code but it did not make much sense to me.
> 
> We use this image for our test on IBM Cloud, if you check stage configuration you will see we are using a custom docker image. This image contains everything we need to build odo, execute tests against it and upload logs to IBM Cloud bucket

Yes, as written by Anand, that's what this image is used for. IBM Cloud will spin up a container off of this image (set in the stage configuration) that will run the test script (also set in the stage configuration).
This image is currently built and pushed only upon a Git push on `main`, but I wanted to make sure it was also built (locally on the runner) for PRs as well, to make sure it builds at least.

**Review by feloy — APPROVED** [review]

**Pull request merged**
