### PR TITLE
Adding tests for `odo create` with git source

### PR DESCRIPTION
**Pull request by ashetty1**
Existing tests have been modified to use git source instead of local source

### CODE REVIEW

**Comment by kadel** [comment]
Fail because of https://github.com/redhat-developer/odo/issues/439

**Comment by cdrage** [comment]
Whats the status of this @ashetty1 ?

**Comment by kadel** [comment]
@ashetty1 is this still blocked?

**Comment by kadel** [comment]
Please don't forget to update https://github.com/redhat-developer/odo/blob/master/tests/e2e/README.md

**Comment by kadel** [comment]
Is this still blocked?

**Comment by ashetty1** [comment]
The tests that were added have now been added  in PR #625 as part of the refactoring exercise. Hence closing this PR.

**Pull request closed without merging**
