### PR TITLE
Use an image with pre-installed oc/kubectl/ibmcloud for IBM Pipelines

### PR DESCRIPTION
**Pull request by feloy**
**What type of PR is this?**

/kind tests

**What does this PR do / why we need it**:

Modifies the IBM scripts to use a Docker image with preinstalled tools: oc, kubectl, ibmcloud, gh

### CODE REVIEW

**Comment by feloy** [comment]
OpenShift Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5269-openshift-tests-96.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5269-openshift-tests-96.html)

**Comment by feloy** [comment]
Unit Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5269-unit-tests-80.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5269-unit-tests-80.html)

**Comment by dharmit** [comment]
Where in this PR have you specified the container image? I'm confused.

**Comment by feloy** [comment]
> Where in this PR have you specified the container image? I'm confused.

The image is specified in the IBM Cloud console, it is done manually for the moment as there is no way to define pipelines with Ansible

**Comment by feloy** [comment]
Kubernetes Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5269-kubernetes-tests-67.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5269-kubernetes-tests-67.html)

**Comment by feloy** [comment]
Unit Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5269-unit-tests-81.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5269-unit-tests-81.html)

**Comment by feloy** [comment]
OpenShift Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5269-openshift-tests-97.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5269-openshift-tests-97.html)

**Comment by feloy** [comment]
Kubernetes Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5269-kubernetes-tests-68.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5269-kubernetes-tests-68.html)

**Comment by feloy** [comment]
Unit Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5269-unit-tests-82.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5269-unit-tests-82.html)

**Comment by feloy** [comment]
OpenShift Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5269-openshift-tests-98.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5269-openshift-tests-98.html)

**Comment by feloy** [comment]
Kubernetes Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5269-kubernetes-tests-70.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5269-kubernetes-tests-70.html)

**Comment by feloy** [comment]
OpenShift Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5269-openshift-tests-100.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5269-openshift-tests-100.html)

**Comment by feloy** [comment]
Unit Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5269-unit-tests-84.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5269-unit-tests-84.html)

**Comment by feloy** [comment]
Unit Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5269-unit-tests-90.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5269-unit-tests-90.html)

**Comment by feloy** [comment]
Kubernetes Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5269-kubernetes-tests-76.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5269-kubernetes-tests-76.html)

**Comment by feloy** [comment]
OpenShift Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5269-openshift-tests-106.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5269-openshift-tests-106.html)

**Comment by feloy** [comment]
/test psi-kubernetes-integration-e2e

```
[Fail] odo devfile push command tests devfile is modified odo push -f is executed when java-springboot application is created and pushed [BeforeEach] should push the component successfully 
```

**Comment by feloy** [comment]
/test psi-kubernetes-integration-e2e

Timed out after 4h

**Pull request merged**
