### PR TITLE
Fix oc to odo project translation

### LINKED ISSUE #6898: Proposed command: odo create project set <project-name> doesn't work
/kind bug

## What versions of software are you using?

**Operating System:**
Ubuntu 22.04

**Output of `odo version`:**
v.3.6.0

## How did you run odo exactly?
I've logged in with odo:
```
odo login -u <username> <addr>
# output
Connecting to the OpenShift cluster

Logged into *** as *** using existing credentials.

You don't have any projects. You can try to create a new project, by running

    odo create project set <project-name>
```

## Actual behavior
When I tried to type the `odo create project set <project-name>` command I had:

```
$ odo create project set my_project
Error: accepts 1 arg(s), received 2
Usage:
  odo create namespace [flags]

Aliases:
  namespace, project

Examples:
  # Create a new namespace and set it as the current active namespace
  odo create namespace my-namespace

Flags:
  -h, --help   Help for namespace
  -w, --wait   Wait until the namespace is ready

Additional Flags:
      --kubeconfig string    Paths to a kubeconfig. Only required if out-of-cluster.
  -o, --o string             Specify output format, supported format: json
  -v, --v Level              Number for the log level verbosity. Level varies from 0 to 9 (default 0).
      --var stringArray      Variable to override Devfile variable and variables in var-file
      --var-file string      File containing variables to override Devfile variables
      --vmodule moduleSpec   Comma-separated list of pattern=N settings for file-filtered logging

 ✗  accepts 1 arg(s), received 2
```

## Expected behavior
I would expect the login command to propose `odo create project <project-name>` without set, as with this command I was able to continue.

## Any logs, error output, etc?
All logs are mentioned above.

### PR DESCRIPTION
**Pull request by valaparthvi**
**What type of PR is this:**
/kind bug

**What does this PR do / why we need it:**

**Which issue(s) this PR fixes:**

Fixes #6898

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**
This fix is specific to OpenShift. Even though I have not been able to test this fix due to the lack of an OpenShift cluster, I believe it should still work.

### CODE REVIEW

**Review by rm3l — CHANGES_REQUESTED** [review]
Hey @valaparthvi !

Great to see you contributing to odo ;-)

Your changes work great for the issue reported.
However, I noticed a regression when the user already has access to more than one project.

```
$ odo login -u developer https://api.crc.testing:6443                                                                                                                                          
Connecting to the OpenShift cluster                                                                                                                                                            
                                                                                                                                                                                               
Logged into "https://api.crc.testing:6443" as "developer" using existing credentials.                                                                                                          
                                                                                                                                                                                               
You don't have any projects. You can try to create a new project, by running                                                                                                                   
                                                                                                                                                                                               
    odo create project <project-name>
```

```
$ odo create project test                                                                                                                                                                      
 ✓  Creating the project "test" [150ms]                                                                                                                                                        
 ✓  Project "test" is ready for use                                                                                                                                                            
 ✓  New project created and now using project: test                                                                                                                                            

$ odo login -u developer https://api.crc.testing:6443                                                                                                                                          
Connecting to the OpenShift cluster                                                                                                                                                            
                                                                                                                                                                                               
Logged into "https://api.crc.testing:6443" as "developer" using existing credentials.                                                                                                          
                                                                                                                                                                                               
You have one project on this server: "test"

Using project "test".
```

Everything looks good until I create an additional project:

```
$ odo create project test2                            
 ✓  Creating the project "test2" [165ms]
 ✓  Project "test2" is ready for use
 ✓  New project created and now using project: test2
```

```
$ odo login -u developer https://api.crc.testing:6443
Connecting to the OpenShift cluster

Logged into "https://api.crc.testing:6443" as "developer" using existing credentials.

You have access to the following projects and can switch between them with 'odo project <project-name>':

    test
  * test2

Using project "test2".
```

Now, the output displays `'odo project <project-name>'`, which is not accurate. It should display `'odo set project <project-name>'` instead

**Comment by valaparthvi** [comment]
>Now, the output displays 'odo project <project-name>', which is not accurate. It should display 'odo set project <project-name>' instead

This is weird. I don't exactly understand why that is so, and I'm unable to debug it, but I'm going to make some changes, can you see if it works? If not, can you help me debug (when you can find the time) ?

>Great to see you contributing to odo ;-)

Haha, me too :D

**Comment by rm3l** [comment]
> If not, can you help me debug (when you can find the time) ?
>
Sure. I was thinking maybe you could add a simple unit test for the `filteredInformation` function, based on the output of `oc login`. I'll send you what `oc login` returns and then based on that, you could write unit tests that would check that the replacements work correctly.
1. 1st case: login with no projects:
  - Input:
```
Logged into "https://api.crc.testing:6443" as "developer" using existing credentials.

You don't have any projects. You can try to create a new project, by running

    oc new-project <projectname>
```
  - Expected:
```
Logged into "https://api.crc.testing:6443" as "developer" using existing credentials.

You don't have any projects. You can try to create a new project, by running

    odo create project <project-name>
```

2. 2nd case: login with only 1 project:
  - Input:

```
Logged into "https://api.crc.testing:6443" as "developer" using existing credentials.

You have one project on this server: "test1"

Using project "test1".
```
  - Expected:

```
Logged into "https://api.crc.testing:6443" as "developer" using existing credentials.

You have one project on this server: "test1"

Using project "test1".
```

3. 3rd case: login with more than one project:
  - Input:
```
Logged into "https://api.crc.testing:6443" as "developer" using existing credentials.

You have access to the following projects and can switch between them with 'oc project <projectname>':

    test1
    test2
  * test3

Using project "test3".
```
  - Expected:
```
Logged into "https://api.crc.testing:6443" as "developer" using existing credentials.

You have access to the following projects and can switch between them with 'odo set project <project-name>':

    test1
    test2
  * test3

Using project "test3".
```

I hope that would help.

**Review by rm3l — COMMENTED** [review]
Thanks for adding the unit test cases. I was surprised at first sight to see them passing, as the issue with more than one project still persists on my side :-)
After digging a little bit, I narrowed it down to how we configure `LoginOptions`. I noticed that the `CommandName` field actually changes the output of the login process.
So I guess that's why we are seeing `odo project <projectname>`, which did not get replaced by `filteredInformation`.

So I think we need to change it to `oc` for `filtteredInformation` to work properly:

```diff
diff --git a/pkg/auth/login.go b/pkg/auth/login.go
index a7909aae8..ee90ce1f7 100644
--- a/pkg/auth/login.go
+++ b/pkg/auth/login.go
@@ -35,7 +35,7 @@ func (o KubernetesClient) Login(server, username, password, token, caAuth string
 
        a := login.LoginOptions{
                Server:         server,
-               CommandName:    "odo",
+               CommandName:    "oc",
                CAFile:         caAuth,
                InsecureTLS:    skipTLS,
                Username:       username,
```

After that, everything works properly.
Thanks.

**Review by rm3l — APPROVED** [review]

**Comment by rm3l** [comment]
```
[FAILED] error while sending or expecting line: "Enter value for "DEBUG_PORT_PROJECT" environment variable"
  === output of command '["odo" "init"]' read so far ===
  I0714 10:27:45.745503    8466 implem.go:114] The path for preference file is /tmp/860642052/preference.yaml
  I0714 10:27:45.747471    8466 util.go:198] path /tmp/2329489644/devfile.yaml doesn't exist, skipping it
  I0714 10:27:45.747827    8466 util.go:198] path /tmp/2329489644/.devfile.yaml doesn't exist, skipping it
  I0714 10:27:45.748105    8466 util.go:198] path /tmp/2329489644/devfile.yaml doesn't exist, skipping it
    __
   /  \__     Initializing a new component
   \__/  \    Files: Source code detected, a Devfile will be determined based upon source code autodetection
   /  \__/    odo version: v3.12.0
   \__/
  
  Interactive mode enabled, please answer the following questions:
   â€¢  Determining a Devfile for the current directory  ...
  

 âœ“  Determining a Devfile for the current directory [368ms]
  Based on the files in the current directory odo detected
  Language: JavaScript
  Project type: Node.js
  Application ports: 3000
  The devfile "nodejs:2.1.1" from the registry "DefaultDevfileRegistry" will be downloaded.
  ? Is this correct? (Y/n) 
  ? Is this correct? Yes
   â€¢  Downloading devfile "nodejs:2.1.1" from registry "DefaultDevfileRegistry"  ...
  I0714 10:27:46.128386    8466 registry.go:53] sending telemetry data: library.TelemetryData{User:"", Locale:"", Client:"odo"}
  

 âœ“  Downloading devfile "nodejs:2.1.1" from registry "DefaultDevfileRegistry" [65ms]
  I0714 10:27:46.185775    8466 context.go:172] absolute devfile path: '/tmp/2329489644/devfile.yaml'
  I0714 10:27:46.185798    8466 context.go:113] absolute devfile path: '/tmp/2329489644/devfile.yaml'
  I0714 10:27:46.189350    8466 content.go:48] converted devfile YAML to JSON
  I0714 10:27:46.191303    8466 apiVersion.go:60] devfile schemaVersion: '2.1.0'
  I0714 10:27:46.191485    8466 helper.go:56] devfile apiVersion '2.1.0' is supported
  I0714 10:27:46.208237    8466 schema.go:61] validated devfile schema
  I0714 10:27:46.211122    8466 applicationports.go:28] Found 1 container components in Devfile at path "/tmp/2329489644/devfile.yaml"
  
  â†ª Container Configuration "runtime":
    OPEN PORTS:
      - 3000
      - 5858
    ENVIRONMENT VARIABLES:
      - DEBUG_PORT = 5858
  
  ? Select container for which you want to change configuration?  [Use arrows to move, type to filter]
    runtime
  > NONE - configuration is correct
  runtime
  ? Select container for which you want to change configuration? r  [Use arrows to move, type to filter]
    runtime
  > NONE - configuration is correct
  ? Select container for which you want to change configuration? ru  [Use arrows to move, type to filter]
  > runtime
  ? Select container for which you want to change configuration? run  [Use arrows to move, type to filter]
  > runtime
  ? Select container for which you want to change configuration? runt  [Use arrows to move, type to filter]
  > runtime
  ? Select container for which you want to change configuration? runti  [Use arrows to move, type to filter]
  > runtime
  ? Select container for which you want to change configuration? runtim  [Use arrows to move, type to filter]
  > runtime
  ? Select container for which you want to change configuration? runtime  [Use arrows to move, type to filter]
  > runtime
  ? Select container for which you want to change configuration? runtime
  ? What configuration do you want change?  [Use arrows to move, type to filter]
  > NOTHING - configuration is correct
    Delete port "3000"
    Delete port "5858"
    Add new port
    Delete environment variable "DEBUG_PORT"
    Add new environment variable
  ? What configuration do you want change? D  [Use arrows to move, type to filter]
  > Delete port "3000"
    Delete port "5858"
    Add new port
    Delete environment variable "DEBUG_PORT"
    Add new environment variable
  ? What configuration do you want change? De  [Use arrows to move, type to filter]
  > Delete port "3000"
    Delete port "5858"
    Delete environment variable "DEBUG_PORT"
  ? What configuration do you want change? Del  [Use arrows to move, type to filter]
  > Delete port "3000"
    Delete port "5858"
    Delete environment variable "DEBUG_PORT"
  ? What configuration do you want change? Dele  [Use arrows to move, type to filter]
  > Delete port "3000"
    Delete port "5858"
    Delete environment variable "DEBUG_PORT"
  ? What configuration do you want change? Delet  [Use arrows to move, type to filter]
  > Delete port "3000"
    Delete port "5858"
    Delete environment variable "DEBUG_PORT"
  ? What configuration do you want change? Delete  [Use arrows to move, type to filter]
  > Delete port "3000"
    Delete port "5858"
    Delete environment variable "DEBUG_PORT"
  ? What configuration do you want change? Delete   [Use arrows to move, type to filter]
  > Delete port "3000"
    Delete port "5858"
    Delete environment variable "DEBUG_PORT"
  ? What configuration do you want change? Delete e  [Use arrows to move, type to filter]
  > Delete environment variable "DEBUG_PORT"
  ? What configuration do you want change? Delete en  [Use arrows to move, type to filter]
  > Delete environment variable "DEBUG_PORT"
  ? What configuration do you want change? Delete env  [Use arrows to move, type to filter]
  > Delete environment variable "DEBUG_PORT"
  ? What configuration do you want change? Delete envi  [Use arrows to move, type to filter]
  > Delete environment variable "DEBUG_PORT"
  ? What configuration do you want change? Delete envir  [Use arrows to move, type to filter]
  > Delete environment variable "DEBUG_PORT"
  ? What configuration do you want change? Delete enviro  [Use arrows to move, type to filter]
  > Delete environment variable "DEBUG_PORT"
  ? What configuration do you want change? Delete environ  [Use arrows to move, type to filter]
  > Delete environment variable "DEBUG_PORT"
  ? What configuration do you want change? Delete environm  [Use arrows to move, type to filter]
  > Delete environment variable "DEBUG_PORT"
  ? What configuration do you want change? Delete environme  [Use arrows to move, type to filter]
  > Delete environment variable "DEBUG_PORT"
  ? What configuration do you want change? Delete environmen  [Use arrows to move, type to filter]
  > Delete environment variable "DEBUG_PORT"
  ? What configuration do you want change? Delete environment  [Use arrows to move, type to filter]
  > Delete environment variable "DEBUG_PORT"
  ? What configuration do you want change? Delete environment   [Use arrows to move, type to filter]
  > Delete environment variable "DEBUG_PORT"
  ? What configuration do you want change? Delete environment v  [Use arrows to move, type to filter]
  > Delete environment variable "DEBUG_PORT"
  ? What configuration do you want change? Delete environment va  [Use arrows to move, type to filter]
  > Delete environment variable "DEBUG_PORT"
  ? What configuration do you want change? Delete environment var  [Use arrows to move, type to filter]
  > Delete environment variable "DEBUG_PORT"
  ? What configuration do you want change? Delete environment vari  [Use arrows to move, type to filter]
  > Delete environment variable "DEBUG_PORT"
  ? What configuration do you want change? Delete environment varia  [Use arrows to move, type to filter]
  > Delete environment variable "DEBUG_PORT"
  ? What configuration do you want change? Delete environment variab  [Use arrows to move, type to filter]
  > Delete environment variable "DEBUG_PORT"
  ? What configuration do you want change? Delete environment variabl  [Use arrows to move, type to filter]
  > Delete environment variable "DEBUG_PORT"
  ? What configuration do you want change? Delete environment variable  [Use arrows to move, type to filter]
  > Delete environment variable "DEBUG_PORT"
  ? What configuration do you want change? Delete environment variable   [Use arrows to move, type to filter]
  > Delete environment variable "DEBUG_PORT"
  ? What configuration do you want change? Delete environment variable "  [Use arrows to move, type to filter]
  > Delete environment variable "DEBUG_PORT"
  ? What configuration do you want change? Delete environment variable "D  [Use arrows to move, type to filter]
  > Delete environment variable "DEBUG_PORT"
  ? What configuration do you want change? Delete environment variable "DE  [Use arrows to move, type to filter]
  > Delete environment variable "DEBUG_PORT"
  ? What configuration do you want change? Delete environment variable "DEB  [Use arrows to move, type to filter]
  > Delete environment variable "DEBUG_PORT"
  ? What configuration do you want change? Delete environment variable "DEBU  [Use arrows to move, type to filter]
  > Delete environment variable "DEBUG_PORT"
  ? What configuration do you want change? Delete environment variable "DEBUG  [Use arrows to move, type to filter]
  > Delete environment variable "DEBUG_PORT"
  ? What configuration do you want change? Delete environment variable "DEBUG_  [Use arrows to move, type to filter]
  > Delete environment variable "DEBUG_PORT"
  ? What configuration do you want change? Delete environment variable "DEBUG_P  [Use arrows to move, type to filter]
  > Delete environment variable "DEBUG_PORT"
  ? What configuration do you want change? Delete environment variable "DEBUG_PO  [Use arrows to move, type to filter]
  > Delete environment variable "DEBUG_PORT"
  ? What configuration do you want change? Delete environment variable "DEBUG_POR  [Use arrows to move, type to filter]
  > Delete environment variable "DEBUG_PORT"
  ? What configuration do you want change? Delete environment variable "DEBUG_PORT  [Use arrows to move, type to filter]
  > Delete environment variable "DEBUG_PORT"
  ? What configuration do you want change? Delete environment variable "DEBUG_PORT"  [Use arrows to move, type to filter]
  > Delete environment variable "DEBUG_PORT"
  ? What configuration do you want change? Delete environment variable "DEBUG_PORT"
  ? What configuration do you want change?  [Use arrows to move, type to filter]
  > NOTHING - configuration is correct
    Delete port "3000"
    Delete port "5858"
    Add new port
    Add new environment variable
  ? What configuration do you want change? A  [Use arrows to move, type to filter]
  > NOTHING - configuration is correct
    Add new port
    Add new environment variable
  ? What configuration do you want change? Ad  [Use arrows to move, type to filter]
  > Add new port
    Add new environment variable
  ? What configuration do you want change? Add  [Use arrows to move, type to filter]
  > Add new port
    Add new environment variable
  ? What configuration do you want change? Add   [Use arrows to move, type to filter]
  > Add new port
    Add new environment variable
  ? What configuration do you want change? Add n  [Use arrows to move, type to filter]
  > Add new port
    Add new environment variable
  ? What configuration do you want change? Add ne  [Use arrows to move, type to filter]
  > Add new port
    Add new environment variable
  ? What configuration do you want change? Add new  [Use arrows to move, type to filter]
  > Add new port
    Add new environment variable
  ? What configuration do you want change? Add new   [Use arrows to move, type to filter]
  > Add new port
    Add new environment variable
  ? What configuration do you want change? Add new e  [Use arrows to move, type to filter]
  > Add new environment variable
  ? What configuration do you want change? Add new en  [Use arrows to move, type to filter]
  > Add new environment variable
  ? What configuration do you want change? Add new env  [Use arrows to move, type to filter]
  > Add new environment variable
  ? What configuration do you want change? Add new envi  [Use arrows to move, type to filter]
  > Add new environment variable
  ? What configuration do you want change? Add new envir  [Use arrows to move, type to filter]
  > Add new environment variable
  ? What configuration do you want change? Add new enviro  [Use arrows to move, type to filter]
  > Add new environment variable
  ? What configuration do you want change? Add new environ  [Use arrows to move, type to filter]
  > Add new environment variable
  ? What configuration do you want change? Add new environm  [Use arrows to move, type to filter]
  > Add new environment variable
  ? What configuration do you want change? Add new environme  [Use arrows to move, type to filter]
  > Add new environment variable
  ? What configuration do you want change? Add new environmen  [Use arrows to move, type to filter]
  > Add new environment variable
  ? What configuration do you want change? Add new environment  [Use arrows to move, type to filter]
  > Add new environment variable
  ? What configuration do you want change? Add new environment   [Use arrows to move, type to filter]
  > Add new environment variable
  ? What configuration do you want change? Add new environment v  [Use arrows to move, type to filter]
  > Add new environment variable
  ? What configuration do you want change? Add new environment va  [Use arrows to move, type to filter]
  > Add new environment variable
  ? What configuration do you want change? Add new environment var  [Use arrows to move, type to filter]
  > Add new environment variable
  ? What configuration do you want change? Add new environment vari  [Use arrows to move, type to filter]
  > Add new environment variable
  ? What configuration do you want change? Add new environment varia  [Use arrows to move, type to filter]
  > Add new environment variable
  ? What configuration do you want change? Add new environment variab  [Use arrows to move, type to filter]
  > Add new environment variable
  ? What configuration do you want change? Add new environment variabl  [Use arrows to move, type to filter]
  > Add new environment variable
  ? What configuration do you want change? Add new environment variable  [Use arrows to move, type to filter]
  > Add new environment variable
  ? What configuration do you want change? Add new environment variable
  ? Enter new environment variable name: 
  ======================
  Unexpected error:
      <*xpty.errPassthroughTimeout | 0xc000e14440>: 
      passthrough i/o timeout
      {
          error: <*errors.errorString | 0xc000e14430>{
              s: "passthrough i/o timeout",
          },
      }
  occurred
  In [It] at: /go/odo_1/tests/helper/helper_interactive.go:111 @ 07/14/23 10:29:46.36
...

Summarizing 1 Failure:
  [FAIL] E2E Test starting with non-empty Directory test debugging [It] should verify developer workflow from non-empty Directory
  /go/odo_1/tests/helper/helper_interactive.go:111

Ran 4 of 4 Specs in 236.694 seconds
FAIL! -- 3 Passed | 1 Failed | 0 Pending | 0 Skipped
```

Unrelated issue with interactive E2E tests - let's keep an eye on this to see if it happens again.

/override OpenShift-Integration-tests/OpenShift-Integration-tests

**Comment by rm3l** [comment]
```
  [odo] I0714 05:13:53.243591    8220 starterserver.go:58] API Server started at localhost:20000/api/v1
  [odo] I0714 05:13:53.243591    8220 kubedev.go:86] Creating new adapter
  [odo] I0714 05:13:53.243591    8220 kubedev.go:94] Creating inner-loop resources for the component
  [odo] I0714 05:13:53.243591    8220 watch.go:101] starting WatchAndPush, path: C:\Users\Administrator.ANSIBLE-TEST-VS\AppData\Local\Temp\3922279337, component: rubney, ignores [.git .odo .odo\odo-file-index.json]
  [odo] I0714 05:13:53.243740    8220 starterserver.go:78] Stopping the API server; encountered error: listen tcp :20000: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
  [odo] I0714 05:13:53.244605    8220 file_watcher.go:130] adding watch on path C:\Users\Administrator.ANSIBLE-TEST-VS\AppData\Local\Temp\3922279337
  [odo] I0714 05:13:53.245189    8220 file_watcher.go:130] adding watch on path C:\Users\Administrator.ANSIBLE-TEST-VS\AppData\Local\Temp\3922279337\.odo
  [odo] I0714 05:13:53.245569    8220 file_watcher.go:130] adding watch on path C:\Users\Administrator.ANSIBLE-TEST-VS\AppData\Local\Temp\3922279337\test
  [odo] I0714 05:13:53.246271    8220 implem.go:114] The path for preference file is C:\Users\Administrator.ANSIBLE-TEST-VS\AppData\Local\Temp\2747934839\preference.yaml
  [odo] I0714 05:13:53.246595    8220 segment.go:264] Checking telemetry enable status
  [odo] Cleaning resources, please wait
  [odo] I0714 05:13:53.246595    8220 segment.go:282] Sending telemetry disabled by env variable
  [odo]  X  error watching deployment: context canceled
  [FAILED] in [BeforeEach] - C:/Users/Administrator.ANSIBLE-TEST-VS/4367/tests/helper/helper_run.go:50 @ 07/14/23 05:14:03.077
  Deleting project: cmd-dev-api-server-test151kqv
...
Summarizing 1 Failure:
  [FAIL] odo dev command with api server tests when the component is bootstrapped when odo dev is run with --api-server flag [BeforeEach] when /component/command endpoint is POSTed should trigger a push
  C:/Users/Administrator.ANSIBLE-TEST-VS/4367/tests/helper/helper_run.go:50

Ran 379 of 936 Specs in 1249.637 seconds
FAIL! -- 378 Passed | 1 Failed | 0 Pending | 557 Skipped
```

Ports conflict issue on Windows - already reported in #6939 

/override windows-integration-test/Windows-test

**Pull request merged**
