### PR TITLE
Bump version to v3.7.0

### PR DESCRIPTION
**Pull request by rm3l**
**What type of PR is this:**

**What does this PR do / why we need it:**

**Which issue(s) this PR fixes:**
Relates to #6413 

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

### CODE REVIEW

**Comment by rm3l** [comment]
```
Expected
      <*url.Error | 0xc00038af30>: {
          Op: "Post",
          URL: "http://127.0.0.1:61285/api/newuser",
          Err: <*errors.errorString | 0xc00007c130>{s: "EOF"},
      }
  to be nil
  In [It] at: C:/Users/Administrator.ANSIBLE-TEST-VS/3255/tests/e2escenarios/e2e_test.go:306

  There were additional failures detected after the initial failure.  Here's a summary - for full details run Ginkgo in verbose mode:
    [FAILED] in [AfterEach] at C:/Users/Administrator.ANSIBLE-TEST-VS/3255/tests/helper/helper_filesystem.go:49
------------------------------


Summarizing 1 Failure:
  [FAIL] E2E Test starting with non-empty Directory add Binding [It] should verify developer workflow of using binding as env in innerloop
  C:/Users/Administrator.ANSIBLE-TEST-VS/3255/tests/e2escenarios/e2e_test.go:306
```

/override windows-integration-test/Windows-test

Flaky E2E test - following up in #6582

**Comment by feloy** [comment]
You would need to update some doc to make the tests pass, for example:
```
 Expected
      <string>:   strings.Join({
        	... // 93 identical bytes
        	"me my-nodejs-app --starter nodejs-angular-starter\n__\n/  \\__     ",
        	"Initializing a new component\n\\__/  \\\n/  \\__/    odo version: v3.",
      - 	"6",
      + 	"7",
        	".0\n\\__/\n\nâœ“  Downloading devfile from \"https://registry.devfile",
        	".io/devfiles/nodejs-angular\" [1s]\nâœ“  Downloading starter proje",
        	... // 249 identical bytes
        }, "")
      
  to be empty
  In [It] at: /go/odo_1/tests/documentation/command-reference/doc_command_reference_init_test.go:123
```

**Comment by rm3l** [comment]
> You would need to update some doc to make the tests pass, for example:
> 
> ```
>  Expected
>       <string>:   strings.Join({
>         	... // 93 identical bytes
>         	"me my-nodejs-app --starter nodejs-angular-starter\n__\n/  \\__     ",
>         	"Initializing a new component\n\\__/  \\\n/  \\__/    odo version: v3.",
>       - 	"6",
>       + 	"7",
>         	".0\n\\__/\n\nâœ“  Downloading devfile from \"https://registry.devfile",
>         	".io/devfiles/nodejs-angular\" [1s]\nâœ“  Downloading starter proje",
>         	... // 249 identical bytes
>         }, "")
>       
>   to be empty
>   In [It] at: /go/odo_1/tests/documentation/command-reference/doc_command_reference_init_test.go:123
> ```

Well, this is expected on one hand, but on the other hand, should we really update the docs at this point (at least until the 3.7.0 binaries are available)? Otherwise, this means that the docs will display 3.7.0, but this version is not published yet.

Anyway, those are "just" sample outputs, so I'll make the changes in the docs.
All tests should pass on the commit that will be tagged.

**Comment by rm3l** [comment]
```
Expected
      <*url.Error | 0xc0006c9800>: {
          Op: "Post",
          URL: "http://127.0.0.1:63288/api/newuser",
          Err: <*errors.errorString | 0xc00007c130>{s: "EOF"},
      }
  to be nil
  In [It] at: C:/Users/Administrator.ANSIBLE-TEST-VS/3256/tests/e2escenarios/e2e_test.go:306

  There were additional failures detected after the initial failure.  Here's a summary - for full details run Ginkgo in verbose mode:
    [FAILED] in [AfterEach] at C:/Users/Administrator.ANSIBLE-TEST-VS/3256/tests/helper/helper_filesystem.go:49
------------------------------


Summarizing 1 Failure:
  [FAIL] E2E Test starting with non-empty Directory add Binding [It] should verify developer workflow of using binding as env in innerloop
  C:/Users/Administrator.ANSIBLE-TEST-VS/3256/tests/e2escenarios/e2e_test.go:306

Ran 7 of 7 Specs in 208.777 seconds
FAIL! -- 6 Passed | 1 Failed | 0 Pending | 0 Skipped
```

/override windows-integration-test/Windows-test

Flaky E2E test - following up in #6582

**Review by feloy — APPROVED** [review]

**Pull request merged**
