### PR TITLE
Fixing e2e tests on minishift:

### PR DESCRIPTION
**Pull request by ashetty1**
In this PR, we do away with http calls on IP:Port (which failed on minishift), but instead create a route using `odo url` and then run curl on that url.

### CODE REVIEW

**Comment by cdrage** [comment]
Just ran this! All tests pass locally / minishift works well.

**Comment by kadel** [comment]
is this going to fix #521 @cdrage?

**Comment by kadel** [comment]
How can I increase test timeout?
I'm facing this:

```
*** Test killed with quit: ran too long (10m0s).
```

**Comment by ashetty1** [comment]
@kadel should we enable adding timeout as an option for `make test-e2e`?

**Comment by cdrage** [comment]
Since https://github.com/redhat-developer/odo/issues/521 is a documentation issue, this PR won't fix it @kadel 

I'm going to contribute a small guide after @syamgk is done with his documentation on tests.

@ashetty1 Yeah! Timeouts / parallel similar to https://github.com/kedgeproject/kedge/blob/master/Makefile#L75 I guess haha

**Comment by ashetty1** [comment]
Ping @cdrage @surajnarwade @mik-dass @syamgk @kadel, want this reviewed and merged so that I can send in another patch on top of this.

**Comment by kadel** [comment]
> Ping @cdrage @surajnarwade @mik-dass @syamgk @kadel, want this reviewed and merged so that I can send in another PR on top of this.

two LGTMs, nothing more is needed merge it!

**Pull request merged**
