### PR TITLE
Wait when Build command fails

### LINKED ISSUE #6671: `odo dev` should exit if the build command fails
/kind user-story

## User Story
As an odo user, I want `odo` to log the build command output only once if it fails and indicate which command in the Devfile should be fixed, so that I can understand why my devfile/source code is not working and fix it without having to scroll through a lot of logs.

See the "Original issue" section below for the original user request.

## Acceptance Criteria 
- [ ] Similar to how the `run`/`debug` commands are handled, if the `build` command fails, `odo dev` should not retry until there is a manual sync triggered (by pressing `p`) or until there are new changes in the local source code or the devfile
- [ ] `odo dev --no watch` should also behave the same way, the only difference being that it should retry only if there is manual sync triggered (by pressing `p`)
- [ ] Make sure it behaves the same way on both cluster and Podman

## Links 
- Related Epic (mandatory): https://github.com/redhat-developer/odo/issues/5848
- Related issues:
  - https://github.com/redhat-developer/odo/issues/6173

---

# Original issue

/kind feature

## Which functionality do you think we should add?

If the build command as defined in the devfile fails, `odo dev` should exit and indicate which command in the devfile should be be fixed/investigated

## Why is this needed?

When bootstrapping a project via `odo init`, it may be the case that the build command needs to be modified so that the application can be compiled.

This is particularly true for go-based projects. The stacks currently available on https://github.com/devfile/registry/blob/main/stacks/go assume there is a `main.go` at the project root. This is not universally true - there is no firm consensus in the go community that this pattern should be adopted, and many teams/projects have their own idioms around "main" files. Example - putting command line invocations in the `cmd` package is common.

Stopping the sync loop and printing the last lines of the log (current behavior) followed by a helpful action statement would improve the developer flow.

### PR DESCRIPTION
**Pull request by feloy**
**What type of PR is this:**

/kind code-refactoring

**What does this PR do / why we need it:**

this PR refactors the `pkg/dev` package to make more code generic between podman and kubernetes platforms. It changes the behaviour when the Build command fails.

**Which issue(s) this PR fixes:**

Fixes #6671 

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

### CODE REVIEW

**Review by rm3l — COMMENTED** [review]
It works great overall - thanks for this refactoring!

One thing I just noticed: when the build command fails on Kubernetes, `odo dev` displays the logs and waits (which is expected); but when I tried pressing `p`, but it did not retrigger the sync..

```
$ odo dev --debug --no-watch
  __
 /  \__     Developing using the "my-nodejs" Devfile
 \__/  \    Namespace: default
 /  \__/    odo version: v3.9.0
 \__/

 ⚠  You are using "default" namespace, odo may not work as expected in the default namespace.
 ⚠  You may set a new namespace by running `odo create namespace <name>`, or set an existing one by running `odo set namespace <name>`

↪ Running on the cluster in Dev mode
 •  Waiting for Kubernetes resources  ...
 ⚠  Pod is Pending
 ✓  Pod is Running
 ✓  Syncing files into the container [132ms]
 ✗  Building your application in container (command: install) [57ms]
Exiting...
Error occurred on Push - watch command was unable to push component: unable to exec command [/bin/sh -c cd ${PROJECT_SOURCE} && (echo Exiting... && exit 1 && npm install) 1>>/proc/1/fd/1 2>>/proc/1/fd/2]: error while streaming command: command terminated with exit code 1


↪ Dev mode
 Keyboard Commands:
[Ctrl+c] - Exit and delete resources from the cluster
     [p] - Manually apply local changes to the application on the cluster
p
```

Nothing happened after pressing `p` (I tried multiple times at different intervals to check).  It works as expected on Podman however.
Is it just me?

**Comment by valaparthvi** [comment]
> Nothing happened after pressing `p` (I tried multiple times at different intervals to check). It works as expected on Podman however.
> Is it just me?

It works for me on K8s cluster.

<details><summary>Details</summary>
<p>

```sh
$ odo dev --debug --no-watch
  __
 /  \__     Developing using the "my-nodejs-app" Devfile
 \__/  \    Namespace: default
 /  \__/    odo version: v3.9.0
 \__/

 ⚠  You are using "default" namespace, odo may not work as expected in the default namespace.
 ⚠  You may set a new namespace by running `odo create namespace <name>`, or set an existing one by running `odo set namespace <name>`

↪ Running on the cluster in Dev mode
 •  Waiting for Kubernetes resources  ...
 ⚠  Pod is Pending
 ✓  Pod is Running
 ✓  Syncing files into the container [138ms]
 ✓  Building your application in container (command: install) [1s]
 •  Executing the application (command: debug)  ...
 ✓  Waiting for the application to be ready [1s]
 -  Forwarding from 127.0.0.1:20001 -> 3000

 -  Forwarding from 127.0.0.1:20002 -> 5858


↪ Dev mode
 Keyboard Commands:
[Ctrl+c] - Exit and delete resources from the cluster
     [p] - Manually apply local changes to the application on the cluster
pPushing files...

 •  Waiting for Kubernetes resources  ...
 ✓  Syncing files into the container [65ms]
 ✓  Building your application in container (command: install) [789ms]
 ✗  Finished executing the application (command: debug) [35s]
 •  Executing the application (command: debug)  ...
 ✓  Waiting for the application to be ready [1s]

↪ Dev mode
 Keyboard Commands:
[Ctrl+c] - Exit and delete resources from the cluster
     [p] - Manually apply local changes to the application on the cluster
```

</p>
</details>

**Review by valaparthvi — CHANGES_REQUESTED** [review]

**Review by rm3l — APPROVED** [review]
Thanks for the refactoring and fixes! It works fine now.

**Comment by feloy** [comment]
/override OpenShift-Integration-tests/OpenShift-Integration-tests

```
[FAILED] [169.775 seconds]
odo remove binding command tests when the component with binding is bootstrapped (bindingName=my-nodejs-app-cluster-sample-ocp) when odo dev is running when binding is removed [It] should have led odo dev to delete ServiceBinding from the cluster
/go/odo_1/tests/integration/cmd_remove_binding_test.go:71

[...]

[odo] I0502 07:47:27.510696    6779 exec.go:49] ExecuteCommand returned an an err: error while streaming command: error sending request: Post "[https://c100-e.eu-de.containers.cloud.ibm.com:31049/api/v1/namespaces/cmd-remove-binding-test71ook/pods/mynode-app-6f4678f6db-bx42v/exec?command=%2Fbin%2Fsh&amp;command=-c&amp;command=cat+%2Fopt%2Fodo%2F.odo_cmd_run.pid+%7C%7C+true&amp;container=runtime&amp;stderr=true&amp;stdout=true&quot;:](https://c100-e.eu-de.containers.cloud.ibm.com:31049/api/v1/namespaces/cmd-remove-binding-test71ook/pods/mynode-app-6f4678f6db-bx42v/exec?command=%2Fbin%2Fsh&command=-c&command=cat+%2Fopt%2Fodo%2F.odo_cmd_run.pid+%7C%7C+true&container=runtime&stderr=true&stdout=true%22:) dial tcp: lookup c100-e.eu-de.containers.cloud.ibm.com: operation was canceled. for command '[/bin/sh -c cat /opt/odo/.odo_cmd_run.pid || true]'
```

**Pull request merged**
