### PR TITLE
Fix ignores files during sync

### LINKED ISSUE #4389: odo doesn't honor directory .gitignore entries like `/target`
/kind bug

## What versions of software are you using?

**Operating System:**  Win 10

**Output of `odo version`:**
odo v2.0.4 (5544b25ec)
Kubernetes: v1.18.3+47c0e71

## How did you run odo exactly?
1. git clone git@github.com:scottkurz/multi-module-devfile.git
2. mvn install    # populate 'target' subdirs on host system
3. odo push -v 7

## Actual behavior

You can see ./war/target* , ./ear/target/*,  ./jar/target/* files get copied into the pod container, both with the odo verbose logging and if you exec into the container.

E.g.:

> I0125 21:43:15.735257   12928 sync.go:127] Corrected destinations: base: /projects file: ear/target/test-classes/it/io/openliberty/guides/multimodules
> I0125 21:43:15.735257   12928 sync.go:121] recursiveTar arguments: srcBase: C:\git, srcFile: multi-mod-dev\ear\target\test-classes\it\io\openliberty\guides\multimodules\IT.class, destBase: /projects, destFile: ear\target\test-classes\it\io\openliberty\guides\multimodules\IT.class
> I0125 21:43:15.735257   12928 sync.go:127] Corrected destinations: base: /projects file: ear/target/test-classes/it/io/openliberty/guides/multimodules/IT.class
> I0

## Expected behavior

The .gitignore entry of:
> target/

should be honored by odo and it should prevent the above files from getting copied into the pod container.

## Any logs, error output, etc?

See above.

### PR DESCRIPTION
**Pull request by feloy**
**What type of PR is this:**

/kind bug

**What does this PR do / why we need it:**

**Which issue(s) this PR fixes:**

Fixes #4389 

**PR acceptance criteria:**

- [ ] Unit test 

- [x] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

### CODE REVIEW

**Review by rm3l — APPROVED** [review]

**Comment by rm3l** [comment]
I noticed that while the changes here worked great for sync'ing, we were still unnecessaringly watching files that were supposed to be ignored. For example, I saw these logs while testing on a sample multi-module Maven project:

```
I0426 10:57:01.415897  907437 watch.go:176] adding watch on path /home/asoro/work/tmp/maven-modular/module2/target
I0426 10:57:01.415905  907437 watch.go:176] adding watch on path /home/asoro/work/tmp/maven-modular/module2/target/classes
I0426 10:57:01.415913  907437 watch.go:176] adding watch on path /home/asoro/work/tmp/maven-modular/module2/target/classes/io
I0426 10:57:01.415920  907437 watch.go:176] adding watch on path /home/asoro/work/tmp/maven-modular/module2/target/classes/io/jitpack
I0426 10:57:01.415929  907437 watch.go:176] adding watch on path /home/asoro/work/tmp/maven-modular/module2/target/generated-sources
I0426 10:57:01.415938  907437 watch.go:176] adding watch on path /home/asoro/work/tmp/maven-modular/module2/target/generated-sources/annotations
I0426 10:57:01.415946  907437 watch.go:176] adding watch on path /home/asoro/work/tmp/maven-modular/module2/target/generated-test-sources
I0426 10:57:01.415955  907437 watch.go:176] adding watch on path /home/asoro/work/tmp/maven-modular/module2/target/generated-test-sources/test-annotations
```

As discussed together, the "watch" part will be fixed in a separate issue/PR.

LGTM so far, but I'll let other reviewers (@dharmit , @valaparthvi ) review and approve.

/lgtm

**Comment by feloy** [comment]
> I tried a scenario where `odo dev` was running on one hand and on the other hand, I executed the following:
> 
> ```shell
> $ echo -e "\nb.txt" >> .gitignore 
> $ echo hello > b.txt 
> ```
> 
> The `odo dev` still triggered a push when `b.txt` was created. Is this expected behaviour?

Is the b.txt synced to the container?

As noted by @rm3l, this PR fixes the files that are synced to the container, but not particularly which files are triggering the sync.

**Comment by feloy** [comment]
> > Is the b.txt synced to the container?
> 
> Yes.
> 
> ```shell
> $ kubectl exec nodejs-app-9964cc475-94ct6 -c runtime -- cat /projects/b.txt
> hello
> ```
> 
> > As noted by @rm3l, this PR fixes the files that are synced to the container, but not particularly which files are triggering the sync.
> 
> OK, this makes a lot more sense now.
> 
> > But if this is a regression, I will try and fix it as part of this PR
> 
> I don't know/remember how it behaved in the past. But I think it was buggier in the past than what you are proposing in this PR. So, maybe, we should let this in and see if the scenario I discussed is a problem to someone for real.
> 
> /approve

After some more tests, I think that modifying the .gitignore file is not supported during a dev session: the initial content will be used during all the session.

**Comment by rm3l** [comment]
> > > Is the b.txt synced to the container?
> > 
> > 
> > Yes.
> > ```shell
> > $ kubectl exec nodejs-app-9964cc475-94ct6 -c runtime -- cat /projects/b.txt
> > hello
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > > As noted by @rm3l, this PR fixes the files that are synced to the container, but not particularly which files are triggering the sync.
> > 
> > 
> > OK, this makes a lot more sense now.
> > > But if this is a regression, I will try and fix it as part of this PR
> > 
> > 
> > I don't know/remember how it behaved in the past. But I think it was buggier in the past than what you are proposing in this PR. So, maybe, we should let this in and see if the scenario I discussed is a problem to someone for real.
> > /approve
> 
> After some more tests, I think that modifying the .gitignore file is not supported during a dev session: the initial content will be used during all the session.

I remember commenting about this issue in this other PR about `odo dev` and `.gitignore` files: https://github.com/redhat-developer/odo/pull/5572#pullrequestreview-926037701
Maybe we should create an issue to keep track of this, or document it somewhere as a known issue.

**Comment by feloy** [comment]
/override ci/prow/unit
Infra errors, IBM cloud tests pass

**Pull request merged**
