### PR TITLE
Update alizer dependency

### PR DESCRIPTION
**Pull request by kadel**
**What type of PR is this:**

**What does this PR do / why we need it:**

Update Alizer to the latest commit https://github.com/redhat-developer/alizer/commit/ad2d3056c08d511e132c67ed8e353a8fc67d5927

**Which issue(s) this PR fixes:**

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

### CODE REVIEW

**Review by rm3l — COMMENTED** [review]
Added a comment on the related issue: https://github.com/redhat-developer/odo/issues/6210#issuecomment-1463509345

**Comment by kadel** [comment]
> Added a comment on the related issue: [#6210 (comment)](https://github.com/redhat-developer/odo/issues/6210#issuecomment-1463509345)

oh, you are right. 

I've removed "fix" from the issue description. This PR doesn't fix that issue, but I think that updating alizer still makes sense.

**Review by rm3l — CHANGES_REQUESTED** [review]
```
go run -mod=vendor github.com/frapposelli/wwhrd check -q
ERRO[0008] Found Non-Approved license                    license=UNKNOWN package=github.com/pjbgf/sha1cd/ubc
ERRO[0008] Found Non-Approved license                    license=UNKNOWN package=github.com/pjbgf/sha1cd
ERRO[0008] Found Non-Approved license                    license=UNKNOWN package=github.com/pjbgf/sha1cd/cgo
FATA[0008] Exiting: Non-Approved license found          
exit status 1
make: *** [Makefile:109: validate-vendor-licenses] Error 1
```

License validation seems to fail. Not sure why `wwhrd` could not find the [Apache 2.0 license](https://github.com/pjbgf/sha1cd/blob/main/LICENSE) for that indirect dependency..
Do we want to add an exception for this dependency?

**Comment by kadel** [comment]
> License validation seems to fail. Not sure why `wwhrd` could not find the [Apache 2.0 license](https://github.com/pjbgf/sha1cd/blob/main/LICENSE) for that indirect dependency..
> Do we want to add an exception for this dependency?

I'll look into that

**Review by rm3l — APPROVED** [review]
```
  [FAILED] Expected
      <*url.Error | 0xc0005e33e0>: {
          Op: "Post",
          URL: "http://127.0.0.1:54632/api/newuser",
          Err: <*errors.errorString | 0xc000088130>{s: "EOF"},
      }
  to be nil
  In [It] at: C:/Users/Administrator.ANSIBLE-TEST-VS/3482/tests/e2escenarios/e2e_test.go:306 @ 03/25/23 10:37:27.085

  There were additional failures detected.  To view them in detail run ginkgo -vv
------------------------------

Summarizing 1 Failure:
  [FAIL] E2E Test starting with non-empty Directory add Binding [It] should verify developer workflow of using binding as env in innerloop
  C:/Users/Administrator.ANSIBLE-TEST-VS/3482/tests/e2escenarios/e2e_test.go:306
```

Flaky E2E test (https://github.com/redhat-developer/odo/issues/6582)

/override windows-integration-test/Windows-test

**Pull request merged**
