### PR TITLE
Removal from OWNERS

### PR DESCRIPTION
**Pull request by cdrage**
Removal from OWNERS

**What type of PR is this:**

/kind cleanup

**What does this PR do / why we need it:**

No longer reviewing / approving the project.

Thanks all for the wonderful years working on `odo`!

**Which issue(s) this PR fixes:**

N/A

Signed-off-by: Charlie Drage <charlie@charliedrage.com>

### CODE REVIEW

**Comment by feloy** [comment]
Thanks @cdrage for all your work on odo 
/lgtm

**Comment by valaparthvi** [comment]
/approve
This is a sad PR :/
But, thank you for all your contributions, Charlie!

**Comment by rm3l** [comment]
Thanks @cdrage for your work on odo !

**Comment by dharmit** [comment]
Thanks for your contributions @cdrage! It was a pleasure. 🍻

**Pull request merged**
