### PR TITLE
Implement devfile state in odo api 

### LINKED ISSUE #6903: Move the `odo dev` web UI state to odo
/kind task
/area dev

- [ ] Move the state (stored currently in WebAssembly module) to odo.
- [ ] Modify the API endpoints to manipulate this state.

## Links 
- Related Epic (mandatory): https://github.com/redhat-developer/odo/issues/6895

### PR DESCRIPTION
**Pull request by feloy**
**What type of PR is this:**

/kind feature

**What does this PR do / why we need it:**

**Which issue(s) this PR fixes:**

Fixes #6903

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

The changes can be tested by:
- starting odo with `ODO_EXPERIMENTAL_MODE=t odo dev --platform podman --api-server` from a directory containing a Devfile
- Starting the ui with `cd ui && ng serve`
- Manually accessing http://localhost:4200 (paste a Devfile into the first page, ...)
- running e2e tests with `cd ui && npm run cypress:run`

### CODE REVIEW

**Review by rm3l — COMMENTED** [review]
Another minor point: can you update `ui/Makefile}  and `ui/devfile.yaml` to remove references to the WebAssembly module?

**Comment by feloy** [comment]
> Also, I was curious as to why the `ui-e2e.yaml` GitHub Workflow did not run, as I was expecting it to not pass at this point.. Can you check why it did not run?

Good catch, there was an error on the paths description. It is running now. Thanks

**Review by rm3l — APPROVED** [review]
Thanks for your work on this!

**Comment by rm3l** [comment]
/override cypress-run

The E2E job will be handled once we have https://github.com/redhat-developer/odo/issues/6943 implemented.

**Pull request merged**
