### PR TITLE
Redo the quickstart guide to odo 3.0.0

### PR DESCRIPTION
**Pull request by cdrage**
**What type of PR is this:**

/kind documentation

**What does this PR do / why we need it:**

This PR adds examples to the odo quickstart guide in order to go into
details with the `odo init`, `odo dev` and `odo deploy` commands.

**Which issue(s) this PR fixes:**

N/A, part of multiple PR's

related to https://github.com/redhat-developer/odo/issues/5682

**PR acceptance criteria:**

- [X] Unit test

- [X] Integration test

- [X] Documentation

**How to test changes / Special notes to the reviewer:**

### CODE REVIEW

**Comment by cdrage** [comment]
This is up for a PRELIMINARY review!

I'm still adding the other examples, but I'd like to get some feedback on the Node.js format / how it is.

Thanks!

**Review by feloy — COMMENTED** [review]
The quickstat guide works great for me :) 

Just some little remarks

**Comment by cdrage** [comment]
Updated! Thanks @feloy

**Comment by cdrage** [comment]
Ready for one last lgtm / approval as I've removed the sections about .Net and Springboot now!

**Review by feloy — APPROVED** [review]

**Comment by cdrage** [comment]
/lgtm

(since we only need 1 approval for docs)

**Comment by feloy** [comment]
/override Kubernetes Integration Tests/Kubernetes Integration Tests
/override OpenShift Integration tests/OpenShift Integration tests

Doc only

**Pull request merged**
