### PR TITLE
Add CLI-reference related to service catalog

### PR DESCRIPTION
**Pull request by surajnarwade**
Added respective command reference related to service catalog in `cli-reference.md`
under docs section

### CODE REVIEW

**Comment by surajnarwade** [comment]
Merge only when #413 gets merged

**Comment by cdrage** [comment]
@surajnarwade You do know that we auto generate this from https://github.com/redhat-developer/odo/blob/master/scripts/cli-reference/generate-cli-reference.go right? We may have to close this PR.

**Comment by surajnarwade** [comment]
I was not aware of that :(

**Comment by surajnarwade** [comment]
I used `make generate-cli-structure` to modify `docs/cli-reference.md`  file now, so that new command reference will get added for  `odo service xxxx`

**Comment by cdrage** [comment]
LGTM!

**Pull request merged**
