### PR TITLE
Remove localconfigLocalConfigProvider abstraction

### PR DESCRIPTION
**Pull request by feloy**
**What type of PR is this:**

/kind code-refactoring

**What does this PR do / why we need it:**

This refactoring is useful for being able to work with Storage without unnecessary localconfigLocalConfigProvider abstraction

### CODE REVIEW

**Review by rm3l — APPROVED** [review]

**Comment by feloy** [comment]
Rebased on main to use go v1.18

**Review by rm3l — APPROVED** [review]

**Comment by rm3l** [comment]
```
unable to download starter project "nodejs-starter": Get "https://github.com/odo-devfiles/nodejs-ex.git/info/refs?service=git-upload-pack": net/http: TLS handshake timeout
```

Let's retrigger the tests.

**Review by rm3l — COMMENTED** [review]
/approve

**Pull request merged**
