### PR TITLE
Implement unlink command

### LINKED ISSUE #929: Implement unlink command
[kind/Feature]

## Which functionality do you think we should add?
Provide `odo unlink` command for unlinking components from another component/services.

Subtask of https://github.com/redhat-developer/odo/issues/171

cc/ @geoand

### PR DESCRIPTION
**Pull request by geoand**
## What is the purpose of this change? What does it change?
Provide an `odo unlink` command which the mirror opposite of `odo link`

Since I was touching code relevant to link anyway, I performed some refactoring on link as well.

## Was the change discussed in an issue?
Fixes #929 

## How to test changes?
Setup multiple components and/or a service.
Link them with `odo link`.
You should now be able to unlink them with `odo unlink`.
Note that support has been added for completion handler for unlink as well

### CODE REVIEW

**Comment by geoand** [comment]
@metacosm how weird would it be if you did not approve :P

**Comment by girishramnani** [comment]
@geoand can we have an e2e test for unlink?

**Comment by geoand** [comment]
@girishramnani that's a good idea. We don't have any for link or unlink, so I will a new type set of tests

**Comment by girishramnani** [comment]
we can if possible consider a scenerio, where someone removes a component and concurrently someone else unlinks it. Just a thought :smile:

**Comment by geoand** [comment]
@girishramnani that seems like an enhancement to be done down the road :)

Currently the e2e test mostly verify the happy path.

**Comment by girishramnani** [comment]
@geoand got it

**Comment by geoand** [comment]
Also another reason I would like to avoid that for the time being, is the (high) risk of introducing test flakes. We have been hit by this in the past and I would like to avoid as much as possible in the future :)

**Comment by geoand** [comment]
@girishramnani A rudimentary link / unlink e2e test suite was added

**Comment by girishramnani** [comment]
LGTM

**Pull request merged**
