### PR TITLE
#686 Adding Java as supported language to README.md

### PR DESCRIPTION
**Pull request by gunnarmorling**

### CODE REVIEW

**Comment by surajnarwade** [comment]
cc @cmoulliard @jorgemoralespou

**Comment by jorgemoralespou** [comment]
SGTM

**Comment by cmoulliard** [comment]
I would prefer to place Spring Boot in first position of the list ;-) LGTM

**Comment by cdrage** [comment]
This LGTM! :+1:

**Comment by cdrage** [comment]
Since only 1 ACK is needed for doc issues, I'm going to go ahead and merge this in.

**Pull request merged**
