### PR TITLE
Updates the README.md with a new layout

### PR DESCRIPTION
**Pull request by cdrage**
Updates the README.md with a more intuitive layout.

It also:

- Moves around a few things
- Uses the <section> feature of GitHub to make installation pages
dropdown
- Floats the logo to the right
- Changes the gif to asciinema

### CODE REVIEW

**Comment by cdrage** [comment]
It's best to view the changes from here: https://github.com/redhat-developer/odo/blob/5aa43435d8947cebae8e808bf1479390f659fa3f/README.md :100:

**Comment by cdrage** [comment]
@sspeiche thanks! 1 more ack? @kadel ?

**Comment by cdrage** [comment]
Tests are failing due to flakiness (this PR doesn't touch any code...)

**Comment by kadel** [comment]
Just one thing. Way back we agreed that we will format odo as odo (lower case) unless it is at the beginning of the sentence.

**Comment by sspeiche** [comment]
I was thinking that could be a different PR, since this is a just about
rearranging items.

I'd like to update some of the phrasing as well, I can take that as a
follow up, For example, instead of saying OpenShift Do...say what it
actually is "developer focused CLI for OpenShift".

**Comment by cdrage** [comment]
@sspeiche Okay. Issue opened here: https://github.com/redhat-developer/odo/issues/1397

**Pull request merged**
