### PR TITLE
Bump odo version to v3.3.0

### PR DESCRIPTION
**Pull request by valaparthvi**
**What type of PR is this:**

**What does this PR do / why we need it:**

**Which issue(s) this PR fixes:**

Fixes part of #6261 

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

### CODE REVIEW

**Comment by valaparthvi** [comment]
/hold
Until #6255 goes in.

**Comment by valaparthvi** [comment]
/hold cancel
#6255 is in.

**Comment by anandrkskd** [comment]
@valaparthvi this [file](https://github.com/redhat-developer/odo/blob/main/build/VERSION) should also be updated with the new version, right?

**Comment by valaparthvi** [comment]
> @valaparthvi this [file](https://github.com/redhat-developer/odo/blob/main/build/VERSION) should also be updated with the new version, right?

I believe that file should be updated after the binaries are released.

**Comment by anandrkskd** [comment]
> I believe that file should be updated after the binaries are released. At least, that's what the bump-version script says.

Understood! Thanks
/lgtm
/approve

**Comment by valaparthvi** [comment]
@feloy can you also add approve?

**Comment by feloy** [comment]
/override Kubernetes-Integration-Tests/Kubernetes-Integration-Tests

Flaky test
```
[FAILED] [287.834 seconds]
odo dev command tests
/go/odo_1/tests/integration/cmd_dev_test.go:31
  port-forwarding for the component
  /go/odo_1/tests/integration/cmd_dev_test.go:552
    when devfile has single endpoint
    /go/odo_1/tests/integration/cmd_dev_test.go:553
      when running odo dev
      /go/odo_1/tests/integration/cmd_dev_test.go:560
        when modifying memoryLimit for container in Devfile [BeforeEach]
        /go/odo_1/tests/integration/cmd_dev_test.go:590
          should expose the endpoint on localhost
          /go/odo_1/tests/integration/cmd_dev_test.go:606
```

**Comment by feloy** [comment]
/override ci/prow/v4.11-integration-e2e 
Tests pass on IBM Cloud

**Pull request merged**
