### PR TITLE
Upgrade to registry-library v1.0.1 to ignore OWNERS files

### PR DESCRIPTION
**Pull request by feloy**
**What type of PR is this:**

/kind bug

**What does this PR do / why we need it:**

**Which issue(s) this PR fixes:**

Fixes https://github.com/devfile/api/issues/840

Result of the commands:
```
go get github.com/devfile/registry-support/registry-library@21de53798172594993e41d27bba8d5d8cd0eee4d
go mod vendor
```

### CODE REVIEW

**Review by rm3l — APPROVED** [review]

**Comment by anandrkskd** [comment]
@feloy could the failure on prow be flake due to network??
Otherwise, /lgtm

**Comment by feloy** [comment]
> @feloy could the failure on prow be flake due to network?? Otherwise, /lgtm

Yes, that seems a network problem:

```
[odo]  ✗  unable to download devfile: unable to find the registry with name "go"
```

**Comment by feloy** [comment]
/override ci/prow/v4.10-integration-e2e
/override ci/prow/unit

Tests are passing on IBM Cloud

**Comment by feloy** [comment]
/approve

Got 2 LGTM

**Pull request merged**
