### PR TITLE
[ui] Set AutoBuild and DeployByDefault

### LINKED ISSUE #7021: [UI] AutoBuild / deployByDefault support
- [ ] Add a checkbox to created images and resources, to indicate if the component is "autonomous"
- [ ] e2e tests
- [ ] api endpoints to adapt
- [ ] check if changes are supported by odo

### PR DESCRIPTION
**Pull request by feloy**
**What type of PR is this:**

/kind feature

**What does this PR do / why we need it:**

**Which issue(s) this PR fixes:**

Fixes #7021

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

### CODE REVIEW

**Review by rm3l — COMMENTED** [review]
LGTM overall, but I was wondering about the case of components loaded from the Devfile, without `autoBuild`/`deployByDefault` set and not referenced.
Currently, `odo` automatically applies them at startup, but the UI shows them as not built/deployed at startup, which might sound confusing, I guess.

image

image

So shouldn't we at least show them in the UI as built/deployed at startup?

**Review by rm3l — CHANGES_REQUESTED** [review]
> LGTM overall, but I was wondering about the case of components loaded from the Devfile, without `autoBuild`/`deployByDefault` set and not referenced. Currently, `odo` automatically applies them at startup (per [devfile/api#852 (comment)](https://github.com/devfile/api/issues/852#issuecomment-1211928487)), but the UI shows them as not built/deployed at startup, which might sound confusing, I guess.
> 
> So shouldn't we at least show them in the UI as built/deployed at startup?

Looks good on the UI with the latest changes, but I just noticed one slight side effect.

The YAML view currently loads the Devfile with all boolean fields set to their default values if they were not set in the source Devfile, which causes an issue here.
For example, if the Devfile contains an orphan Image component without `autoBuild` set (so built on startup), the YAML view will have the field set to `false`. And when persisting it back to the filesystem, this Image component will no longer be applied automatically (because `autoBuild` is `false`).

In the source Devfile:
```
- image:
   imageName: my-image
   dockerfile:
     uri: Containerfile
  name: my-image-cmp
```

In the UI:
image

I think we should tell the Devfile parser not to automatically set default boolean values when they are unset. See https://github.com/devfile/library/pull/169
And I guess this would also fix some other boolean fields like `dedicatedPod`, `secure`, ... that get automatically added when saving the Devfile from the UI to the disk.

**Comment by feloy** [comment]
> > LGTM overall, but I was wondering about the case of components loaded from the Devfile, without `autoBuild`/`deployByDefault` set and not referenced. Currently, `odo` automatically applies them at startup (per [devfile/api#852 (comment)](https://github.com/devfile/api/issues/852#issuecomment-1211928487)), but the UI shows them as not built/deployed at startup, which might sound confusing, I guess.
> > So shouldn't we at least show them in the UI as built/deployed at startup?
> 
> Looks good on the UI with the latest changes, but I just noticed one slight side effect.
> 
> The YAML view currently loads the Devfile with all boolean fields set to their default values if they were not set in the source Devfile, which causes an issue here. For example, if the Devfile contains an orphan Image component without `autoBuild` set (so built on startup), the YAML view will have the field set to `false`. And when persisting it back to the filesystem, this Image component will no longer be applied automatically (because `autoBuild` is `false`).
> 

The definition of this `autoBuild` field is not clear to me. Is it a three-state value?

- true: always build at startup
- false: never build at startup (even if orphan)
- undefined: build if orphan only


Or two-states?

- true: always build at startup
- false: build if orphan only
- undefined: defaults to false (build if orphan only)

@rm3l @kadel @elsony wdyt?

**Comment by feloy** [comment]
> > 
> 
> > > > LGTM overall, but I was wondering about the case of components loaded from the Devfile, without `autoBuild`/`deployByDefault` set and not referenced. Currently, `odo` automatically applies them at startup (per [devfile/api#852 (comment)](https://github.com/devfile/api/issues/852#issuecomment-1211928487)), but the UI shows them as not built/deployed at startup, which might sound confusing, I guess.
> > > > So shouldn't we at least show them in the UI as built/deployed at startup?
> > > 
> > > 
> > > Looks good on the UI with the latest changes, but I just noticed one slight side effect.
> > > The YAML view currently loads the Devfile with all boolean fields set to their default values if they were not set in the source Devfile, which causes an issue here. For example, if the Devfile contains an orphan Image component without `autoBuild` set (so built on startup), the YAML view will have the field set to `false`. And when persisting it back to the filesystem, this Image component will no longer be applied automatically (because `autoBuild` is `false`).
> > 
> > 
> > The definition of this `autoBuild` field is not clear to me. Is it a three-state value?
> > 
> > * true: always build at startup
> > * false: never build at startup (even if orphan)
> > * undefined: build if orphan only
> 
> Yes, to me, it is a 3-state value and is currently implemented as above (per [devfile/api#852 (comment)](https://github.com/devfile/api/issues/852#issuecomment-1211928487)). So if it is explicitly set to `false`, it will never be applied at startup even if orphan.

OK, so I will introduce a 3-states button for the user to be able to select one of them

**Review by rm3l — APPROVED** [review]
Works great with the latest changes - thanks!

**Pull request merged**
