### PR TITLE
Use of re package for string operation in testsuite

### LINKED ISSUE #1129: Use regular expression for string operation in testsuite
[kind/Enhancement]

## Which functionality do you think we should update/improve?
string operation like sed, awk should be replaced with inbuilt go package ```re```.  

## Why is this needed? 

Just to make sure the testsuite should run on all the platforms.

### PR DESCRIPTION
**Pull request by amitkrout**
## Was the change discussed in an issue?
fixes #1129

## How to test changes?
CI should go green or run test locally one by one through ```make test-*```

### CODE REVIEW

**Comment by girishramnani** [comment]
```src/github.com/redhat-developer/odo/tests/e2e/watch_test.go
  78,88: 					url := runCmdShouldPass("odo url list | grep `odo component get -q` | grep 8080 | awk '{print $2}' | tr -d '\n'")
  83,70: 						podName := runCmdShouldPass("oc get pods | grep nodejs-watch | awk '{print $1}' | tr -d '\n'")
  141,88: 					url := runCmdShouldPass("odo url list | grep `odo component get -q` | grep 8080 | awk '{print $2}'")
  145,70: 						podName := runCmdShouldPass("oc get pods | grep python-watch | awk '{print $1}' | tr -d '\n'")
  222,88: 					url := runCmdShouldPass("odo url list | grep `odo component get -q` | grep 8080 | awk '{print $2}' | tr -d '\n'")
  227,71: 						podName := runCmdShouldPass("oc get pods | grep wildfly-watch | awk '{print $1}' | tr -d '\n'")
  298,88: 					url := runCmdShouldPass("odo url list | grep `odo component get -q` | grep 8080 | awk '{print $2}' | tr -d '\n'")
  302,71: 						podName := runCmdShouldPass("oc get pods | grep openjdk-watch | awk '{print $1}' | tr -d '\n'")
  368,88: 					url := runCmdShouldPass("odo url list | grep `odo component get -q` | grep 8080 | awk '{print $2}' | tr -d '\n'")
  443,88: 					url := runCmdShouldPass("odo url list | grep `odo component get -q` | grep 8080 | awk '{print $2}' | tr -d '\n'")```

10 places from where `awk` and other related commands need to be removed

**Comment by girishramnani** [comment]
grep instances found

```
/home/gramnani/GoProjects/src/github.com/redhat-developer/odo/tests/e2e/component.go
  90,44: 			waitForEqualCmd("curl -s "+routeURL+" | grep 'develop' | wc -l | tr -d '\n'", "1", 10)

/home/gramnani/GoProjects/src/github.com/redhat-developer/odo/tests/e2e/e2e_test.go
  96,69: 			configOutput := runCmdShouldPass("odo utils config view --global|grep Timeout")
  102,70: 			configOutput := runCmdShouldPass("odo utils config view --global |grep UpdateNotification")
  105,69: 			configOutput = runCmdShouldPass("odo utils config view --global |grep Timeout")
  110,60: 			configOutput := runCmdShouldPass("odo utils config view|grep ComponentType")
  119,59: 			configOutput = runCmdShouldPass("odo utils config view|grep ComponentType")
  127,69: 			configOutput = runCmdShouldPass("odo utils config view --global |grep Timeout")
  399,58: 				curlRoute := waitForEqualCmd("curl -s "+getRoute+" | grep 'Welcome to your Node.js application on OpenShift' | wc -l | tr -d '\n'", "1", 10)
  401,6: 					grepBeforePush := runCmdShouldPass("curl -s " + getRoute + " | grep 'Welcome to your Node.js application on OpenShift'")
  401,69: 					grepBeforePush := runCmdShouldPass("curl -s " + getRoute + " | grep 'Welcome to your Node.js application on OpenShift'")
  402,63: 					log.Printf("Text before odo push: %s", strings.TrimSpace(grepBeforePush))
  416,58: 				curlRoute := waitForEqualCmd("curl -s "+getRoute+" | grep -i odo | wc -l | tr -d '\n'", "1", 10)
  418,6: 					grepAfterPush := runCmdShouldPass("curl -s " + getRoute + " | grep -i odo")
  418,68: 					grepAfterPush := runCmdShouldPass("curl -s " + getRoute + " | grep -i odo")
  419,62: 					log.Printf("Text after odo push: %s", strings.TrimSpace(grepAfterPush))
  420,13: 					Expect(grepAfterPush).To(ContainSubstring("ODO"))

/home/gramnani/GoProjects/src/github.com/redhat-developer/odo/tests/e2e/java_test.go
  38,67: 			buildName := runCmdShouldPass("oc get builds --output='name' | grep javaee-git-test | cut -d '/' -f 2")
  54,57: 			pingValue := waitForEqualCmd("curl -s "+routeURL+" | grep 'Insult' | wc -l | tr -d '\n'", "1", 10)
  65,67: 			buildName := runCmdShouldPass("oc get builds --output='name' | grep wo-wait-javaee-git-test | cut -d '/' -f 2")
  68,53: 			buildStatus := runCmdShouldPass("oc get builds | grep wo-wait-javaee-git-test")
  71,44: 			dcName := runCmdShouldPass("oc get dc | grep wo-wait-javaee-git-test | cut -f 1 -d ' '")
  75,46: 				dcStatus := runCmdShouldPass("oc get dc |grep wo-wait-javaee-git-test | cut -f 4 -d ' '")
  94,57: 			pingValue := waitForEqualCmd("curl -s "+routeURL+" | grep 'Insult' | wc -l | tr -d '\n'", "1", 10)
  104,44: 			dcName := runCmdShouldPass("oc get dc | grep javaee-war-test| cut -f 1 -d ' '")
  119,57: 			pingValue := waitForEqualCmd("curl -s "+routeURL+" | grep 'Sample' | wc -l | tr -d '\n'", "2", 10)
  132,67: 			buildName := runCmdShouldPass("oc get builds --output='name' | grep uberjar-git-test | cut -d '/' -f 2")
  148,57: 			pingValue := waitForEqualCmd("curl -s "+routeURL+" | grep 'Hello World' | wc -l | tr -d '\n'", "1", 10)
  161,44: 			dcName := runCmdShouldPass("oc get dc | grep sb-jar-test| cut -f 1 -d ' '")
  175,57: 			pingValue := waitForEqualCmd("curl -s "+routeURL+" | grep 'HTTP Booster' | wc -l | tr -d '\n'", "1", 10)

/home/gramnani/GoProjects/src/github.com/redhat-developer/odo/tests/e2e/service_test.go
  75,45: 				waitForEqualCmd("curl -s "+routeURL+" | grep 'Spring Boot' | wc -l | tr -d '\n'", "3", 2)

/home/gramnani/GoProjects/src/github.com/redhat-developer/odo/tests/e2e/source_test.go
  39,44: 			waitForEqualCmd("curl -s "+routeURL+" | grep 'WSGI' | wc -l | tr -d '\n'", "1", 10)
  60,44: 			waitForEqualCmd("curl -s "+routeURL+" | grep 'Javalin' | wc -l | tr -d '\n'", "1", 10)
  79,44: 			waitForEqualCmd("curl -s "+routeURL+" | grep 'Insult' | wc -l | tr -d '\n'", "1", 10)
  98,44: 			waitForEqualCmd("curl -s "+routeURL+" | grep 'node.js' | wc -l | tr -d '\n'", "1", 10)
  117,44: 			waitForEqualCmd("curl -s "+routeURL+" | grep 'dotnet' | wc -l | tr -d '\n'", "1", 10)

/home/gramnani/GoProjects/src/github.com/redhat-developer/odo/tests/e2e/watch_test.go
  78,46: 					url := runCmdShouldPass("odo url list | grep `odo component get -q` | grep 8080 | awk '{print $2}' | tr -d '\n'")
  78,76: 					url := runCmdShouldPass("odo url list | grep `odo component get -q` | grep 8080 | awk '{print $2}' | tr -d '\n'")
  83,50: 						podName := runCmdShouldPass("oc get pods | grep nodejs-watch | awk '{print $1}' | tr -d '\n'")
  85,96: 						runCmdShouldPass("oc exec " + podName + " -c nodejs-watch-testing -- ls -lai /tmp/src/ | grep 'a b';exit")
  86,96: 						runCmdShouldFail("oc exec " + podName + " -c nodejs-watch-testing -- ls -lai /tmp/src/ | grep 'a b.txt';exit")
  141,46: 					url := runCmdShouldPass("odo url list | grep `odo component get -q` | grep 8080 | awk '{print $2}'")
  141,76: 					url := runCmdShouldPass("odo url list | grep `odo component get -q` | grep 8080 | awk '{print $2}'")
  145,50: 						podName := runCmdShouldPass("oc get pods | grep python-watch | awk '{print $1}' | tr -d '\n'")
  146,96: 						runCmdShouldPass("oc exec " + podName + " -c python-watch-testing -- ls -lai /tmp/src/ | grep 'a b';exit")
  151,96: 						runCmdShouldFail("oc exec " + podName + " -c python-watch-testing -- ls -lai /tmp/src/ | grep 'a b.txt';exit")
  222,46: 					url := runCmdShouldPass("odo url list | grep `odo component get -q` | grep 8080 | awk '{print $2}' | tr -d '\n'")
  222,76: 					url := runCmdShouldPass("odo url list | grep `odo component get -q` | grep 8080 | awk '{print $2}' | tr -d '\n'")
  227,50: 						podName := runCmdShouldPass("oc get pods | grep wildfly-watch | awk '{print $1}' | tr -d '\n'")
  229,117: 						runCmdShouldPass("oc exec " + podName + " -c wildfly-watch-testing -- ls -lai /opt/s2i/destination/src/src/ | grep 'a b';exit")
  232,117: 						runCmdShouldFail("oc exec " + podName + " -c wildfly-watch-testing -- ls -lai /opt/s2i/destination/src/src/ | grep 'a b.txt';exit")
  298,46: 					url := runCmdShouldPass("odo url list | grep `odo component get -q` | grep 8080 | awk '{print $2}' | tr -d '\n'")
  298,76: 					url := runCmdShouldPass("odo url list | grep `odo component get -q` | grep 8080 | awk '{print $2}' | tr -d '\n'")
  302,50: 						podName := runCmdShouldPass("oc get pods | grep openjdk-watch | awk '{print $1}' | tr -d '\n'")
  304,101: 						runCmdShouldPass("oc exec " + podName + " -c openjdk-watch-testing -- ls -lai /tmp/src/src/ | grep 'a b';exit")
  307,101: 						runCmdShouldFail("oc exec " + podName + " -c openjdk-watch-testing -- ls -lai /tmp/src/src/ | grep 'a b.txt';exit")
  369,46: 					url := runCmdShouldPass("odo url list | grep `odo component get -q` | grep 8080 | awk '{print $2}' | tr -d '\n'")
  369,76: 					url := runCmdShouldPass("odo url list | grep `odo component get -q` | grep 8080 | awk '{print $2}' | tr -d '\n'")
  444,46: 					url := runCmdShouldPass("odo url list | grep `odo component get -q` | grep 8080 | awk '{print $2}' | tr -d '\n'")
  444,76: 					url := runCmdShouldPass("odo url list | grep `odo component get -q` | grep 8080 | awk '{print $2}' | tr -d '\n'")

```

**Comment by amitkrout** [comment]
@girishramnani Thanks a lot for these reference. I am fixing these one by one.

**Comment by kadel** [comment]
@amitkrout wouldn't it be easier to split this into multiple PRs? You could work on converting each test separately

**Comment by amitkrout** [comment]
> @amitkrout wouldn't it be easier to split this into multiple PRs? You could work on converting each test separately

+100, Awesome idea!!!
Closing the pr and will start sending pr for each test file. It will really speed up the process. Thanks a lot.

**Comment by amitkrout** [comment]
@kadel  https://github.com/redhat-developer/odo/issues/1129#issuecomment-468219393

**Pull request closed without merging**
