### PR TITLE
Fix interactive tests on Windows

### LINKED ISSUE #5573: Setup interactive testing for windows
/area testing

## Which functionality do you think we should add?

Currently, we don't have a working interactive testing framework on Windows. We need to enable the interactive testing for windows to increase the coverage of our tests.

### PR DESCRIPTION
**Pull request by feloy**
**What type of PR is this:**

/kind bug

**What does this PR do / why we need it:**

This PR makes use of github.com/ActiveState/termtest for interactive tests, which is compatible with Linux / Windows / Mac, and is a fork of the previously used library.

We are skipping tests relative to welcoming messages on Windows because Windows virtual terminal cuts lines and makes the tests fail.

This PR is necessary for testing the manual trigger of sync #6089

**Which issue(s) this PR fixes:**

Fixes #5573

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

### CODE REVIEW

**Review by rm3l — COMMENTED** [review]
Can we enable the `windows-integration-test` pipeline in IBM Cloud to check this PR? I can see that the last execution of this pipeline is 13 days ago.
https://cloud.ibm.com/devops/pipelines/929da3ed-6cad-4026-a847-7a8485f20fa4/582614a3-b910-4659-ac27-6288668c5fe6/a1d74ffa-3d39-4dbb-8583-b0a34f87f3bd?env_id=ibm:yp:eu-de

**Comment by feloy** [comment]
Failed with 16 parallel tests (Insufficient memory), retesting with 12 parallel tests

**Comment by feloy** [comment]
> Can we enable the `windows-integration-test` pipeline in IBM Cloud to check this PR? I can see that the last execution of this pipeline is 13 days ago. https://cloud.ibm.com/devops/pipelines/929da3ed-6cad-4026-a847-7a8485f20fa4/582614a3-b910-4659-ac27-6288668c5fe6/a1d74ffa-3d39-4dbb-8583-b0a34f87f3bd?env_id=ibm:yp:eu-de

@rm3l I re-enabled the Windows tests

**Review by rm3l — APPROVED** [review]

**Comment by valaparthvi** [comment]
/approve
Windows test has passed.

**Comment by feloy** [comment]
/override ci/prow/unit-and-validate-test
Pass on IBM Cloud

/override Kubernetes-Integration-Tests/Kubernetes-Integration-Tests
/override OpenShift-Integration-tests/OpenShift-Integration-tests
/override Unit-Tests/Unit-Tests
Passed with old names

**Pull request merged**
