### PR TITLE
Allow `:` character in devfile registry URI

### LINKED ISSUE #6623: Adding a registry with a port in the URI fails
/kind bug

## What versions of software are you using?

**Operating System:**

**Output of `odo version`:**

## How did you run odo exactly?

```
odo preference add registry cluster http://192.168.1.100:30742
 ✗  URL is invalid
```

## Actual behavior

URI is not recognized.

## Expected behavior

URI should be recognized, as it is correct

## Any logs, error output, etc?

Limitation has been introduced by the PR #3900. `:` is now forbidden in the `host` field, which could be either `hostname` or `hostname:port`, so the error.

### PR DESCRIPTION
**Pull request by feloy**
**What type of PR is this:**

/kind bug

**What does this PR do / why we need it:**

**Which issue(s) this PR fixes:**

Fixes #6623

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

### CODE REVIEW

**Review by rm3l — APPROVED** [review]
Thanks.

**Comment by feloy** [comment]
/override OpenShift-Integration-tests/OpenShift-Integration-tests
Flaky test

```
odo dev command tests
/go/odo_1/tests/integration/cmd_dev_test.go:33
  port-forwarding for the component
  /go/odo_1/tests/integration/cmd_dev_test.go:658
    when devfile has single endpoint
    /go/odo_1/tests/integration/cmd_dev_test.go:695
      when running odo dev
      /go/odo_1/tests/integration/cmd_dev_test.go:704
        when modifying memoryLimit for container in Devfile [BeforeEach]
        /go/odo_1/tests/integration/cmd_dev_test.go:739
          should react on the Devfile modification
          /go/odo_1/tests/integration/cmd_dev_test.go:759
```

**Pull request merged**
