### PR TITLE
Set replicas using devfile library

### LINKED ISSUE #5347: devfile/library add replicas to  `generator.DeploymentParams` structure
It would be nice to have this field set when the Deployment is first created, by the devfile library. Could we propose a path to the library to add the Replicas to the `generator.DeploymentParams` structure?

_Originally posted by @feloy in https://github.com/redhat-developer/odo/pull/5315#r778793735_

### PR DESCRIPTION
**Pull request by dharmit**
**What type of PR is this:**
/kind cleanup

**What does this PR do / why we need it:**
Sets replicas using devfile library. We need it as we have pushed the necessary change in devfile library, and now odo just needs to use it.

**Which issue(s) this PR fixes:**

Fixes #5347

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**
Tests should pass.

### CODE REVIEW

**Comment by dharmit** [comment]
4.9 integration tests are full of below error:
```
[odo]  ✗  1 error occurred:
[odo] 	* devfile contains multiple endpoint entries with same TargetPort: 3000 
```
I think #5407 is addressing this. @valaparthvi WDYT? I see your PR failing with bunch of:
```
[odo]  ✗  URL creation failed:
[odo] 	- port 8080 already exists in devfile endpoint entry under container "py-web" 
```

**Comment by valaparthvi** [comment]
You are facing these problems because devfile libraries recently added duplicate port validation checks. 5407 is accommodating this validation for odo. I need to fix the tests tho.

**Comment by dharmit** [comment]
> You are facing these problems because devfile libraries recently added duplicate port validation checks. 5407 is accommodating this validation for odo. I need to fix the tests tho.

Yeah, I know the devfile PR that caused this and the reason why they made that change. The reason I pinged you was to understand if your PR is going to address the tests. That is why I said in my original message that -

> I think #5407 is addressing this. @valaparthvi WDYT?

**Comment by valaparthvi** [comment]
Yes. My PR will address these failures.

**Comment by feloy** [comment]
Now that https://github.com/redhat-developer/odo/pull/5407 is merged, tests should pass if you rebase your PR

**Comment by dharmit** [comment]
> Now that #5407 is merged, tests should pass if you rebase your PR

Thanks, I had missed the need of rebase. Done that now.

**Comment by dharmit** [comment]
Force-push was to fix conflicts.

**Pull request merged**
