### PR TITLE
Add more tests for odo dev on Podman (2)

### PR DESCRIPTION
**Pull request by rm3l**
- prepare test dev.odo.push.path - not implemented yet on Podman
- Skip 'should create vcs-uri annotation for the deployment when running odo dev' on Podman
- [Test cpu/memory limit/resources on podman/cluster](https://github.com/redhat-developer/odo/pull/6482/commits/1ffb48ed3e941bd7f540dccb43b4ac4252009c84)
- [WIP add GetPodDef implementation for cluster](https://github.com/redhat-developer/odo/pull/6482/commits/dcb788fd14305bf5d274d27d666b98890dcc1602)
- [Convert springboot compare lo](https://github.com/redhat-developer/odo/pull/6482/commits/40a4f04a8f2404f0ed286b1af7b5280efdf7e386)[cal and remote files test for podman](https://github.com/redhat-developer/odo/pull/6482/commits/40a4f04a8f2404f0ed286b1af7b5280efdf7e386)
- [Fix namespace instead of component name](https://github.com/redhat-developer/odo/pull/6482/commits/e5821e83524bb25a4d0f474d34e84710d6e536a7)
- Change image and make adjustments for this image

**What type of PR is this:**

**What does this PR do / why we need it:**

**Which issue(s) this PR fixes:**

Fixes #

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

### CODE REVIEW

**Comment by rm3l** [comment]
For the 2nd test not passing on Podman (`[FAIL] odo dev command tests port-forwarding for the component when devfile has single endpoint when running odo dev when modifying memoryLimit for container in Devfile [It] should react on the Devfile modification [podman]`), I think we can cherry-pick [`e8f0815` (#6504)](https://github.com/redhat-developer/odo/pull/6504/commits/e8f08154240deb59da695f79016ff13b0bba60de) or wait until #6504 is merged in.

**Comment by feloy** [comment]
> For the 2nd test not passing on Podman (`[FAIL] odo dev command tests port-forwarding for the component when devfile has single endpoint when running odo dev when modifying memoryLimit for container in Devfile [It] should react on the Devfile modification [podman]`), I think we can cherry-pick [`e8f0815` (#6504)](https://github.com/redhat-developer/odo/pull/6504/commits/e8f08154240deb59da695f79016ff13b0bba60de) or wait until #6504 is merged in.

Right, I'll test by cherry-picking the commit. Thanks

**Comment by feloy** [comment]
Rebased to resolve conflicts

**Pull request merged**
