### PR TITLE
[DO NOT MERGE] Test PR for OpenShift CI

### PR DESCRIPTION
**Pull request by mohammedzee1000**
Signed-off-by: Mohammed Zeeshan Ahmed <mohammed.zee1000@gmail.com>

## What is the purpose of this change? What does it change?

/hold
DO NOT MERGE this PR is meant to check if OpenShift e2e tests were enabled correctly

### CODE REVIEW

**Comment by amitkrout** [comment]
@mohammedzee1000 How to confirm e2e test runs on prow ? I did not find the test log or am i missing the test log location ?

**Comment by mohammedzee1000** [comment]
@amitkrout you should be able to see it now

**Comment by amitkrout** [comment]
Purpose resolved

**Pull request closed without merging**
