### PR TITLE
update go version to use go 1.17

### LINKED ISSUE #5463: Use go 1.17.x to build odo
The build system used by odo to build and publish binaries on [Red Hat Developer content gateway](https://developers.redhat.com/content-gateway/rest/mirror/pub/openshift-v4/clients/odo/) has been upgraded to use go 1.17.5. We should build odo using that at the time of making v3alpha1 release.

## remaining
- [ ] #5707
- [x] update IBM cloud build pipeline to use go 1.17
- [x] test in build in Brew using **scratch** build

/kind feature
/area release-eng

### PR DESCRIPTION
**Pull request by anandrkskd**
Signed-off-by: anandrkskd <anandrkskd@gmail.com>

**What type of PR is this:**

/kind feature

**What does this PR do / why we need it:**
This PR updates odo to use go 1.17.x for building binary, tests(OpenShift-ci)

**Which issue(s) this PR fixes:**

partially  #5463

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

Steps used to update the go verison
- update go version in mentioned files
  - Dockerfile.rhel
  - go.mod
  - openshift-ci/build-root/Dockerfile
  - scripts/rpm-prepare.sh
- Running following commands
```
go mod vendor
go mod tidy
```

### CODE REVIEW

**Comment by mohammedzee1000** [comment]
Changes are looking good. It is really strange that tests are failing tho. Once we have figured that out we should be good

**Comment by mohammedzee1000** [comment]
Rebase please?

**Comment by dharmit** [comment]
@anandrkskd Is this still a WIP?

**Comment by anandrkskd** [comment]
`make validate` is failing on my local, so I am trying to figure out if I am missing something or not.
Currently, I will say it should be in WIP

**Comment by anandrkskd** [comment]
failed with flake, /test v4.9-integration-e2e

**Comment by feloy** [comment]
@anandrkskd I can see this error on `make test-integration-interactive` with go 1.17:

```

**Comment by anandrkskd** [comment]
> I can see this error on make test-integration-interactive with go 1.17

Fixed, Thanks @feloy for pointing that out.

**Comment by valaparthvi** [comment]
Can we use go 1.18 instead since it's already out?

**Comment by dharmit** [comment]
> Can we use go 1.18 instead since it's already out?

Not unless the build systems are updated to provide it. The comments on original issue might help get some info on how this works.

**Comment by anandrkskd** [comment]
/retest
`4.10` test failed due to infra.

**Review by feloy — APPROVED** [review]

**Comment by feloy** [comment]
/test ci/prow/unit
infra error

**Pull request merged**
