### PR TITLE
Devfile telemetry

### PR DESCRIPTION
**Pull request by kim-tsao**
**What type of PR is this?**
> Uncomment only one ` /kind` line, and delete the rest.
> For example, `> /kind bug` would simply become: `/kind bug`

 /kind feature

> Feel free to use other [labels](https://github.com/openshift/odo/labels) as needed. However one of the above labels must be present or the PR will not be reviewed. This instruction is for reviewers as well.

**What does this PR do / why we need it**:
Sends additional telemetry data to the devfile registry in order to improve our metrics.   Data such as the anonymousId and locale will only be collected if the user has given consent to Odo, otherwise we will only collect events under the generic client name 'odo'

**Which issue(s) this PR fixes**:

Fixes #?
https://github.com/devfile/api/issues/688

**PR acceptance criteria**:

- [x] Unit test 

- [ ] Integration test 

- [ ] Documentation 

- [x] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:

Run `make bin` to get the new odo binary and issue the `odo create` and `odo catalog list components` commands to drive devfile `list` and `download` events to segment and woopra.  This requires a local build and install of the `devfile/registry-support` repo to verify property updates.

### CODE REVIEW

**Review by valaparthvi — APPROVED** [review]

**Comment by feloy** [comment]
Kubernetes Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5260-kubernetes-tests-78.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5260-kubernetes-tests-78.html)

**Comment by feloy** [comment]
Unit Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5260-unit-tests-92.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5260-unit-tests-92.html)

**Comment by feloy** [comment]
OpenShift Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5260-openshift-tests-108.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5260-openshift-tests-108.html)

**Comment by feloy** [comment]
Kubernetes Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5260-kubernetes-tests-79.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5260-kubernetes-tests-79.html)

**Comment by feloy** [comment]
OpenShift Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5260-openshift-tests-109.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5260-openshift-tests-109.html)

**Comment by feloy** [comment]
Unit Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5260-unit-tests-94.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5260-unit-tests-94.html)

**Comment by feloy** [comment]
Kubernetes Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5260-kubernetes-tests-80.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5260-kubernetes-tests-80.html)

**Comment by feloy** [comment]
OpenShift Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5260-openshift-tests-110.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5260-openshift-tests-110.html)

**Comment by feloy** [comment]
Unit Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5260-unit-tests-95.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5260-unit-tests-95.html)

**Comment by feloy** [comment]
Kubernetes Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5260-kubernetes-tests-81.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5260-kubernetes-tests-81.html)

**Comment by feloy** [comment]
OpenShift Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5260-openshift-tests-111.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5260-openshift-tests-111.html)

**Pull request merged**
