### PR TITLE
Bump version 3.11.0

### PR DESCRIPTION
**Pull request by feloy**

### CODE REVIEW

**Review by valaparthvi — APPROVED** [review]
I wonder if we do some kind of auto merge for such PRs. But this lgtm.

**Comment by feloy** [comment]
/override OpenShift-Integration-tests/OpenShift-Unauth-Integration-tests

```
[FAILED] [129.452 seconds]
odo init interactive command tests label unauth personalizing Devfile configuration [It] should allow for personalizing configurations [unauth]
/go/odo_1/tests/integration/interactive_init_test.go:95

```

Flaky, passed first time

**Comment by feloy** [comment]
```
 [FAILED] [170.901 seconds]
odo remove binding command tests when the component with binding is bootstrapped (bindingName=my-nodejs-app-cluster-sample-k8s) when odo dev is running when binding is removed [It] should have led odo dev to delete ServiceBinding from the cluster
```

Flaky, passed first time

**Comment by feloy** [comment]
/override OpenShift-Integration-tests/OpenShift-Integration-tests

**Pull request merged**
