### PR TITLE
Terminate process on windows

### LINKED ISSUE #5485: odo dev part 2 (cleanup)
## Acceptance Criteria
- [x] Before the command ends it should delete all **inner loop** resources that it created on the cluster.
   - [x] There are different ways how the command can end (for example SIGQUIT, SIGHUP, SIGINT etc...) Program should catch all those signals and do cleanup before exiting.
   - [x] if the command is interrupted in the middle of some other operation (for example file syncing, k8s resource creation etc...) it should complete what is is doing, and when it gets to the point when `odo dev` is waiting or files to change start the cleanup procedure
- [x] The last line of the output needs to always inform user that ctrl+c will end the command and that it will result in deleting all resources from the cluster
- [ ] at least one test with devfile that creates storage, k8s. networking/Service (endpoint), k8s component.  (moved to separate issue https://github.com/redhat-developer/odo/issues/5621)
- [ ] verify that this work on Windows (moved to separate issue https://github.com/redhat-developer/odo/issues/5621)
- [x] for now this won't wait for resources to get deleted, it can reuse current `odo delete component` logic. It should show warning that it might take some time for resources to get deleted

## blocked on
- https://github.com/redhat-developer/odo/issues/5484

### PR DESCRIPTION
**Pull request by feloy**
**What type of PR is this:**

/kind bug

**What does this PR do / why we need it:**

This PR fixes how the odo process is terminated on Windows during integration tests

**Which issue(s) this PR fixes:**

Fixes #5485 

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

### CODE REVIEW

**Review by rm3l — APPROVED** [review]

**Comment by rm3l** [comment]
Tested it locally and it works great on Windows 👍🏿

**Comment by rm3l** [comment]
Not clear why the "Validate" job on IBM Cloud did not pass.
I guess we will have to run it again?

**Comment by feloy** [comment]
/override validator/Validate
Validate pass on Prow

**Comment by feloy** [comment]
> Not clear why the "Validate" job on IBM Cloud did not pass. I guess we will have to run it again?

Oups! it seems an infra problem. As the validation passes locally and on Prow, I have overriden it

**Pull request merged**
