### PR TITLE
Do not call LogErrorAndExit but return err in GenericRun

### PR DESCRIPTION
**Pull request by feloy**
**What type of PR is this:**

/kind code-refactoring

**What does this PR do / why we need it:**

**Which issue(s) this PR fixes:**

Fixes #

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

### CODE REVIEW

**Review by rm3l — COMMENTED** [review]
I think there might be some other places to change.
Didn't check if that was also happening on main, but if I run `odo` with an unknown flag (say `odo --xyz`), Usage is displayed twice.

<details>
<summary>odo --xyz</summary>

```
$ odo --xyz

flag provided but not defined: -xyz
  __
 /  \__     odo is a CLI tool for fast iterative application development
 \__/  \    deployed immediately to your kubernetes cluster.
 /  \__/    Find more information at https://odo.dev
 \__/

Usage:
  odo [flags]
  odo [command]

Examples:
  Initializing your component by taking your pick from multiple languages or frameworks:
  odo init
  
  After creating your initial component, start development with:
  odo dev
  
  Want to deploy after development? See it live with:
  odo deploy

Main Commands:
  build-images Build images
  deploy       Deploy components
  dev          Deploy component to development cluster
  init         Init bootstraps a new project
  logs         Show logs of all containers of the component
  registry     List all components from the Devfile registry

Management Commands:
  add          Add resources to devfile (binding)
  create       Perform create operation (namespace)
  delete       Delete resources (component, namespace)
  describe     Describe resource (binding, component)
  list         List all components in the current namespace (binding, component, namespace, services)
  remove       Remove resources from devfile (binding)
  set          Perform set operation (namespace)

OpenShift Commands:
  login        Login to cluster 
  logout       Logout of the cluster 

Utility Commands:
  analyze      Detect devfile to use based on files present in current directory
  completion   Add odo completion support to your development environment
  preference   Modifies preference settings (add, remove, set, unset, view)
  version      Print the client version information

Flags:
      --complete             Install completion for odo command
      --kubeconfig string    Paths to a kubeconfig. Only required if out-of-cluster.
  -o, --o string             Specify output format, supported format: json
      --uncomplete           Uninstall completion for odo command
  -v, --v Level              Number for the log level verbosity. Level varies from 0 to 9 (default 0).
      --var stringArray      Variable to override Devfile variable and variables in var-file
      --var-file string      File containing variables to override Devfile variables
      --vmodule moduleSpec   Comma-separated list of pattern=N settings for file-filtered logging
  -y, --y                    Don't prompt user for typing 'yes' when installing completion

Use "odo [command] --help" for more information about a command.
Error: unknown flag: --xyz
Usage:
  odo [flags]
  odo [command]

Examples:
  Initializing your component by taking your pick from multiple languages or frameworks:
  odo init
  
  After creating your initial component, start development with:
  odo dev
  
  Want to deploy after development? See it live with:
  odo deploy

Main Commands:
  build-images Build images
  deploy       Deploy components
  dev          Deploy component to development cluster
  init         Init bootstraps a new project
  logs         Show logs of all containers of the component
  registry     List all components from the Devfile registry

Management Commands:
  add          Add resources to devfile (binding)
  create       Perform create operation (namespace)
  delete       Delete resources (component, namespace)
  describe     Describe resource (binding, component)
  list         List all components in the current namespace (binding, component, namespace, services)
  remove       Remove resources from devfile (binding)
  set          Perform set operation (namespace)

OpenShift Commands:
  login        Login to cluster 
  logout       Logout of the cluster 

Utility Commands:
  analyze      Detect devfile to use based on files present in current directory
  completion   Add odo completion support to your development environment
  preference   Modifies preference settings (add, remove, set, unset, view)
  version      Print the client version information

Flags:
      --complete             Install completion for odo command
  -h, --help                 Help for odo
      --kubeconfig string    Paths to a kubeconfig. Only required if out-of-cluster.
  -o, --o string             Specify output format, supported format: json
      --uncomplete           Uninstall completion for odo command
  -v, --v Level              Number for the log level verbosity. Level varies from 0 to 9 (default 0).
      --var stringArray      Variable to override Devfile variable and variables in var-file
      --var-file string      File containing variables to override Devfile variables
      --vmodule moduleSpec   Comma-separated list of pattern=N settings for file-filtered logging
  -y, --y                    Don't prompt user for typing 'yes' when installing completion

Use "odo [command] --help" for more information about a command.

 ✗  unknown flag: --xyz
```

</details>

**Comment by rm3l** [comment]
> I think there might be some other places to change. Didn't check if that was also happening on main, but if I run `odo` with an unknown flag (say `odo --xyz`), Usage is displayed twice.
> 
> odo --xyz

I just tested and noticed the same behavior on `main`, so this might be a different issue, not directly related to the changes here.

**Review by rm3l — CHANGES_REQUESTED** [review]
One slight thing I noticed on the behavior: when checking if `ODO_DISABLE_TELEMETRY` and `ODO_TRACKING_CONSENT` conflict, it looks like Usage is also being displayed:

```
$ ODO_DISABLE_TELEMETRY=true ODO_TRACKING_CONSENT=yes odo version
Error: ODO_DISABLE_TELEMETRY and ODO_TRACKING_CONSENT values are in conflict. ODO_DISABLE_TELEMETRY is deprecated, please use only ODO_TRACKING_CONSENT
Usage:
  odo version [flags]

Examples:
  # Print the client version of odo
  odo version

Flags:
      --client   Client version only (no server required).
  -h, --help     Help for version

Additional Flags:
      --kubeconfig string    Paths to a kubeconfig. Only required if out-of-cluster.
  -o, --o string             Specify output format, supported format: json
  -v, --v Level              Number for the log level verbosity. Level varies from 0 to 9 (default 0).
      --var stringArray      Variable to override Devfile variable and variables in var-file
      --var-file string      File containing variables to override Devfile variables
      --vmodule moduleSpec   Comma-separated list of pattern=N settings for file-filtered logging

 ✗  ODO_DISABLE_TELEMETRY and ODO_TRACKING_CONSENT values are in conflict. ODO_DISABLE_TELEMETRY is deprecated, please use only ODO_TRACKING_CONSENT
```

And on `main`, I only get this, which makes more sense to me:
```
$ ODO_DISABLE_TELEMETRY=true ODO_TRACKING_CONSENT=yes odo version
 ✗  ODO_DISABLE_TELEMETRY and ODO_TRACKING_CONSENT values are in conflict. ODO_DISABLE_TELEMETRY is deprecated, please use only ODO_TRACKING_CONSENT
```

**Review by rm3l — APPROVED** [review]
/approve

**Comment by feloy** [comment]
/override ci/prow/v4.11-integration-e2e
Flaky e2e tests failing

**Pull request merged**
