### PR TITLE
fix PATH for odo binary

### LINKED ISSUE #5683: Windows tests not running the right odo binary
/kind bug
/area testing

First encountered this issue in #5675. The entire job logs are attached below.
[windows-integration-test-log.txt](https://github.com/redhat-developer/odo/files/8532004/windows-integration-test-log.txt)

## Context

Weirder than before. It can't find `--no-watch` flag! 😕 
```
[14] [odo] Your new component 'qaymxq' is ready in the current directory.
[14] [odo] To start editing your component, use 'odo dev' and open this folder in your favorite IDE.
[14] [odo] Changes will be directly reflected on the cluster.
[14] Running odo.exe with args [odo dev --random-ports --no-watch]
[14] [odo] Error: unknown flag: --no-watch
[14] [odo] Usage:
[14] [odo]   odo dev [flags]
[14] [odo] 
[14] [odo] Examples:
[14] [odo]   # Deploy component to the development cluster
[14] [odo]   odo dev
[14] [odo] 
[14] [odo] Flags:
[14] [odo]   -h, --help           Help for dev
[14] [odo]   -f, --random-ports   Assign random ports to redirected ports
[14] [odo] 
[14] [odo] Additional Flags:
[14] [odo]       --kubeconfig string    Paths to a kubeconfig. Only required if out-of-cluster.
[14] [odo]   -v, --v Level              Number for the log level verbosity. Level varies from 0 to 9 (default 0).
[14] [odo]       --vmodule moduleSpec   Comma-separated list of pattern=N settings for file-filtered logging
[14] [odo] 
[14] [odo]  X  unknown flag: --no-watch
```

_Originally posted by @dharmit in https://github.com/redhat-developer/odo/issues/5675#issuecomment-1104965332_

---

Indeed, this is strange. As you said, it looks like a different binary was used. I can see the version is `v2.5.0` in the CI job logs, while it should now be `v3.0.0-alpha1` (since 946385b and #5677, and given that you rebased your branch onto `main`):

```
[14] [odo] I0421 03:47:24.159538   10020 implem.go:103] The path for preference file is C:\Users\Administrator.ANSIBLE-TEST-VS\AppData\Local\Temp\238738076\preference.yaml
[14] [odo]   __
[14] [odo]  /  \__     Initializing new component
[14] [odo]  \__/  \    
[14] [odo]  /  \__/    odo version: v2.5.0
[14] [odo]  \__/
[14] [odo] 
[14] [odo] Interactive mode enabled, please answer the following questions:
[14] [odo]  -  Copying devfile from "C:\\Users\\Administrator.ANSIBLE-TEST-VS\\651\\tests\\examples\\source\\devfiles\\nodejs\\devfile.yaml"  ...
[14] [odo]
```

_Originally posted by @rm3l in https://github.com/redhat-developer/odo/issues/5675#issuecomment-1105273480_

### PR DESCRIPTION
**Pull request by anandrkskd**
Signed-off-by: anandrkskd <anandrkskd@gmail.com>

**What type of PR is this:**
/kind tests

**What does this PR do / why we need it:**
This PR will make sure to use correct odo binary for tests even if there are other binary in the PATH
**Which issue(s) this PR fixes:**

Fixes #5683

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

### CODE REVIEW

**Comment by rm3l** [comment]
@anandrkskd LGTM, but out of curiosity, do you know now what could have caused it to have other binaries in the PATH?

**Review by rm3l — APPROVED** [review]

**Comment by anandrkskd** [comment]
> @anandrkskd Thanks for this fix. LGTM, but out of curiosity, do you know what could have caused it to have other binaries in the PATH?

I was using the Windows machine to do some testing before enabling the CI, for which I had to put odo binary in the path and I forgot to remove the odo binary after my testing.
With this, I think we won't face this issue again.

**Comment by rm3l** [comment]
> > @anandrkskd Thanks for this fix. LGTM, but out of curiosity, do you know what could have caused it to have other binaries in the PATH?
> 
> I was using the Windows machine to do some testing before enabling the CI, for which I had to put odo binary in the path and I forgot to remove the odo binary after my testing. With this, I think we won't face this issue again.

Thanks.

**Pull request merged**
