### PR TITLE
Improve --help page by separating commands to management commands

### PR DESCRIPTION
**Pull request by cdrage**
<!--
Thank you for opening a PR! Here are some things you need to know before submitting:

1. Please read our developer guideline: https://github.com/redhat-developer/odo/wiki/Dev:-odo-Dev-Guidelines
2. Label this PR accordingly with the '/kind' line
3. Ensure you have written and ran the appropriate tests: https://github.com/redhat-developer/odo/wiki/Dev:-Writing-and-running-tests
4. Read how we approve and LGTM each PR: https://github.com/redhat-developer/odo/wiki/Pull-Requests:-Review-guideline

Documentation:

If you are pushing a change to documentation, please read: https://github.com/redhat-developer/odo/wiki/Documentation:-Contributing
-->

**What type of PR is this:**

<!--
Add one of the following kinds:
/kind bug
/kind feature
/kind tests
/kind documentation

Feel free to use other [labels](https://github.com/redhat-developer/odo/labels) as needed. However one of the above labels must be present or the PR will not be reviewed. This instruction is for reviewers as well.
-->
/kind cleanup

**What does this PR do / why we need it:**

One thing I noticed is that all of our commands are clustered into one
section.

We mix both nouns and verbs together.

I've gone ahead and separated it into a different section so it's easier
to decipher what can be done, I've named the section "management
commands".

```sh
go/src/odo  improve-help-page-usage ✔                                                                                                                                                                                                                                                                                                                             2h18m
 /  \__     odo is a CLI tool for fast iterative application development
 \__/  \    deployed immediately to your kubernetes cluster.
 /  \__/    Find more information at https://odo.dev
 \__/

Usage:
  odo [flags]
  odo [command]

Examples:
  Initializing your component by taking your pick from multiple languages or frameworks:
  odo init

  After creating your initial component, start development with:
  odo dev

  Want to deploy after development? See it live with:
  odo deploy

Main Commands:
  build-images Build images
  deploy       Deploy components
  dev          Deploy component to development cluster
  init         Init bootstraps a new project
  logs         Show logs of all containers of the component
  registry     List all components from the Devfile registry

Management Commands:
  add          Add resources to devfile (binding)
  create       Perform create operation (namespace)
  delete       Delete resources (component, namespace)
  describe     Describe resource (binding, component)
  list         List all components in the current namespace (binding, namespace)
  remove       Remove resources from devfile (binding)
  set          Perform set operation (namespace)

OpenShift Commands:
  login        Login to cluster
  logout       Logout of the cluster

Utility Commands:
  analyze      Detect devfile to use based on files present in current directory
  completion   Add odo completion support to your development environment
  preference   Modifies preference settings (add, remove, set, unset, view)
  version      Print the client version information
```

**Which issue(s) this PR fixes:**
<!--
Specifying the issue will automatically close it when this PR is merged
-->

N/A

**How to test changes / Special notes to the reviewer:**

Signed-off-by: Charlie Drage <charlie@charliedrage.com>

### CODE REVIEW

**Comment by cdrage** [comment]
Thoughts? @kadel @dharmit @valaparthvi @rm3l

**Comment by dharmit** [comment]
> Thoughts? @kadel @dharmit @valaparthvi @rm3l

I don't have any strong views on this.

**Review by rm3l — APPROVED** [review]
> Thoughts?

No strong opinion either, but this makes the different commands more understandable to me in the help output.

**Comment by valaparthvi** [comment]
/approve


> Thoughts? @kadel @dharmit @valaparthvi @rm3l

I like it.

**Pull request merged**
