### PR TITLE
update devfiles on v2 branch

### PR DESCRIPTION
**Pull request by anandrkskd**
Signed-off-by: anandrkskd <anandrkskd@gmail.com>

**What type of PR is this:**

Add one of the following kinds:

/kind tests

**What does this PR do / why we need it:**
This PR updates the devfile.yaml present in the example dir for tests.

**Which issue(s) this PR fixes:**

Fixes #

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

### CODE REVIEW

**Comment by dharmit** [comment]
@anandrkskd maybe a naive question, but is this solving some problem/bug we are seeing in the CI or elsewhere? Trying to understand why the change is proposed.

**Comment by anandrkskd** [comment]
We use devfile registry devfile for tests, but if there are changes introduced to the devfiles in devfile-registry then odo might break, We are updating/syncing the context of devfiles with the changes that were done on the devfile registry. I hope this help answer your questing.

**Comment by dharmit** [comment]
> We use devfile registry devfile for tests, but if there are changes introduced to the devfiles in devfile-registry then odo might break, We are updating/syncing the context of devfiles with the changes that were done on the devfile registry. I hope this help answer your questing.

So, IIUC, we are aligning our devfiles to look the same as those on devfile registry, right?

**Comment by anandrkskd** [comment]
Yes

**Comment by feloy** [comment]
This test is failing:
```

**Comment by feloy** [comment]
@anandrkskd  This test is failing:
```
Fail] Test suits to check .devfile.yaml compatibility when Creating a nodejs component and replace devfile.yaml with .devfile.yaml when creating a service when odo push is executed [It] should find files in component container 
```

You will need to update the test to replae `/project` with `/projects`:
```
--- a/tests/integration/devfile/cmd_dot_devfile_test.go
+++ b/tests/integration/devfile/cmd_dot_devfile_test.go
@@ -136,7 +136,7 @@ var _ = Describe("Test suits to check .devfile.yaml compatibility", func() {
                                })
 
                                It("should find files in component container", func() {
-                                       helper.Cmd("odo", "exec", "--context", commonVar.Context, "--", "ls", "/project/server.js").ShouldPass()
+                                       helper.Cmd("odo", "exec", "--context", commonVar.Context, "--", "ls", "/projects/server.js").ShouldPass()
                                })
```

**Review by feloy — APPROVED** [review]

**Pull request merged**
