### PR TITLE
Fix: Non odo components not reported

### LINKED ISSUE #6007: Non odo components not reported
/kind bug

## What versions of software are you using?

**Operating System:**
Win10Pro

**Output of `odo version`:**

```
odo v3.0.0-beta2 (c8e4458f4)

Server: https://api.sandbox-m2.ll9k.p1.openshiftapps.com:6443
Kubernetes: v1.23.5+9ce5071
```

## How did you run odo exactly?

Deploy a Quarkus app using ODC

`odo list`

## Actual behavior

Only odo components are reported

## Expected behavior

Non odo components should be reported

### PR DESCRIPTION
**Pull request by valaparthvi**
Signed-off-by: Parthvi Vala <pvala@redhat.com>

**What type of PR is this:**
/kind bug

**What does this PR do / why we need it:**
This PR fixes the bug where components not managed by odo were not detected by odo.
**Which issue(s) this PR fixes:**

Fixes #6007 

**PR acceptance criteria:**

- [ ] Unit test 

- [x] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**
1. Create a component from OpenShift Web Console.
2. Run `odo list`
3. See if the component is detected.

### CODE REVIEW

**Review by rm3l — COMMENTED** [review]
/approve

**Comment by valaparthvi** [comment]
@feloy IBM K8s tests have passed, thanks for the reopening.

**Comment by feloy** [comment]
Thanks for these changes 

/lgtm

/override ci/prow/v4.10-integration-e2e
Infra error; tests pass on IBM Cloud

**Pull request merged**
