### PR TITLE
Updated vendor with service catalog and client-go

### PR DESCRIPTION
**Pull request by surajnarwade**
Updated vendor with:

service-catalog: v0.1.31
openshift/client-go: 431ec9a26e5021f35fa41ee9a89842db9bfdb370

### CODE REVIEW

**Comment by surajnarwade** [comment]
I was playing with vendor and this seems to work I guess
cc @mik-dass @dgolovin

**Comment by surajnarwade** [comment]
@dgolovin , @mik-dass , Please test `git clone` on windows after merging this

**Comment by surajnarwade** [comment]
Only merge after testing it on windows

**Comment by mik-dass** [comment]
@cdrage please review and merge

**Comment by cdrage** [comment]
This LGTM.

**Pull request merged**
