### PR TITLE
Minor fixes to documentation

### PR DESCRIPTION
**Pull request by valaparthvi**
**What type of PR is this:**
/kind documentation

**What does this PR do / why we need it:**
This PR makes some things that we missed out on that I observed while reviewing downstream.
**Which issue(s) this PR fixes:**

Fixes #

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [x] Documentation 

**How to test changes / Special notes to the reviewer:**

### CODE REVIEW

**Review by rm3l — COMMENTED** [review]
/approve

**Comment by valaparthvi** [comment]
/override Kubernetes-Integration-Tests/Kubernetes-Integration-Tests
/override OpenShift-Integration-tests/OpenShift-Integration-tests 
/override windows-integration-test/Windows-test

**Review by rm3l — APPROVED** [review]

**Review by rm3l — APPROVED** [review]

**Comment by valaparthvi** [comment]
/override Kubernetes-Integration-Tests/Kubernetes-Integration-Tests
/override OpenShift-Integration-tests/OpenShift-Integration-tests
/override windows-integration-test/Windows-test

**Pull request merged**
