### PR TITLE
Do not output log to stdout

### PR DESCRIPTION
**Pull request by feloy**
**What type of PR is this:**

/kind bug

**What does this PR do / why we need it:**

When running `odo dev -v2`, output of commands are displayed on stdout, and makes some tests fail because of these unexpected data in output. 

**Which issue(s) this PR fixes:**

Fixes #

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

### CODE REVIEW

**Comment by valaparthvi** [comment]
/override ci/prow/v4.11-integration-e2e
IBM passes.

**Comment by valaparthvi** [comment]
I couldn't reproduce the error, and I couldn't try to fake the error either, do you know if there is a way to test that this will work as expected?

**Comment by feloy** [comment]
The lines:
```
      + 	cat: /opt/odo/.odo_cmd_run.pid: No such file or directory
        	✓  Building your application in container on cluster (command: build) [1s]
        	•  Executing the application (command: run)  ...
      + 	196
      + 	0
      + 	196
      + 	0
```

are displayed when you run odo dev with `-v2`.

With this patch, they are displayed as log, and not on stdout directly.

**Comment by valaparthvi** [comment]
> The lines:
> 
> ```
>       + 	cat: /opt/odo/.odo_cmd_run.pid: No such file or directory
>         	✓  Building your application in container on cluster (command: build) [1s]
>         	•  Executing the application (command: run)  ...
>       + 	196
>       + 	0
>       + 	196
>       + 	0
> ```
> 
> are displayed when you run odo dev with `-v2`.
> 
> With this patch, they are displayed as log, and not on stdout directly.

I understand that, but I wasn't able to reproduce the error when I ran doc tests. So I tried to fake my way into getting an output like that, but couldn't. I'll try running the tests again.

But, if you're able to reproduce the error and this solution works for you, I'll take your word for it.

/lgtm

**Pull request merged**
