### PR TITLE
Bump odo to v3.1.0

### PR DESCRIPTION
**Pull request by dharmit**

### CODE REVIEW

**Comment by anandrkskd** [comment]
We are not going to update [build/VERSION](https://github.com/redhat-developer/odo/blob/main/build/VERSION) file?

**Comment by dharmit** [comment]
Infra errors:
```
error: creating temp namespace: Post "https://api.ci-op-9lc9s7pp-c362a.origin-ci-int-aws.dev.rhcloud.com:6443/api/v1/namespaces": dial tcp 3.136.69.97:6443: connect: connection refused
{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"k8s.io/test-infra/prow/entrypoint/run.go:79","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2022-10-18T05:36:12Z"}
error: failed to execute wrapped command: exit status 1
```
/test v4.11-integration-e2e

**Comment by dharmit** [comment]
/override OpenShift-Integration-tests

Because prow tests are passing.

**Comment by dharmit** [comment]
/override OpenShift-Integration-tests/OpenShift-Integration-tests

Because prow tests are passing.

**Pull request merged**
