### PR TITLE
update golang-ci to 1.46.2

### PR DESCRIPTION
**Pull request by kadel**

### CODE REVIEW

**Review by rm3l — COMMENTED** [review]
I think this PR duplicates https://github.com/redhat-developer/odo/pull/5870

**Comment by kadel** [comment]
> I think this PR duplicates #5870

oh, I did not noticed that when I opened this one :-(

But it looks like https://github.com/redhat-developer/odo/pull/5870 was closed. @anandrkskd, are you planning to reopen your PR? I don't mind closing this one in favor of #5870

**Comment by anandrkskd** [comment]
> @anandrkskd, are you planning to reopen your PR? I don't mind closing this one in favor of https://github.com/redhat-developer/odo/pull/5870

That PR won't fix the issue we encountered on our tests. Instead, I have this [PR](https://github.com/redhat-developer/odo/pull/5934) opened for fixing the unit test, and I am using the same version as before. i.e `1.37.0` for the tests. 
I think the main question would be, do we want to use the new version `1.46.2` ?

**Comment by kadel** [comment]
> I think the main question would be, do we want to use the new version `1.46.2` ?

I think that we do ;-) We should regularly update  our tools

**Comment by kadel** [comment]
/close
in favor of https://github.com/redhat-developer/odo/pull/5934

**Pull request closed without merging**
