### PR TITLE
Automate Doc: Quickstart Guides

### LINKED ISSUE #6466: Automate Doc: Quickstart Guide
/kind user-story

## User Story
As an odo developer I want to examples in doc to be up to date with the latest changes in odo So that the doc examples stay up to date.

## Acceptance Criteria 
- [ ] It should test all the examples mentioned inside the quickstart guide docs.

## Links 
- Related Epic (mandatory): #6192 

/kind user-story

### PR DESCRIPTION
**Pull request by valaparthvi**
Signed-off-by: Parthvi Vala <pvala@redhat.com>

**What type of PR is this:**
/kind tests
/area documentation

**What does this PR do / why we need it:**
This PR adds tests to verify quickstart doc outputs.

**Which issue(s) this PR fixes:**

Fixes #6466 

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

### CODE REVIEW

**Comment by feloy** [comment]
@valaparthvi When running the tests locally, with a Kubernetes cluster, I get the following error. Do you get it too?

```
Expected
      <string>:   (
        	"""
        	... // 11 identical lines
        	✓  Pod is Running
        	✓  Syncing files into the container [1s]
      + 	cat: /opt/odo/.odo_cmd_run.pid: No such file or directory
        	✓  Building your application in container on cluster (command: build) [1s]
        	•  Executing the application (command: run)  ...
      + 	196
      + 	0
      + 	196
      + 	0
        	-  Forwarding from 127.0.0.1:40001 -> 8080
        	
        	... // 11 identical lines
        	"""
        )
      
  to be empty
```

**Comment by valaparthvi** [comment]
> @valaparthvi When running the tests locally, with a Kubernetes cluster, I get the following error. Do you get it too?
> 
> ```
> Expected
>       <string>:   (
>         	"""
>         	... // 11 identical lines
>         	✓  Pod is Running
>         	✓  Syncing files into the container [1s]
>       + 	cat: /opt/odo/.odo_cmd_run.pid: No such file or directory
>         	✓  Building your application in container on cluster (command: build) [1s]
>         	•  Executing the application (command: run)  ...
>       + 	196
>       + 	0
>       + 	196
>       + 	0
>         	-  Forwarding from 127.0.0.1:40001 -> 8080
>         	
>         	... // 11 identical lines
>         	"""
>         )
>       
>   to be empty
> ```

I didn't encounter it while working on the tests, I'll re-run the tests though.

**Comment by valaparthvi** [comment]
> > @valaparthvi When running the tests locally, with a Kubernetes cluster, I get the following error. Do you get it too?
> > ```
> > Expected
> >       <string>:   (
> >         	"""
> >         	... // 11 identical lines
> >         	✓  Pod is Running
> >         	✓  Syncing files into the container [1s]
> >       + 	cat: /opt/odo/.odo_cmd_run.pid: No such file or directory
> >         	✓  Building your application in container on cluster (command: build) [1s]
> >         	•  Executing the application (command: run)  ...
> >       + 	196
> >       + 	0
> >       + 	196
> >       + 	0
> >         	-  Forwarding from 127.0.0.1:40001 -> 8080
> >         	
> >         	... // 11 identical lines
> >         	"""
> >         )
> >       
> >   to be empty
> > ```
> 
> I didn't encounter it while working on the tests, I'll re-run the tests though.

I can see them now. I'll try to skip those.

**Comment by feloy** [comment]
@valaparthvi This PR should remove the unwanted output: https://github.com/redhat-developer/odo/pull/6473
Feel free to integrate the change in your PR

**Review by feloy — APPROVED** [review]

**Comment by valaparthvi** [comment]
/override OpenShift-Integration-tests/OpenShift-Integration-tests

I am overriding the test for now because the failure is unrelated to the changes made here, but the following failure needs to be investigated:
```sh
Expected
      <string>:   __
       /  \__     Developing using the "xpczcj" Devfile
       \__/  \    Namespace: cmd-logs-test189tbj
       /  \__/    odo version: v3.5.0
       \__/
      
      â†ª Deploying to the cluster in developer mode
       â€¢  Waiting for Kubernetes resources  ...
       â€¢  Creating resource Pod/myapp-inner  ...
      
 âœ“  Creating resource Pod/myapp-inner 
       âš   Pod is Pending
       âœ“  Pod is Running
       â€¢  Deleting resources not present in the Devfile: PodMetrics/myapp-inner  ...
      
 âœ“  Deleting resources not present in the Devfile: PodMetrics/myapp-inner [1s]
      Error occurred on Push - watch command was unable to push component: unable to delete remote resources: unable to delete resource: PodMetrics/myapp-inner: the server does not allow this method on the requested resource
      
       â€¢  Deleting resources not present in the Devfile: PodMetrics/myapp-inner  ...
      
 âœ“  Deleting resources not present in the Devfile: PodMetrics/myapp-inner [1s]
      Error occurred on Push - watch command was unable to push component: unable to delete remote resources: unable to delete resource: PodMetrics/myapp-inner: the server does not allow this method on the requested resource
  ```

**Pull request merged**
