### PR TITLE
[v3] update to SBO library to 1.0

### PR DESCRIPTION
**Pull request by feloy**
By merging this PR on main, we can make odo v3 able to push services to cluster with or without SBO installed. 

As odo v3 does not support the addition of services to devfile, the integration tests testing the deployment of services has been removed, and there is no more blocker for merging this PR (inn opposite to v2 which still tests services deployments)

The PR for v2 branch is https://github.com/redhat-developer/odo/pull/5446

- [x] Binding Redis instance fails if instance created without `redisSecret` field (https://github.com/redhat-developer/service-binding-operator/issues/1088)
- [x] unlinking two components with SBO installed fails: `ListOperatorServices` was `break`ing after the firdt empty list found
- [x] no SBO installed and non-admin user and link to component: error `no binding data to project`

if you delete the Service Binding Operator from your OpenShift cluster, `IsResourceSupported` continues to detect it => in this circumstance, odo will create `sbr` for binding, and will timeout waiting for deployment to be restarted after the sbr is created. SOLUTION: delete servicebindings CRDs manually

### CODE REVIEW

**Comment by cdrage** [comment]
I can confirm that this fixes the issue with the PostgreSQL operator and binding:

```sh
~/odo-quickstart/backend  main ✗                                                                                                                                                                                                                                                                                                                                    120d ◒  
▶ odo push

Validation
 ✓  Validating the devfile [94559ns]

Creating Services for component backend
 ✓  Created service "PostgresCluster/hippo" on the cluster; refer "odo link -h" to know how to link it to the component

Creating Kubernetes resources for component backend
 ✓  Waiting for component to start [7ms]
 ✓  Created link "backend-postgrescluster-hippo" using Service Binding Operator on the cluster; component will be restarted
 ✓  Restarting the component [5s]
 ✓  Waiting for component to start [9s]

Applying URL changes
 ✓  URL backend-8080: http://backend-8080.k8s.land/ created

Syncing to component backend
 ✓  Checking file changes for pushing [13ms]
 ✓  Syncing files to the component [511ms]

Executing devfile commands for component backend
 ✓  Executing build command "mvn clean -Dmaven.repo.local=/home/user/.m2/repository package -Dmaven.test.skip=true" [5s]
 ✓  Executing run command "mvn -Dmaven.repo.local=/home/user/.m2/repository spring-boot:run" [1s]

Pushing devfile component "backend"
 ✓  Changes successfully pushed to component
```

**Comment by dharmit** [comment]
Code LGTM

/lgtm

**Comment by dharmit** [comment]
/retest

Want to see if all the tests still pass. It's been a while since tests succeeded for this PR.

**Comment by dharmit** [comment]
> /retest
> 
> Want to see if all the tests still pass. It's been a while since tests succeeded for this PR.

/test v4.9-integration-e2e

**Pull request merged**
