### PR TITLE
Small fix according to golang ci

### PR DESCRIPTION
**Pull request by surajnarwade**
* Removed unused variable `dc`
* define variable `currentProjectName` properly

### CODE REVIEW

**Comment by cdrage** [comment]
Please capitalize the git commit title as well as add a description / issue to link! :+1: https://github.com/redhat-developer/odo/blob/master/docs/development.md#creating-a-pull-request

**Comment by surajnarwade** [comment]
@cdrage updated :tada:

**Comment by cdrage** [comment]
LGTM!

**Comment by anmolbabu** [comment]
Merging based on above acks

**Pull request merged**
