### PR TITLE
Make remaining docs consistent

### LINKED ISSUE #6143: Create dropdown menus for examples for user guides / other documentation.
/area documentation
/kind bug

## What mistake did you find / what is missing in the documentation?

See: https://github.com/redhat-developer/odo/pull/6126

We should make the example output as dropdown menus as well on all the tutorial guides / etc.

## What is the relevance of it?

Cleaner and looks better! :)

### PR DESCRIPTION
**Pull request by SD-13**
**What type of PR is this:**
/area documentation
/kind feature

**What does this PR do / why we need it:**

**Which issue(s) this PR fixes:**

Fixes #6143 

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [X] Documentation 

**How to test changes / Special notes to the reviewer:**

### CODE REVIEW

**Comment by SD-13** [comment]
Hi @valaparthvi , from your mentions, one file is remaining. I am having issues with binding the component and working on it. Will update that soon. Thanks,

**Review by valaparthvi — APPROVED** [review]
Thank you for working on this. I'll merge this for now, you can raise a separate PR for the tutorial, or leave it be for now. I am working on an issue that will probably refactor the doc.

**Comment by SD-13** [comment]
Hey @valaparthvi, thanks for the info, I will leave it for now.

**Pull request merged**
