### PR TITLE
Fix #1329: Add wait flag to wait for project to be ready.

### LINKED ISSUE #1329: odo app create fails after odo project create
[kind/bug]

I discovered this when writing integration tests for the IntelliJ OpenShift Connector (which is odo based) and one of my test is first creating a project then creating an application in that project

## What versions of software are you using?
- Operating System: Win10 Pro
- Output of `odo version`:

```
odo v0.0.19 (61f278a1)             
                                   
Server: https://172.17.247.235:8443
OpenShift: v3.9.31                 
Kubernetes: v1.9.1+a0ce1bc657
```      

## How did you run odo exactly?
`odo project create jeff1 && odo app create --project jeff1 app1`

## Actual behavior

```
 ✓  New project created and now using project : jeff1
 ✗   jeff1 project does not exist
```

## Expected behavior

```
 ✓  New project created and now using project : jeff1
 Creating application: app1 in project: jeff1
Switched to application: app1 in project: jeff1
```

### PR DESCRIPTION
**Pull request by metacosm**
## What is the purpose of this change? What does it change?
See $SUBJECT.

## Was the change discussed in an issue?
fixes #1329

## How to test changes?
See #1329 for failing scenario that should now be fixed by adding the `-w` flag to the `project create` command to wait for the project to be created before returning.

### CODE REVIEW

**Comment by jeffmaury** [comment]
Ran: 

`odo project create jeff1 --wait && odo app create --project jeff1 app1`

and got:

` ✗  unknown (get namespaces)`

With log messages:

`odo project create jeff1 --wait -v 9 && odo app create --project jeff1 app1 -v 9`

```
I0226 11:11:41.229310   18208 loader.go:359] Config loaded from file C:\Users\Je
ffMAURY/.kube/config                                                            
I0226 11:11:41.276309   18208 occlient.go:438] Trying to connect to server 172.1
7.188.37:8443                                                                   
I0226 11:11:41.277308   18208 occlient.go:445] Server https://172.17.188.37:8443
 is up                                                                          
I0226 11:11:41.277308   18208 round_trippers.go:386] curl -k -v -XGET  -H "Accep
t: application/json, */*" -H "User-Agent: odo/v0.0.0 (windows/amd64) kubernetes/
$Format" -H "Authorization: Bearer mvJcjMBLW58fUx1CruqICVAZq_od0jSJ4hFxqpzyk8M" 
'https://172.17.188.37:8443/apis/user.openshift.io/v1/users/~'                  
I0226 11:11:41.292309   18208 round_trippers.go:405] GET https://172.17.188.37:8
443/apis/user.openshift.io/v1/users/~ 200 OK in 14 milliseconds                 
I0226 11:11:41.292309   18208 round_trippers.go:411] Response Headers:          
I0226 11:11:41.293310   18208 round_trippers.go:414]     Content-Type: applicati
on/json                                                                         
I0226 11:11:41.294308   18208 round_trippers.go:414]     Date: Mon, 25 Feb 2019 
20:54:33 GMT                                                                    
I0226 11:11:41.294308   18208 round_trippers.go:414]     Content-Length: 306    
I0226 11:11:41.295309   18208 round_trippers.go:414]     Cache-Control: no-store
                                                                                
I0226 11:11:41.296310   18208 round_trippers.go:414]     Cache-Control: no-store
                                                                                
I0226 11:11:41.296310   18208 request.go:897] Response Body: {"kind":"User","api
Version":"user.openshift.io/v1","metadata":{"name":"developer","selfLink":"/apis
/user.openshift.io/v1/users/developer","uid":"041a6d28-3924-11e9-80c3-00155d0028
27","resourceVersion":"1876","creationTimestamp":"2019-02-25T17:37:26Z"},"identi
ties":["anypassword:developer"],"groups":null}                                  
I0226 11:11:41.298309   18208 occlient.go:368] isLoggedIn err:  <nil>           
 output: "developer"                                                            
I0226 11:11:41.299309   18208 context.go:231] Ignoring error as it usually means
 flag wasn't set: flag accessed but not defined: project                        
I0226 11:11:41.299309   18208 round_trippers.go:386] curl -k -v -XGET  -H "Accep
t: application/json, */*" -H "User-Agent: odo/v0.0.0 (windows/amd64) kubernetes/
$Format" -H "Authorization: Bearer mvJcjMBLW58fUx1CruqICVAZq_od0jSJ4hFxqpzyk8M" 
'https://172.17.188.37:8443/apis/project.openshift.io/v1/projects'              
I0226 11:11:41.303310   18208 round_trippers.go:405] GET https://172.17.188.37:8
443/apis/project.openshift.io/v1/projects 200 OK in 3 milliseconds              
I0226 11:11:41.303310   18208 round_trippers.go:411] Response Headers:          
I0226 11:11:41.304308   18208 round_trippers.go:414]     Cache-Control: no-store
                                                                                
I0226 11:11:41.304308   18208 round_trippers.go:414]     Cache-Control: no-store
                                                                                
I0226 11:11:41.306341   18208 round_trippers.go:414]     Content-Type: applicati
on/json                                                                         
I0226 11:11:41.306341   18208 round_trippers.go:414]     Date: Mon, 25 Feb 2019 
20:54:33 GMT                                                                    
I0226 11:11:41.307307   18208 round_trippers.go:414]     Content-Length: 689    
I0226 11:11:41.307307   18208 request.go:897] Response Body: {"kind":"ProjectLis
t","apiVersion":"project.openshift.io/v1","metadata":{"selfLink":"/apis/project.
openshift.io/v1/projects"},"items":[{"metadata":{"name":"tets","selfLink":"/apis
/project.openshift.io/v1/projects/tets","uid":"70d6e196-392e-11e9-95d9-00155d002
827","resourceVersion":"14133","creationTimestamp":"2019-02-25T18:52:03Z","annot
ations":{"openshift.io/description":"","openshift.io/display-name":"","openshift
.io/requester":"developer","openshift.io/sa.scc.mcs":"s0:c16,c10","openshift.io/
sa.scc.supplemental-groups":"1000260000/10000","openshift.io/sa.scc.uid-range":"
1000260000/10000"}},"spec":{"finalizers":["openshift.io/origin","kubernetes"]},"
status":{"phase":"Active"}}]}                                                   
I0226 11:11:41.311308   18208 context.go:231] Ignoring error as it usually means
 flag wasn't set: flag accessed but not defined: app                            
I0226 11:11:41.312310   18208 context.go:231] Ignoring error as it usually means
 flag wasn't set: flag accessed but not defined: component                      
 •  Waiting for project to come up  ...                                         
I0226 11:11:41.313324   18208 request.go:897] Request Body: {"kind":"ProjectRequ
est","apiVersion":"project.openshift.io/v1","metadata":{"name":"jeff1","creation
Timestamp":null}}                                                               
I0226 11:11:41.315310   18208 round_trippers.go:386] curl -k -v -XPOST  -H "Auth
orization: Bearer mvJcjMBLW58fUx1CruqICVAZq_od0jSJ4hFxqpzyk8M" -H "Accept: appli
cation/json, */*" -H "Content-Type: application/json" -H "User-Agent: odo/v0.0.0
 (windows/amd64) kubernetes/$Format" 'https://172.17.188.37:8443/apis/project.op
enshift.io/v1/projectrequests'                                                  
I0226 11:11:41.417311   18208 round_trippers.go:405] POST https://172.17.188.37:
8443/apis/project.openshift.io/v1/projectrequests 201 Created in 93 milliseconds
                                                                                
I0226 11:11:41.419310   18208 round_trippers.go:411] Response Headers:          
I0226 11:11:41.421313   18208 round_trippers.go:414]     Cache-Control: no-store
                                                                                
I0226 11:11:41.422315   18208 round_trippers.go:414]     Cache-Control: no-store
                                                                                
I0226 11:11:41.424308   18208 round_trippers.go:414]     Content-Type: applicati
on/json                                                                         
I0226 11:11:41.427313   18208 round_trippers.go:414]     Date: Mon, 25 Feb 2019 
20:54:33 GMT                                                                    
I0226 11:11:41.428315   18208 round_trippers.go:414]     Content-Length: 617    
I0226 11:11:41.428315   18208 request.go:897] Response Body: {"kind":"Project","
apiVersion":"project.openshift.io/v1","metadata":{"name":"jeff1","selfLink":"/ap
is/project.openshift.io/v1/projectrequests/jeff1","uid":"8db0ee99-393f-11e9-95d9
-00155d002827","resourceVersion":"32133","creationTimestamp":"2019-02-25T20:54:3
3Z","annotations":{"openshift.io/description":"","openshift.io/display-name":"",
"openshift.io/requester":"developer","openshift.io/sa.scc.mcs":"s0:c18,c12","ope
nshift.io/sa.scc.supplemental-groups":"1000330000/10000","openshift.io/sa.scc.ui
d-range":"1000330000/10000"}},"spec":{"finalizers":["openshift.io/origin","kuber
netes"]},"status":{"phase":"Active"}}                                           
I0226 11:11:41.432311   18208 round_trippers.go:386] curl -k -v -XGET  -H "User-
Agent: odo/v0.0.0 (windows/amd64) kubernetes/$Format" -H "Authorization: Bearer 
mvJcjMBLW58fUx1CruqICVAZq_od0jSJ4hFxqpzyk8M" -H "Accept: application/json, */*" 
'https://172.17.188.37:8443/api/v1/namespaces?fieldSelector=metadata.name%3Djeff
1&watch=true'                                                                   
I0226 11:11:41.437308   18208 round_trippers.go:405] GET https://172.17.188.37:8
443/api/v1/namespaces?fieldSelector=metadata.name%3Djeff1&watch=true 403 Forbidd
en in 2 milliseconds                                                            
I0226 11:11:41.438309   18208 round_trippers.go:411] Response Headers:          
I0226 11:11:41.439309   18208 round_trippers.go:414]     Cache-Control: no-store
                                                                                
I0226 11:11:41.439309   18208 round_trippers.go:414]     Content-Type: applicati
on/json                                                                         
I0226 11:11:41.440315   18208 round_trippers.go:414]     X-Content-Type-Options:
 nosniff                                                                        
I0226 11:11:41.441311   18208 round_trippers.go:414]     Content-Length: 297    
I0226 11:11:41.442309   18208 round_trippers.go:414]     Date: Mon, 25 Feb 2019 
20:54:33 GMT                                                                    
I0226 11:11:41.443312   18208 request.go:897] Response Body: {"kind":"Status","a
piVersion":"v1","metadata":{},"status":"Failure","message":"namespaces is forbid
den: User \"developer\" cannot watch namespaces at the cluster scope: User \"dev
eloper\" cannot watch all namespaces in the cluster","reason":"Forbidden","detai
ls":{"kind":"namespaces"},"code":403}                                           
I0226 11:11:41.445314   18208 cmdutils.go:21] Error:                            
unable to create new project: unable to watch new project jeff1 creation: unknow
n (get namespaces)                                                              
 ✗  unknown (get namespaces)                                                    
```

I think you should try to watch Projects and not Namespaces, we're on OpenShift :)

**Comment by metacosm** [comment]
@jeffmaury it works on OpenShift, you just need better privileges :)
I will see if I can make it work with developer privileges.

**Comment by metacosm** [comment]
@jeffmaury Give it another try when the AppVeyor binary is ready.

**Comment by jeffmaury** [comment]
Works for me now with the latest binary

**Comment by syamgk** [comment]
@metacosm it would be nice if you can add one end to test for this flag

**Pull request merged**
