### PR TITLE
Refactor occlient

### LINKED ISSUE #5249: Merging occlient with kclient
/kind bug

There is a lot of duplication between those occlient and kclient, and with recent move to removing s2i related code from odo there are only 2 things that are specific to OpenShift that odo uses (Routes and Projects). Technically even those two are just another Kubernetes resources that are not different from any other Kubernetes CRs. Odo should treat all resources the same way (https://github.com/openshift/odo/issues/5247#issuecomment-978933036).

It will also simplify the Context, to have only one client instead of 3 (kclient, occlient and occlient.kclient)

### PR DESCRIPTION
**Pull request by feloy**
**What type of PR is this?**
/kind cleanup

**What does this PR do / why we need it**:

Moves occlient package into kclient package

**Which issue(s) this PR fixes**:

Fixes #5249

**PR acceptance criteria**:

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

- [ ] I have read the [test guidelines](https://github.com/redhat-developer/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by feloy** [comment]
OpenShift Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-openshift-tests-117.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-openshift-tests-117.html)

**Comment by feloy** [comment]
Kubernetes Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-kubernetes-tests-88.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-kubernetes-tests-88.html)

**Comment by feloy** [comment]
Unit Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-unit-tests-101.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-unit-tests-101.html)

**Comment by feloy** [comment]
Kubernetes Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-kubernetes-tests-89.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-kubernetes-tests-89.html)

**Comment by feloy** [comment]
Unit Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-unit-tests-102.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-unit-tests-102.html)

**Comment by feloy** [comment]
OpenShift Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-openshift-tests-118.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-openshift-tests-118.html)

**Comment by feloy** [comment]
Kubernetes Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-kubernetes-tests-93.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-kubernetes-tests-93.html)

**Comment by feloy** [comment]
OpenShift Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-openshift-tests-122.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-openshift-tests-122.html)

**Comment by feloy** [comment]
Unit Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-unit-tests-106.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-unit-tests-106.html)

**Comment by feloy** [comment]
Kubernetes Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-kubernetes-tests-94.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-kubernetes-tests-94.html)

**Comment by feloy** [comment]
OpenShift Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-openshift-tests-123.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-openshift-tests-123.html)

**Comment by feloy** [comment]
Unit Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-unit-tests-107.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-unit-tests-107.html)

**Comment by feloy** [comment]
OpenShift Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-openshift-tests-124.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-openshift-tests-124.html)

**Comment by feloy** [comment]
Unit Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-unit-tests-108.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-unit-tests-108.html)

**Comment by feloy** [comment]
Kubernetes Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-kubernetes-tests-96.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-kubernetes-tests-96.html)

**Comment by feloy** [comment]
Unit Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-unit-tests-109.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-unit-tests-109.html)

**Comment by feloy** [comment]
OpenShift Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-openshift-tests-125.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-openshift-tests-125.html)

**Comment by feloy** [comment]
Kubernetes Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-kubernetes-tests-97.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-kubernetes-tests-97.html)

**Comment by feloy** [comment]
Unit Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-unit-tests-110.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-unit-tests-110.html)

**Comment by feloy** [comment]
OpenShift Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-openshift-tests-126.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-openshift-tests-126.html)

**Comment by feloy** [comment]
Kubernetes Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-kubernetes-tests-98.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-kubernetes-tests-98.html)

**Comment by feloy** [comment]
Unit Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-unit-tests-111.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-unit-tests-111.html)

**Comment by feloy** [comment]
OpenShift Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-openshift-tests-127.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-openshift-tests-127.html)

**Comment by feloy** [comment]
Kubernetes Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-kubernetes-tests-99.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-kubernetes-tests-99.html)

**Comment by feloy** [comment]
Unit Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-unit-tests-112.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-unit-tests-112.html)

**Comment by feloy** [comment]
/test v4.9-integration-e2e

```
[Fail] odo devfile create command tests when devfile exists in the working directory when devfile contains parent URI [It] should not replace the original devfile 
/go/src/github.com/redhat-developer/odo/tests/helper/helper_cmd_wrapper.go:100
[Fail] odo devfile create command tests when devfile does not exist in the working directory and user specifies the devfile path via --devfile when devfile contains parent URI [It] should not replace the original devfile 
/go/src/github.com/redhat-developer/odo/tests/helper/helper_cmd_wrapper.go:100

```

**Comment by feloy** [comment]
OpenShift Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-openshift-tests-136.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-openshift-tests-136.html)

**Comment by feloy** [comment]
Kubernetes Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-kubernetes-tests-107.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-kubernetes-tests-107.html)

**Comment by feloy** [comment]
Unit Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-unit-tests-120.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-unit-tests-120.html)

**Comment by feloy** [comment]
Kubernetes Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-kubernetes-tests-112.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-kubernetes-tests-112.html)

**Comment by feloy** [comment]
Unit Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-unit-tests-125.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-unit-tests-125.html)

**Comment by feloy** [comment]
OpenShift Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-openshift-tests-141.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-openshift-tests-141.html)

**Review by valaparthvi — CHANGES_REQUESTED** [review]
Can you remove empty files (utils.go, utils_test.go, occlient.go, occlient_test.go, etc)?

Everything else looks good to me, thanks for the change :)

**Comment by feloy** [comment]
Kubernetes Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-kubernetes-tests-114.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-kubernetes-tests-114.html)

**Comment by feloy** [comment]
Unit Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-unit-tests-127.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-unit-tests-127.html)

**Comment by feloy** [comment]
OpenShift Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-openshift-tests-143.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5271-openshift-tests-143.html)

**Review by valaparthvi — APPROVED** [review]

**Pull request merged**
