### PR TITLE
Adding check in odo dev interactive mode for pod/sync to complete 

### LINKED ISSUE #6594: [Flake] add check in odo dev interactive mode for pod/sync to complete
/area testing

Test for odo dev on interactive mode are flaky. Tests fail on PR while waiting for sync to complete.

We can reduce this by adding a check for pod sync before checking for [[ctrl+c]](https://github.com/redhat-developer/odo/blob/main/tests/integration/interactive_dev_test.go#L99) in output.

### PR DESCRIPTION
**Pull request by ritudes**
**What type of PR is this:**
/area testing 

**What does this PR do / why we need it:**
Adds the feature to check and ensure if a pod is created and running before any devfile command is run
**Which issue(s) this PR fixes:**

Fixes #6594 

**PR acceptance criteria:**

- [ ] Unit test 

- [x] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

### CODE REVIEW

**Comment by anandrkskd** [comment]
Below test failed, 
```
â€¢ [FAILED] [266.797 seconds]
odo dev command tests
/go/odo_1/tests/integration/cmd_dev_test.go:33
  when Starting a PostgreSQL service
  /go/odo_1/tests/integration/cmd_dev_test.go:1168
    when creating local files and dir and running odo dev - with metadata.name [AfterEach]
    /go/odo_1/tests/integration/cmd_dev_test.go:1209
      when deleting local files and dir and waiting for sync
      /go/odo_1/tests/integration/cmd_dev_test.go:1223
        should not list deleted dir and file in container
        /go/odo_1/tests/integration/cmd_dev_test.go:1231
```
re-running test, failures are not related to changes

**Comment by feloy** [comment]
It is not clear to me how this change can make the test less flaky.

Could you share some example of failure for which this addition could help?

**Comment by anandrkskd** [comment]
This is one of the error we experienced on InterOP test and this failure was caused due to the timeout we have in expectString function that was waiting for pod/sync process to complete.
By adding the EnsurePodIsUp before checking, `"[Ctrl+c] - Exit"` we make sure the process is completed.

```
error while sending or expecting line: "[Ctrl+c] - Exit"
=== output of command '["odo" "dev" "--random-ports"]' read so far ===
  __
 /  \__     Dev mode ran, but no Devfile was found. Initializing a component in the current directory
 \__/  \    Files: Source code detected, a Devfile will be determined based upon source code autodetection
 /  \__/    odo version: v3.6.0
 \__/

Interactive mode enabled, please answer the following questions:
Based on the files in the current directory odo detected
Language: Python
Project type: Python
The devfile "python:2.1.0" from the registry "DefaultDevfileRegistry" will be downloaded.
�[0G�[2K�[1;92m? �[0m�[1;99mIs this correct? �[0m�[37m(Y/n) �[0m�[?25l�7�[999;999f�[6n�8�[?25h�[6n�[1B�[0G�[1A�[0G�[0G�[2K�[1;92m? �[0m�[1;99mIs this correct? �[0m�[36mYes�[0m



 ✓  Downloading devfile "python:2.1.0" from registry "DefaultDevfileRegistry" [104ms]

↪ Container Configuration "py":
  OPEN PORTS:
    - 8080
    - 5858
  ENVIRONMENT VARIABLES:
    - DEBUG_PORT = 5858

�7�[?25l�8�[0G�[2K�[1;92m? �[0m�[1;99mSelect container for which you want to change configuration?�[0m  �[36m[Use arrows to move, type to filter]�[0m
�[39m  py�[0m
�[1;36m> NONE - configuration is correct�[0m
�7
�[1A�[0G�8�[?25h�8�[0G�[2K�[1A�[0G�[2K�[1A�[0G�[2K�[1A�[0G�[2K�[1A�[0G�[2K�[1;92m? �[0m�[1;99mSelect container for which you want to change configuration?�[0m�[36m NONE - configuration is correct�[0m
�[0G�[2K�[1;92m? �[0m�[1;99mEnter component name: �[0m�[37m(x847091490) �[0m�[?25l�[?25l�7�[999;999f�[6n�8�[?25h�[6nmy-app�[1D�[1D�[1D�[1D�[1D�[1D�[1B�[0G�[1A�[?25h�[0G�[2K�[1;92m? �[0m�[1;99mEnter component name: �[0m�[36mmy-app�[0m
  __
 /  \__     Developing using the "my-app" Devfile
 \__/  \    Namespace: interactive-dev-test106zxu
 /  \__/    odo version: v3.6.0
 \__/

↪ Running on the cluster in Dev mode
 •  Waiting for Kubernetes resources  ...
W0213 10:27:53.769603   83969 warnings.go:70] would violate PodSecurity "restricted:latest": seccompProfile (pod or container "py" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
 ⚠  Pod is Pending
W0213 10:27:54.778272   83969 warnings.go:70] would violate PodSecurity "restricted:latest": seccompProfile (pod or container "py" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
W0213 10:27:55.877387   83969 warnings.go:70] would violate PodSecurity "restricted:latest": seccompProfile (pod or container "py" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
W0213 10:27:56.504983   83969 warnings.go:70] would violate PodSecurity "restricted:latest": seccompProfile (pod or container "py" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")

======================
Unexpected error:
    <*xpty.errPassthroughTimeout | 0xc0008c6020>: {
        error: <*errors.errorString | 0xc0008c6010>{
            s: "passthrough i/o timeout",
        },
    }
    passthrough i/o timeout
occurred
```

**Comment by feloy** [comment]
> It is not clear to me how this change can make the test less flaky.
> 
> Could you share some example of failure for which this addition could help?

As discussed, this increases the timeout for the pod to be up.

LGTM

**Comment by feloy** [comment]
/override ci/prow/v4.10-images

Thanks @ritudes for this fix

**Pull request merged**
