### PR TITLE
Use oceanicNext dark theme for website

### LINKED ISSUE #6002: YAML syntax highlighting in dark mode is partially broken
/area documentation
/kind bug

## What mistake did you find / what is missing in the documentation?

YAML syntax highlighting in dark mode is partially broken, due to a problem with the specific prism renderer.

https://odo.dev/docs/user-guides/advanced/pushing-specific-files

We could fix this by using a different dark theme, for example, 

```
  darkTheme: require('prism-react-renderer/themes/oceanicNext')
```

Or by adding a temporary CSS fix in src/css/custom.css:

```
.token.atrule {
	color: #c792ea;
}
```

## What is the relevance of it?

Dark mode is probably the preferred reading mode, and better syntax highlighting would improve the user experience

### PR DESCRIPTION
**Pull request by valaparthvi**
**What type of PR is this:**
/kind documentation
/area documentation

**What does this PR do / why we need it:**

**Which issue(s) this PR fixes:**

Fixes #6002 

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [x] Documentation 

**How to test changes / Special notes to the reviewer:**
Change to dark mode on the website.

### CODE REVIEW

**Comment by valaparthvi** [comment]
/override OpenShift Integration tests/OpenShift Integration tests
Docs PR.

**Review by rm3l — APPROVED** [review]
😍 Looks much better

**Comment by dharmit** [comment]
Looks really great when comparing the YAML codeblocks between `main` and this PR. Just wondering if a variant of monokai or jellybeans themes is available. Especially monokai is very popular for good reasons, IMO. But just a personal preference.

Thanks for addressing this.
/approve

**Comment by dharmit** [comment]
> Just wondering if a variant of monokai or jellybeans themes is available. Especially monokai is very popular for good reasons, IMO. But just a personal preference.

I just saw all the other available themes. I am glad something as good as oceanicNext is there. Phew.

**Pull request merged**
