### PR TITLE
Adding ritudes user id to tests/OWNERS 

### PR DESCRIPTION
**Pull request by ritudes**
**What type of PR is this:**

**What does this PR do / why we need it:**

**Which issue(s) this PR fixes:**

Fixes #

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

### CODE REVIEW

**Comment by feloy** [comment]
@ritudes, I think you need to start from a fresh new branch. This one already contains other commits, which are not related to OWNERS (and are probably some tests)

**Comment by ritudes** [comment]
@feloy I have commited the changes, can  you review them again?

**Review by feloy — APPROVED** [review]

**Pull request merged**
