### PR TITLE
Add CLI images / information on index page of odo.dev

### PR DESCRIPTION
**Pull request by cdrage**
Add CLI images / information on index page of odo.dev

**What type of PR is this:**

/kind documentation

**What does this PR do / why we need it:**

Updates the index page with information / details on the CLI with
previews of using odo init, dev and deploy.

**Which issue(s) this PR fixes:**

Fixes part of https://github.com/redhat-developer/odo/issues/6034

Signed-off-by: Charlie Drage <charlie@charliedrage.com>

### CODE REVIEW

**Review by rm3l — COMMENTED** [review]
Nice - thanks.

/approve

**Comment by valaparthvi** [comment]
/lgtm
PR was rebased

**Comment by valaparthvi** [comment]
/override Kubernetes-Integration-Tests/Kubernetes-Integration-Tests 
/override windows-integration-test/Windows-test

I am overriding these tests for now since the change in the PR is unrelated. However I will continue to debug the flakes.

**Comment by valaparthvi** [comment]
/override Kubernetes-Integration-Tests/Kubernetes-Integration-Tests

**Pull request merged**
