### PR TITLE
Simplify devfile Kubernetes adapter

### PR DESCRIPTION
**Pull request by feloy**
**What type of PR is this:**

/kind bug

**What does this PR do / why we need it:**

This PR makes some refactoring on the Dev code, to simplify the legacy code, to prepare the changes for #6671 :

- Getting the values passed into the context
- Moving Devfile param to WatchParams insted of being part of the Adapter structure, and build adapter only once

**Which issue(s) this PR fixes:**

Fixes partially #6671

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

### CODE REVIEW

**Review by rm3l — COMMENTED** [review]
@feloy I was testing this PR and noticed there might be an issue in the logic for waiting until the application is listening on the expected ports prior to starting port forwarding.
I checked by delaying the start of my `run` command by 70 seconds (to check the timeout), but the spinner returned too quickly for me:

```
$ odo dev
  __
 /  \__     Developing using the "my-java-sb" Devfile
 \__/  \    Namespace: default
 /  \__/    odo version: v3.9.0
 \__/

 ⚠  You are using "default" namespace, odo may not work as expected in the default namespace.
 ⚠  You may set a new namespace by running `odo create namespace <name>`, or set an existing one by running `odo set namespace <name>`

↪ Running on the cluster in Dev mode
 •  Waiting for Kubernetes resources  ...
 ✓  Added storage m2 to component
 ⚠  Pod is Pending
 ✓  Pod is Running
 ✓  Syncing files into the container [116ms]
 ✓  Building your application in container (command: build) [45s]
 •  Executing the application (command: run)  ...
 ✓  Waiting for the application to be ready 
 -  Forwarding from 127.0.0.1:20001 -> 8080


↪ Dev mode
 Status:
 Watching for changes in the current directory /tmp/java-quarkus
```

I remember we discussed setting up port-forwarding as part of the code handling the infra, but that could come later, no?

**Comment by feloy** [comment]
> @feloy I was testing this PR and noticed there might be an issue in the logic for waiting until the application is listening on the expected ports prior to starting port forwarding. I checked by delaying the start of my `run` command by 70 seconds (to check the timeout), but the spinner returned too quickly for me:
> 
> ```
> $ odo dev
>   __
>  /  \__     Developing using the "my-java-sb" Devfile
>  \__/  \    Namespace: default
>  /  \__/    odo version: v3.9.0
>  \__/
> 
>  ⚠  You are using "default" namespace, odo may not work as expected in the default namespace.
>  ⚠  You may set a new namespace by running `odo create namespace <name>`, or set an existing one by running `odo set namespace <name>`
> 
> ↪ Running on the cluster in Dev mode
>  •  Waiting for Kubernetes resources  ...
>  ✓  Added storage m2 to component
>  ⚠  Pod is Pending
>  ✓  Pod is Running
>  ✓  Syncing files into the container [116ms]
>  ✓  Building your application in container (command: build) [45s]
>  •  Executing the application (command: run)  ...
>  ✓  Waiting for the application to be ready 
>  -  Forwarding from 127.0.0.1:20001 -> 8080
> 
> 
> ↪ Dev mode
>  Status:
>  Watching for changes in the current directory /tmp/java-quarkus
> ```
> 
> I remember we discussed setting up port-forwarding as part of the code handling the infra, but that could come later, no?

This behaviour is not expected to have changed. Let me check

**Comment by rm3l** [comment]
> > > @feloy I was testing this PR and noticed there might be an issue in the logic for waiting until the application is listening on the expected ports prior to starting port forwarding. I checked by delaying the start of my `run` command by 70 seconds (to check the timeout), but the spinner returned too quickly for me:
> > > ```
> > > $ odo dev
> > >   __
> > >  /  \__     Developing using the "my-java-sb" Devfile
> > >  \__/  \    Namespace: default
> > >  /  \__/    odo version: v3.9.0
> > >  \__/
> > > 
> > >  ⚠  You are using "default" namespace, odo may not work as expected in the default namespace.
> > >  ⚠  You may set a new namespace by running `odo create namespace <name>`, or set an existing one by running `odo set namespace <name>`
> > > 
> > > ↪ Running on the cluster in Dev mode
> > >  •  Waiting for Kubernetes resources  ...
> > >  ✓  Added storage m2 to component
> > >  ⚠  Pod is Pending
> > >  ✓  Pod is Running
> > >  ✓  Syncing files into the container [116ms]
> > >  ✓  Building your application in container (command: build) [45s]
> > >  •  Executing the application (command: run)  ...
> > >  ✓  Waiting for the application to be ready 
> > >  -  Forwarding from 127.0.0.1:20001 -> 8080
> > > 
> > > 
> > > ↪ Dev mode
> > >  Status:
> > >  Watching for changes in the current directory /tmp/java-quarkus
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I remember we discussed setting up port-forwarding as part of the code handling the infra, but that could come later, no?
> > 
> > 
> > This behaviour is not expected to have changed. Let me check
> 
> I have pushed a fix. thanks for catching the issue :)

Works better - thanks!

**Review by rm3l — APPROVED** [review]

**Comment by feloy** [comment]
/override windows-integration-test/Windows-test

```
[FAILED] [23.603 seconds]
odo list with devfile listing non-odo managed components when an operator managed deployment(without instance and managed-by label) is deployed [AfterEach] should not be listed in the odo list output
  [AfterEach] C:/Users/Administrator.ANSIBLE-TEST-VS/3792/tests/integration/cmd_devfile_list_test.go:85
  [It] C:/Users/Administrator.ANSIBLE-TEST-VS/3792/tests/integration/cmd_devfile_list_test.go:88

  [oc] Unable to connect to the server: dial tcp 161.156.12.82:31700: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
```

**Pull request merged**
