### PR TITLE
Adjust sidebars on odo.dev website

### LINKED ISSUE #6152: Adjust sidebars on odo.dev by making some sections expanded by default and others collapsed
/area documentation
/kind documentation

## What mistake did you find / what is missing in the documentation?
`Command Reference` should be the last section in the left sidebar.

## What is the relevance of it?
As the largest section, it hides other sections below it, like "Developer Reference".

### PR DESCRIPTION
**Pull request by valaparthvi**
**What type of PR is this:**
/kind documentation
/area documentation

**What does this PR do / why we need it:**
This PR adds adjustable collapsible sidebar.
**Which issue(s) this PR fixes:**

Fixes #6152 

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [x] Documentation 

**How to test changes / Special notes to the reviewer:**

### CODE REVIEW

**Comment by cdrage** [comment]
IMHO, I think we should have Advanced Usage also uncollapsed / open as well as the Deploying section, so we can showcase dev and deploy functionality.

Command reference as well as Developer Reference I agreed should be closed.

**Review by rm3l — COMMENTED** [review]
> IMHO, I think we should have Advanced Usage also uncollapsed / open as well as the Deploying section, so we can showcase dev and deploy functionality.
> 
> Command reference as well as Developer Reference I agreed should be closed.

But now we have the same issue with the "Developer Reference" not being visible unless you scroll.
image

I think "Advanced Usage" should remain collapsed, IMO, since it is supposed to be for advanced users, and they can expand it if needed. Or, as a tradeoff if we want to showcase deploy feature, would it make sense to just collapse "Deploying application"? Because I don't think we need to see  the different languages we wrote a page for..
image

**Comment by valaparthvi** [comment]
>Or, as a tradeoff if we want to showcase deploy feature, would it make sense to just collapse "Deploying application"? Because I don't think we need to see the different languages we wrote a page for..

I think the highlight for 'Advanced Usage' category is 'Deploying the application' part. If we collapse it, perhaps we can collapse the whole category.

**Comment by cdrage** [comment]
I like the current change 👍 I'm going to add my /approve

/approve

If we need more discussion on this, perhaps we can add this to the cabal?

**Review by rm3l — APPROVED** [review]
> I like the current change +1 I'm going to add my /approve
> 
> /approve
> 
> If we need more discussion on this, perhaps we can add this to the cabal?

Okay, that's fine then. Let's see what it gives later in terms of practical usage.

**Comment by rm3l** [comment]
/override Kubernetes-Integration-Tests/Kubernetes-Integration-Tests

Doc-only PR.

**Pull request merged**
