### PR TITLE
Add podman version to odo version output

### LINKED ISSUE #6806: Provide support in odo version for podman
Currently when we run odo commands on podman, we should also understand if podman is running or not in the user system.

The `odo version` command can verify that and list down in the podman version (if running). It should send this information as json so the IDE extension can leverage it and make an informed decision beforehand that whether the system has podman started.

### PR DESCRIPTION
**Pull request by valaparthvi**
**What type of PR is this:**
/kind feature

**What does this PR do / why we need it:**
This PR adds podman version (if available) to the `odo version` output.
**Which issue(s) this PR fixes:**

Fixes #6806

**PR acceptance criteria:**

- [ ] Unit test 

- [x] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

### CODE REVIEW

**Comment by valaparthvi** [comment]
/override OpenShift-Integration-tests/OpenShift-Integration-tests
Unrelated failure.

**Review by rm3l — CHANGES_REQUESTED** [review]
One last comment about the `--client` option: we are displaying warnings when a user specifies `--client`, but I think this can be quite confusing.

```
$ odo version --client        
 ⚠  unable to fetch the cluster server version
 ⚠  unable to fetch the podman client version
odo v3.11.0 (8e0cd5a80)
```

As a user, I'd expect to not even check Podman and clusters, so I think we should not display those warnings, no?

**Comment by rm3l** [comment]
Not sure why, but the Podman tests consistently fail on the same error: `Error: k8s.gcr.io/pause:3.5: image not known`

This was the first time I saw this kind of error..

**Comment by rm3l** [comment]
> Not sure why, but the Podman tests consistently fail on GitHub with the same error: `Error: k8s.gcr.io/pause:3.5: image not known`
> 
> This was the first time I saw this kind of error..
> 
> I noticed the same error on other PRs as well, like with #6924 ([redhat-developer/odo/actions/runs/5344975468/jobs/9690029602](https://github.com/redhat-developer/odo/actions/runs/5344975468/jobs/9690029602))

@valaparthvi Can you rebase your branch onto `main`? The tests on Podman should be passing now.

**Comment by rm3l** [comment]
```
  << Timeline

  [FAILED] user-guides/quickstart/docs-mdx/java/java_odo_dev_output.mdx
  Expected
      <string>: Â Â (
      Â Â 	"""
      Â Â 	... // 12 identical lines
      Â Â 	âœ“  Pod is Running
      Â Â 	âœ“  Syncing files into the container [1s]
      -Â 	âœ“  Building your application in container (command: build) [1s]
      -Â 	â€¢  Executing the application (command: run)  ...
      -Â 	âœ“  Waiting for the application to be ready [1s]
      -Â 	-  Forwarding from 127.0.0.1:20001 -> 8080
      +Â 	âœ—  Building your application in container (command: build) [1s]
      +Â 	Error occurred on Push - watch command was unable to push component: unable to exec command [/bin/sh -c cd ${PROJECT_SOURCE} && (mvn clean -Dmaven.repo.local=/home/user/.m2/repository package -Dmaven.test.skip=true) 1>>/proc/1/fd/1 2>>/proc/1/fd/2]: error while streaming command: command terminated with exit code 1
      Â Â 	
      Â Â 	
      Â Â 	... // 9 identical lines
      Â Â 	"""
      Â Â )
      
  to be empty
  In [It] at: /go/odo_1/tests/documentation/user-guides/doc_user_guides_quickstart_test.go:256 @ 06/23/23 18:22:16.76
------------------------------
Spawning '/go/bin/odo init' from /tmp/3658003557
â€¢

Summarizing 1 Failure:
  [FAIL] User guides: Quickstart test Java quickstart guide [It] should test the complete java springboot quickstart output in order
  /go/odo_1/tests/documentation/user-guides/doc_user_guides_quickstart_test.go:256

Ran 5 of 5 Specs in 231.043 seconds
FAIL! -- 4 Passed | 1 Failed | 0 Pending | 0 Skipped
--- FAIL: TestUserGuidesDocAutomation (231.06s)
FAIL
```

Unrelated.

/override Kubernetes-Integration-Tests/Kubernetes-Docs-Integration-Tests

**Pull request merged**
