### PR TITLE
odo dev: Cleanup after displaying the error

### LINKED ISSUE #6023: Error message displayed after cleanup is done
/kind bug

## Actual behavior

When odo dev is executed and an error occurs, the error message is displayed after the cleanup is done, which can take some time.

```
$ odo dev
  __
 /  \__     Developing using the compo1 Devfile
 \__/  \    Namespace: prj2
 /  \__/    odo version: v3.0.0-beta3
 \__/

↪ Deploying to the cluster in developer mode
 •  Waiting for Kubernetes resources  ...
Cleaning resources, please wait
[... cleaning the resources ...]
 ✗  no such file or directory
```
## Expected behavior

The error message should be displayed immediately.

```
$ odo dev
  __
 /  \__     Developing using the compo1 Devfile
 \__/  \    Namespace: prj2
 /  \__/    odo version: v3.0.0-beta3
 \__/

↪ Deploying to the cluster in developer mode
 •  Waiting for Kubernetes resources  ...
 ✗  no such file or directory
Cleaning resources, please wait
[... cleaning the resources ...] 
```

### PR DESCRIPTION
**Pull request by feloy**
**What type of PR is this:**

/kind bug

**What does this PR do / why we need it:**

**Which issue(s) this PR fixes:**

Fixes #6023 

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

### CODE REVIEW

**Review by rm3l — COMMENTED** [review]
Thanks.

/approve

**Comment by feloy** [comment]
Did we increase the Sonar Cloud sensitivity? 

The code removes one parameter from the eventWatcher function and does not increase the cognitive complexity of eventWatcher function, and the check now fails, when it was not blocking before.

@valaparthvi @dharmit any idea?

**Review by valaparthvi — APPROVED** [review]

**Comment by valaparthvi** [comment]
> Did we increase the Sonar Cloud sensitivity?
> 
> The code removes one parameter from the eventWatcher function and does not increase the cognitive complexity of eventWatcher function, and the check now fails, when it was not blocking before.
> 
> @valaparthvi @dharmit any idea?

We haven't made any recent changes to the sonar cloud. We can override them for now.

**Comment by dharmit** [comment]
> The code removes one parameter from the eventWatcher function and does not increase the cognitive complexity of eventWatcher function, and the check now fails, when it was not blocking before.

Technically, you are correct. But the number of parameters error that SonarCloud raised is something I find a bad idea as well https://github.com/redhat-developer/odo/pull/5933#discussion_r937481973.

**Comment by feloy** [comment]
/override ci/prow/v4.10-integration-e2e
Tests pass on IBM cloud

**Pull request merged**
