### PR TITLE
Fix #1268: Refactor login command to use Complete/Validate/Run pattern.

### LINKED ISSUE #1268: Refactor login command to follow complete-validate-run pattern
See #1142

### PR DESCRIPTION
**Pull request by metacosm**
## What is the purpose of this change? What does it change?
See $SUBJECT

## Was the change discussed in an issue?
fixes #1268 

## How to test changes?
Check that `odo login` still works as expected.

### CODE REVIEW

**Comment by geoand** [comment]
Looks good but needs a rebase

**Comment by syamgk** [comment]
LGTM, code works locally as well 
I've only tested the login using token scenario!

**Comment by mik-dass** [comment]
@metacosm Looks like the CI failed because of
```
appropriate message 
/home/travis/gopath/src/github.com/redhat-developer/odo/tests/e2e/login_test.go:80
  Expected
      <string>:  ✓  Login successful.
      
      You don't have any projects. You can try to create a new project, by running
      
          odo project create <project-name>
      
      
  to contain substring
      <string>: testproject1
```
Please have a look

**Comment by metacosm** [comment]
> @metacosm Looks like the CI failed because of
> 
> ```
> appropriate message 
> /home/travis/gopath/src/github.com/redhat-developer/odo/tests/e2e/login_test.go:80
>   Expected
>       <string>:  ✓  Login successful.
>       
>       You don't have any projects. You can try to create a new project, by running
>       
>           odo project create <project-name>
>       
>       
>   to contain substring
>       <string>: testproject1
> ```
> 
> Please have a look

CI is green, the failing test was due to the flakyness of login tests which should now be addressed now that #1279 is merged.

**Comment by anmolbabu** [comment]
Merging based on 2 acks and green travis

**Pull request merged**
