### PR TITLE
Bump odo to v3.0.0-rc2

### PR DESCRIPTION
**Pull request by dharmit**

### CODE REVIEW

**Comment by feloy** [comment]
This PR introduces changes in the Devfiles metadata that break the integration tests:

https://github.com/devfile/registry/commit/30d83f516b926b831a1fec25ac3447cb1f70a299

**Comment by valaparthvi** [comment]
> This PR introduces changes in the Devfiles metadata that break the integration tests:
> 
> [devfile/registry@30d83f5](https://github.com/devfile/registry/commit/30d83f516b926b831a1fec25ac3447cb1f70a299)

I am not sure I understand why this has failed. Is it because we are using proxy or something else?

**Comment by kadel** [comment]
> > This PR introduces changes in the Devfiles metadata that break the integration tests:
> > [devfile/registry@30d83f5](https://github.com/devfile/registry/commit/30d83f516b926b831a1fec25ac3447cb1f70a299)
> 
> I am not sure I understand why this has failed. Is it because we are using proxy or something else?

No, it is because of updated metadata. 
For example, the `language` field in Go stacks got capitalized. And our tests are doing strict matching, so they are expecting `go` on the output, but the updated stack has `Go`.

**Comment by valaparthvi** [comment]
https://github.com/redhat-developer/odo/pull/6140

**Comment by rm3l** [comment]
/hold

Blocked on #6140

**Comment by rm3l** [comment]
/hold cancel

@dharmit Could you please rebase your branch onto `main`, now that #6140 is merged?

**Comment by rm3l** [comment]
Resource issues in the OpenShift cluster? cc @valaparthvi (as the test boss for this week ;-))
One test was failing because of insufficient resources, but the pod ended up being scheduled but too late for the timeout; I think we can override this.

```
  Timed out after 180.001s.
  Expected
      <string>:   __
       /  \__     Developing using the nodejs Devfile
       \__/  \    Namespace: cmd-delete-test270uts
       /  \__/    odo version: v3.0.0-rc2
       \__/
      
      ↪ Deploying to the cluster in developer mode
       •  Waiting for Kubernetes resources  ...
       ⚠  Pod is Pending
       ⚠  0/3 nodes are available: 3 Insufficient memory.
       ⚠  0/3 nodes are available: 3 Insufficient memory.
       ⚠  0/3 nodes are available: 3 Insufficient memory.
       ✓  Pod is Running
       •  Syncing files into the container  ...

...
Summarizing 1 Failure:
  [FAIL] odo delete command tests when deleting a component containing preStop event that is deployed with DEV [BeforeEach] should contain preStop events list
  /go/odo_1/tests/helper/helper_run.go:40
```

**Comment by valaparthvi** [comment]
/override OpenShift-Integration-tests/OpenShift-Integration-tests
/override windows-integration-test/Windows-test

**Comment by rm3l** [comment]
```
• [FAILED] [67.700 seconds]
odo dev command tests
/go/src/github.com/redhat-developer/odo/tests/integration/cmd_dev_test.go:31
  when running odo dev and devfile with composite command - with metadata.name
  /go/src/github.com/redhat-developer/odo/tests/integration/cmd_dev_test.go:1449
    [It] should execute all commands in composite command
    /go/src/github.com/redhat-developer/odo/tests/integration/cmd_dev_test.go:1468

...

[oc] Error from server (Forbidden): pods is forbidden: User "developer" cannot list resource "pods" in API group "" in the namespace "cmd-dev-test1468hip": RBAC: [clusterrole.rbac.authorization.k8s.io "cluster-status" not found, clusterrole.rbac.authorization.k8s.io "system:basic-user" not found, clusterrole.rbac.authorization.k8s.io "basic-user" not found, clusterrole.rbac.authorization.k8s.io "service-binding-clusterworkloadresourcemappings-viewer-role" not found, clusterrole.rbac.authorization.k8s.io "system:oauth-token-deleter" not found, clusterrole.rbac.authorization.k8s.io "self-access-reviewer" not found, clusterrole.rbac.authorization.k8s.io "system:discovery" not found, clusterrole.rbac.authorization.k8s.io "system:build-strategy-docker" not found, clusterrole.rbac.authorization.k8s.io "system:openshift:scc:restricted-v2" not found, clusterrole.rbac.authorization.k8s.io "system:build-strategy-jenkinspipeline" not found, clusterrole.rbac.authorization.k8s.io "system:webhook" not found, clusterrole.rbac.authorization.k8s.io "self-provisioner" not found, clusterrole.rbac.authorization.k8s.io "system:public-info-viewer" not found, clusterrole.rbac.authorization.k8s.io "system:openshift:useroauthaccesstoken-manager" not found, clusterrole.rbac.authorization.k8s.io "system:scope-impersonation" not found, clusterrole.rbac.authorization.k8s.io "console-extensions-reader" not found, clusterrole.rbac.authorization.k8s.io "helm-chartrepos-viewer" not found, clusterrole.rbac.authorization.k8s.io "system:openshift:public-info-viewer" not found, clusterrole.rbac.authorization.k8s.io "system:openshift:discovery" not found, clusterrole.rbac.authorization.k8s.io "service-binding-bindablekinds-viewer-role" not found, clusterrole.rbac.authorization.k8s.io "system:build-strategy-source" not found]
    [odo] read: read /dev/stdin: input/output error
```

Same tests passing on IBM Cloud.

/override ci/prow/v4.11-integration-e2e

**Pull request merged**
