### PR TITLE
Document how odo works with projects/namespaces

### LINKED ISSUE #5860: Document how odo works with projects/namespaces
/area Documentation

There is some confusion on how odo works with namespaces. 
For example, users are wondering why the `odo project set` doesn't change the project that the component is in.

### PR DESCRIPTION
**Pull request by valaparthvi**
**What type of PR is this:**
/area documentation
/kind documentation

**What does this PR do / why we need it:**

**Which issue(s) this PR fixes:**

Fixes #5860

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [x] Documentation 

**How to test changes / Special notes to the reviewer:**

### CODE REVIEW

**Review by rm3l — CHANGES_REQUESTED** [review]
Maybe we could a note in the "odo dev" docs that documents that odo currently records the current namespace/project the first time it runs. And that changing it, for now, requires deleting the `.odo` folder.

Also, I think we should also update the docs for the "delete namespace/project" command, and mention that deletion does not change the namespace of the component either.

**Review by rm3l — APPROVED** [review]
Thanks for the changes!

**Comment by valaparthvi** [comment]
/override  OpenShift Integration tests/OpenShift Integration tests
/override ci/prow/v4.10-integration-e2e
/override windows-integration-test/Windows-test

Unrelated failures related to cmd_logs_test.

**Comment by feloy** [comment]
Very helpful doc, as I'm never sure myself about these points

/approve

**Pull request merged**
