### PR TITLE
Bump to v3.8.0

### PR DESCRIPTION
**Pull request by feloy**

### CODE REVIEW

**Review by rm3l — APPROVED** [review]

**Comment by feloy** [comment]
/override Kubernetes-Integration-Tests/Kubernetes-Docs-Integration-Tests
Flaky test

**Comment by rm3l** [comment]
@feloy Can we wait for tagging until https://github.com/redhat-developer/odo/issues/6636 is fixed? Otherwise, we might end up with annoying situations similar to https://github.com/redhat-developer/odo/issues/6379, and people might not be able to use `odo init` / `odo registry` / `odo preference view` at all if the cluster is not reachable.
I think we should also wait until https://github.com/redhat-developer/odo/issues/6637 is fixed too.

**Comment by feloy** [comment]
> @feloy Can we wait for tagging until #6636 is fixed? Otherwise, we might end up with annoying situations similar to #6379, and people might not be able to use `odo init` / `odo registry` / `odo preference view` at all if the cluster is not reachable.
> I think we should also wait until #6637 is fixed too.

Yes, sure, good catch, we will wait for these fixes

**Comment by feloy** [comment]
/override windows-integration-test/Windows-test
Flaky e2e test

**Pull request merged**
