### PR TITLE
Rename CheckError to LogErrorAndExit

### LINKED ISSUE #874: Rename cmd.checkError to cmd.logErrorAndExit to be more explicit about function
[kind/Proposal]

## What is the expected outcome?
Same as before, just with a different, more explicit name. ;)

## Why do you think this is relevant?
Manage expectations with respect to what this function does.

### PR DESCRIPTION
**Pull request by glefloch**
Signed-off-by: glefloch <glfloch@gmail.com>

## What is the purpose of this change? What does it change?
This change renames `CheckError` function name to `LogErrorAndExit`.

## Was the change discussed in an issue?
fixes #874 

## How to test changes?
Running tests make sure there are no regressions.

### CODE REVIEW

**Comment by geoand** [comment]
I vaguely remember this being discussed before. @metacosm do you perhaps remember anything specific?

**Comment by metacosm** [comment]
> Thanks for your contribution @glefloch!
> 
> I vaguely remember this being discussed before. @metacosm do you perhaps remember anything specific?

I opened #874 a while ago but I don't think a decision was made on it. That said, it's a low impact change. The only thing I can think of against doing that change is that `oc` uses `CheckError` as well but I don't know how relevant that is.

**Comment by geoand** [comment]
> > Thanks for your contribution @glefloch!
> > I vaguely remember this being discussed before. @metacosm do you perhaps remember anything specific?
> 
> I opened #874 a while ago but I don't think a decision was made on it. That said, it's a low impact change. The only thing I can think of against doing that change is that `oc` uses `CheckError` as well but I don't know how relevant that is.

Thanks for refreshing my memory!

**Comment by glefloch** [comment]
@geoand I should have ask before working on this. I saw the `good first issue` tag and then start to work on it.

**Comment by geoand** [comment]
> @geoand I should have ask before working on this. I saw the `good first issue` tag and then start to work on it.

For what it's worth, I agree with the change :)

**Comment by metacosm** [comment]
> For what it's worth, I agree with the change :)

I agree as well (I created the issue, after all!) :)

**Pull request merged**
