### PR TITLE
Fix: configuration shows volumes as containers

### LINKED ISSUE #5779: configuration shows volumes as containers
/kind bug

```
▶ odo init
  __
 /  \__     Initializing new component
 \__/  \    Files: Source code detected, a Devfile will be determined based upon source code autodetection
 /  \__/    odo version: v3.0.0-alpha2
 \__/

Interactive mode enabled, please answer the following questions:
Based on the files in the current directory odo detected
Language: java
Project type: spring
The devfile "java-springboot" from the registry "StagingRegistry" will be downloaded.
? Is this correct? Yes
 ✓  Downloading devfile "java-springboot" from registry "StagingRegistry" [2s]
Current component configuration:
Container "m2":
  Opened ports:
  Environment variables:
Container "tools":
  Opened ports:
   - 8080
  Environment variables:
   - DEBUG_PORT = 5858
? Select container for which you want to change configuration?  [Use arrows to move, type to filter]
> tools
  m2
  NONE - configuration is correct

```

devfile has `m2` component that is a `volume` in above output it shows it as it would be a `container`. non-container devfile components should be ignored.

/priority high

### PR DESCRIPTION
**Pull request by valaparthvi**
**What type of PR is this:**
/kind bug

**What does this PR do / why we need it:**
This PR fixes the Devfile Volume component shown when personalizing devfile configuration.

**Which issue(s) this PR fixes:**

Fixes #5779 

**PR acceptance criteria:**

- [x] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**
1. `touch pom.xml a.java`
2. `odo init`
3. Select java-springboot project type.
4. Make sure `m2` Volume component does not appear on the list.
```sh
➜  odo init
  __
 /  \__     Initializing new component
 \__/  \    Files: Source code detected, a Devfile will be determined based upon source code autodetection
 /  \__/    odo version: v3.0.0-alpha3
 \__/

Interactive mode enabled, please answer the following questions:
Based on the files in the current directory odo detected
Language: java
Project type: spring
The devfile "java-springboot" from the registry "MyRegistry" will be downloaded.
? Is this correct? Yes
 ✓  Downloading devfile "java-springboot" from registry "MyRegistry" [4s]
Current component configuration:
Container "tools":
  Opened ports:
   - 8080
  Environment variables:
   - DEBUG_PORT = 5858
? Select container for which you want to change configuration? NONE - configuration is correct
? Enter component name: my-java-springboot-app

Your new component 'my-java-springboot-app' is ready in the current directory.
To start editing your component, use 'odo dev' and open this folder in your favorite IDE.
Changes will be directly reflected on the cluster.
```

### CODE REVIEW

**Comment by valaparthvi** [comment]
/override  ci/prow/v4.10-integration-e2e

IBM tests pass.

**Comment by feloy** [comment]
/override ci/prow/v4.10-integration-e2e
Infra errors
IBM tests pass

**Pull request merged**
