### PR TITLE
Remove scripts which are no longer in use

### LINKED ISSUE #5278: Remaining namespaces after integration tests
/kind tests

A `cmd-project-xxxxxx` is remaining on the cluster after the integration tests are terminated.

This namespace should be removed after the tests.

### PR DESCRIPTION
**Pull request by anandrkskd**
Signed-off-by: anandrkskd <anandrkskd@gmail.com>

**What type of PR is this?**
/kind cleanup

**What does this PR do / why we need it**:
This PR removes redundant scripts which are no longer needed.
&
fix a test case in integration project test.

**Which issue(s) this PR fixes**:

Fixes #5278 (fix a test case in integration project test.)

**PR acceptance criteria**:

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

- [x] I have read the [test guidelines](https://github.com/redhat-developer/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by feloy** [comment]
Kubernetes Tests finished successfully.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5295-kubernetes-tests-174.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5295-kubernetes-tests-174.html)

**Comment by feloy** [comment]
Kubernetes Tests finished successfully.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5295-kubernetes-tests-175.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5295-kubernetes-tests-175.html)

**Comment by feloy** [comment]
Unit Tests finished successfully.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5295-unit-tests-188.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5295-unit-tests-188.html)

**Comment by feloy** [comment]
OpenShift Tests finished successfully.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5295-openshift-tests-204.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5295-openshift-tests-204.html)

**Comment by valaparthvi** [comment]
@anandrkskd Just so I understand, can you tell me the where these scripts were used and why you are removing them now? I understand why the minishift, ocp3 docs-sync, and travis scripts were removed, but what about the others, for e.g. create-packages, upload-packages, k8sibmc, and oc-cluster?

**Comment by anandrkskd** [comment]
> @anandrkskd Just so I understand, can you tell me the where these scripts were used and why you are removing them now?

Sure!
- create-packages - From the script, it seems it was previously used for creating deb and rpm packages using `fpm`. But now we use the brew builder to created binary.
 
- upload-packages - This script must be used to upload the generated binary to Bintray repository, and are not used now.
 
 - k8sibmc - this script was created to use the IBM Cloud cluster from PSI Jenkins for tests against odo.
 
- oc-cluster -  it is the script that we used  in Travis to setup OpenShift
 
@kadel  correct me if I am wrong.

**Pull request merged**
