### PR TITLE
Use adler32 into URL name

### LINKED ISSUE #4957: multiple components within the same app have route creation conflict
/kind bug

## What versions of software are you using?

**Operating System:**

**Output of `odo version`:** odo v2.2.3 (b2ca2a81a) - latest main branch

## How did you run odo exactly?
odo create nodejs component-a
odo push

odo create nodejs component-b
odo push

## Actual behavior
component-a created a route `http-3000-app`, and component-b is trying to create another `http-3000-app`, but failure since the route/URL already exist within the same namespace

## Expected behavior
the routes odo create should be unique for each component. should append component name instead of app name. one app can have multiple components, and this will result into potential conflicts if I have multiple components under a single app contain the same endpoint name

## Any logs, error output, etc?
release v2.2.3 works fine for me, since the route name was `<endpointName>-<CmpName>`
URL/route name now is `<endpointName>-<AppName>`
this is a regression introduced by: https://github.com/openshift/odo/pull/4858/files, at line https://github.com/mik-dass/odo/blob/e1391b26245af7a4d93e7a3fbb9a3c67a7b566b6/pkg/url/kubernetes.go#L280

which previously was :
```
routeName, err := util.NamespaceOpenShiftObject(url.Name, k.componentName)
```

### PR DESCRIPTION
**Pull request by feloy**
**What type of PR is this?**

/kind feature

**What does this PR do / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #4957 

**PR acceptance criteria**:

- [x] Unit test 

- [x] Integration test 

- [ ] Documentation 

- [x] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by dharmit** [comment]
@feloy My only concern is 4 occurrences of `suffix := fmt.Sprintf("%08x", adler32.Checksum([]byte(`. If we were to make any change or discover any bug in future, one would have to make sure to fix it at all the places. Otherwise, it works fine for me. Thanks for the fix and apologies for taking long to review it.

/approve
/lgtm

**Comment by feloy** [comment]
Kubernetes Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5238-kubernetes-tests-55.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5238-kubernetes-tests-55.html)

**Comment by feloy** [comment]
Unit Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5238-unit-tests-68.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5238-unit-tests-68.html)

**Comment by feloy** [comment]
Kubernetes Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5238-kubernetes-tests-58.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5238-kubernetes-tests-58.html)

**Comment by feloy** [comment]
OpenShift Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5238-openshift-tests-88.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5238-openshift-tests-88.html)

**Comment by feloy** [comment]
Unit Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5238-unit-tests-71.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5238-unit-tests-71.html)

**Comment by feloy** [comment]
Kubernetes Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5238-kubernetes-tests-72.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5238-kubernetes-tests-72.html)

**Comment by feloy** [comment]
Unit Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5238-unit-tests-86.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5238-unit-tests-86.html)

**Comment by feloy** [comment]
OpenShift Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5238-openshift-tests-102.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5238-openshift-tests-102.html)

**Comment by feloy** [comment]
> @feloy My only concern is 4 occurrences of `suffix := fmt.Sprintf("%08x", adler32.Checksum([]byte(`. If we were to make any change or discover any bug in future, one would have to make sure to fix it at all the places. Otherwise, it works fine for me. Thanks for the fix and apologies for taking long to review it.
> 

@dharmit I have created a function for this repeated code

**Comment by feloy** [comment]
Kubernetes Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5238-kubernetes-tests-77.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5238-kubernetes-tests-77.html)

**Comment by feloy** [comment]
Unit Tests finished.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5238-unit-tests-91.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5238-unit-tests-91.html)

**Comment by feloy** [comment]
/test psi-kubernetes-integration-e2e

```
{"component":"entrypoint","file":"prow/entrypoint/run.go:165","func":"k8s.io/test-infra/prow/entrypoint.Options.ExecuteProcess","level":"error","msg":"Process did not finish before 4h0m0s timeout","severity":"error","time":"2021-12-02T18:46:02Z"}
```

**Comment by feloy** [comment]
/test psi-kubernetes-integration-e2e

Timed out after 4h

**Comment by dharmit** [comment]
> @dharmit I have created a function for this repeated code

Thanks!

/unhold
/lgtm

**Pull request merged**
