### PR TITLE
fix login failure error: x509

### PR DESCRIPTION
**Pull request by anandrkskd**
Signed-off-by: anandrkskd <anandrkskd@gmail.com>

**What type of PR is this:**

/kind tests

**What does this PR do / why we need it:**
This PR fixes failing interop tests on 4.11/4.12

**Which issue(s) this PR fixes:**

Fixes #

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

### CODE REVIEW

**Comment by anandrkskd** [comment]
@feloy can you merge this one? We need to merge this one, in order to test if this helps in fixing the error we got during interop testing.

**Comment by feloy** [comment]
@anandrkskd What is the related issue for doing this?

**Comment by anandrkskd** [comment]
This PR is realated to https://github.com/redhat-developer/odo/issues/6075

**Pull request merged**
