### PR TITLE
Set platform and platformVersion in telemetry

### PR DESCRIPTION
**Pull request by feloy**
**What type of PR is this:**

/kind feature

**What does this PR do / why we need it:**

**Which issue(s) this PR fixes:**

Fixes partially #6508

**PR acceptance criteria:**

- [x] Unit test 

- [x] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

### CODE REVIEW

**Review by rm3l — COMMENTED** [review]
Can you also update the [USAGE_DATA.md](https://github.com/redhat-developer/odo/blob/main/USAGE_DATA.md) file to mention these new properties (along with the "experimental" property) ?

**Review by rm3l — CHANGES_REQUESTED** [review]
LGTM feature-wise. Added a few comments related to the tests.

**Review by rm3l — APPROVED** [review]
LGTM - thanks.

**Comment by feloy** [comment]
/override OpenShift-Integration-tests/OpenShift-Integration-tests
Flaky e2e test

/override windows-integration-test/Windows-test
Flaky logs test

**Review by rm3l — APPROVED** [review]

**Comment by feloy** [comment]
Rebased

**Comment by feloy** [comment]
/override Kubernetes-Integration-Tests/Kubernetes-Docs-Integration-Tests
Fixed by https://github.com/redhat-developer/odo/pull/6545

**Pull request merged**
