### PR TITLE
Fix odo init output in java quickstart guide

### PR DESCRIPTION
**Pull request by valaparthvi**
Signed-off-by: Parthvi Vala <pvala@redhat.com>

**What type of PR is this:**
/kind bug
/area documentation

**What does this PR do / why we need it:**
This PR fixes a bug with `odo dev` output for Java springboot quickstart.
**Which issue(s) this PR fixes:**

Fixes #

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [x] Documentation 

**How to test changes / Special notes to the reviewer:**

### CODE REVIEW

**Review by rm3l — COMMENTED** [review]
LGTM, but the commit message (and PR title) is more about the output of `odo init`, not `odo dev`.. Can you reword the commit message (and optionally the PR title), so it corresponds to the diff?

**Comment by valaparthvi** [comment]
> LGTM, but the commit message (and PR title) is more about the output of `odo init`, not `odo dev`.. Can you reword the commit message (and optionally the PR title), so it corresponds to the diff?

My bad :facepalm:

**Comment by rm3l** [comment]
> > LGTM, but the commit message (and PR title) is more about the output of `odo init`, not `odo dev`.. Can you reword the commit message (and optionally the PR title), so it corresponds to the diff?
> 
> My bad facepalm

No problem. Actually, can you reword the commit message as well? Since there is a single commit in this PR, I think the Merge Robot will use that as the squashed commit message. So I'd say it is more important to me to have the right information in the Git history.

**Comment by valaparthvi** [comment]
> > > LGTM, but the commit message (and PR title) is more about the output of `odo init`, not `odo dev`.. Can you reword the commit message (and optionally the PR title), so it corresponds to the diff?
> > 
> > 
> > My bad facepalm
> 
> No problem. Actually, can you reword the commit message as well? Since there is a single commit in this PR, I think the Merge Robot will use that as the squashed commit message. So I'd say it is more important to me to have the right information in the Git history.

Yes, sorry. I was working on something else and forgot. Will do it.

**Comment by valaparthvi** [comment]
/override OpenShift-Integration-tests/OpenShift-Integration-tests
/override Kubernetes-Integration-Tests/Kubernetes-Integration-Tests

Failures are unrelated to the PR changes.

**Review by rm3l — APPROVED** [review]

**Pull request merged**
