### PR TITLE
Add assertions for types implementing interfaces

### PR DESCRIPTION
**Pull request by feloy**
**What type of PR is this:**

/kind cleanup

### CODE REVIEW

**Review by rm3l — APPROVED** [review]
A big +1 for this.
Verifying interface compliance as much as possible at compile time is something recommended in the Coding Conventions wiki page: https://github.com/redhat-developer/odo/wiki/Dev:-Coding-Conventions#verify-interface-compliance

**Comment by dharmit** [comment]
Connection was reset.
```
✗  Downloading devfile "dotnet50" from registry "DefaultDevfileRegistry" [585ms]
   ✗  unable to download devfile: failed to pull stack dotnet50 from registry.stage.devfile.io/devfile-catalog/dotnet50:1.0.1 with allowed media types [application/vnd.devfileio.devfile.layer.v1 image/png image/svg+xml application/vnd.devfileio.vsx.layer.v1.tar application/x-tar]: failed to do request: Head "[https://registry.stage.devfile.io/v2/devfile-catalog/dotnet50/manifests/1.0.1&quot;:](https://registry.stage.devfile.io/v2/devfile-catalog/dotnet50/manifests/1.0.1%22:) read tcp 172.30.128.135:59098->3.83.37.194:443: read: connection reset by peer
  the command failed, the devfile has been removed from current directory
  
  ======================
  Unexpected error:
      <*fs.PathError | 0xc0006369f0>: {
          Op: "read",
          Path: "|0",
          Err: <*poll.DeadlineExceededError | 0x2b332a0>{},
      }
      read |0: i/o timeout
  occurred
```

**Review by rm3l — APPROVED** [review]

**Comment by feloy** [comment]
```
[13] [odo] Interactive mode enabled, please answer the following questions:
[13] [odo]  -  Downloading devfile "go"  ...
[13] [odo] 
 X  Downloading devfile "go" [1s]
[13] [odo]  X  unable to download devfile: unable to find the registry with name "go"
[13] [odo] the command failed, the devfile has been removed from current directory
```

Network / devfile registry issues?

/override windows-integration-test/Windows-test
/override ci/prow/v4.10-integration-e2e

**Pull request merged**
